//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;
namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public class DonViTinh
    {
        public DON_VI_TINH DonVi { get; set; }
        public NGUOI_DUNG NguoiTao { get; set; }
        public NGUOI_DUNG NguoiCapNhat { get; set; }
    }

    public partial class DON_VI_TINH
    {
        public DON_VI_TINH()
        {
            this.CHUYEN_DOI_DON_VI_TINH = new HashSet<CHUYEN_DOI_DON_VI_TINH>();
            this.SAN_PHAM = new HashSet<SAN_PHAM>();
        }
    
        public int MA_DON_VI { get; set; }

        [Required]
        [Display(Name = "Tên đơn vị")]
        [StringLength(100)]
        public string TEN_DON_VI { get; set; }

        [Display(Name = "Ghi chú")]
        [StringLength(1000)]
        public string GHI_CHU { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "dd/MM/yyyy", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CREATE_AT { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "dd/MM/yyyy", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> UPDATE_AT { get; set; }

        public string ACTIVE { get; set; }
    
        public virtual ICollection<CHUYEN_DOI_DON_VI_TINH> CHUYEN_DOI_DON_VI_TINH { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
        public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }

    }
}
