//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class ChuyenDoiDonViTinhModel
    {
        public IPagedList<CHUYEN_DOI_DON_VI_TINH> ResultList { get; set; }
        public SAN_PHAM SanPham { get; set; }
        public DON_VI_TINH DonViCuoi { get; set; }
        public DON_VI_TINH DonViVao { get; set; }
        public NGUOI_DUNG NguoiTao { get; set; }
        public NGUOI_DUNG NguoiCapNhat { get; set; }
        public CHUYEN_DOI_DON_VI_TINH ChuyenDoiDonVi { get; set; }
    }

    public partial class CHUYEN_DOI_DON_VI_TINH
    {
        public int MA_CHUYEN_DOI { get; set; }

        [Required]
        [Display(Name = "Tên sản phẩm")]
        public Nullable<int> MA_SAN_PHAN { get; set; }

        [Required]
        [Display(Name = "Đơn vị")]
        public Nullable<int> MA_DON_VI_VAO { get; set; }

        [Required]
        [Display(Name = "Hệ số")]
        public Nullable<double> HE_SO { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual DON_VI_TINH DON_VI_TINH { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
    }
}
