//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLLER_PERMISSION
    {
        public int ID { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTION_NAME { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public Nullable<bool> IS_ACCOUNTING { get; set; }
        public Nullable<bool> IS_METEDATA_MANAGER { get; set; }
        public Nullable<bool> IS_STORE_MANAGER { get; set; }
        public Nullable<bool> IS_SALER { get; set; }
    }
}
