//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG_DEBIT_HIST
    {
        public int ID { get; set; }
        public Nullable<int> MA_KHACH_HANG { get; set; }
        public Nullable<double> NO_TRUOC { get; set; }
        public Nullable<double> PHAT_SINH { get; set; }
        public Nullable<double> NO_SAU { get; set; }
        public Nullable<System.DateTime> NGAY_PHAT_SINH { get; set; }
        public Nullable<int> MA_NHAN_VIEN_TH { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG2 { get; set; }
    }
}
