//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public KHO()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
            this.NGUOI_DUNG3 = new HashSet<NGUOI_DUNG>();
            this.NHAP_KHO = new HashSet<NHAP_KHO>();
            this.XUAT_KHO = new HashSet<XUAT_KHO>();
            this.XUAT_KHO1 = new HashSet<XUAT_KHO>();
        }
    
        public int MA_KHO { get; set; }
        public string TEN_KHO { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public string DIA_CHI { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<int> MA_NGUOI_DUNG_DAU { get; set; }
    
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG2 { get; set; }
        public virtual ICollection<NGUOI_DUNG> NGUOI_DUNG3 { get; set; }
        public virtual ICollection<NHAP_KHO> NHAP_KHO { get; set; }
        public virtual ICollection<XUAT_KHO> XUAT_KHO { get; set; }
        public virtual ICollection<XUAT_KHO> XUAT_KHO1 { get; set; }
    }
}
