//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAP_XUAT_TON
    {
        public Nullable<int> MA_KHO { get; set; }
        public Nullable<int> MA_SAN_PHAM { get; set; }
        public double SO_LUONG_NHAP { get; set; }
        public double SO_LUONG_XUAT { get; set; }
        public double SO_LUONG_TON { get; set; }
    }
}
