//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class NhomSanPhamClass
    {
        public NHOM_SAN_PHAM NhomSanPham { get; set; }
        public NGUOI_DUNG NguoiTao { get; set; }
        public NGUOI_DUNG NguoiCapNhat { get; set; }
    }
    public partial class NHOM_SAN_PHAM
    {
        public NHOM_SAN_PHAM()
        {
            this.SAN_PHAM = new HashSet<SAN_PHAM>();
        }
    
        public int MA_NHOM { get; set; }

        [Required]
        [Display(Name = "Tên nhóm")]
        [StringLength(50)]
        public string TEN_NHOM { get; set; }

        [Display(Name = "Ghi chú")]
        [StringLength(1000)]
        public string GHI_CHU { get; set; }

        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
        public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }
    }
}
