//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_REPORT_TOTAL
    {
        public double SO_TIEN_KHACH_TRA { get; set; }
        public double SO_TIEN_NO_GOI_DAU { get; set; }
        public double BUGET_TOTAL { get; set; }
        public double RETURN_TOTAL { get; set; }
        public double TONG_CHI { get; set; }
        public double TONG_NHAP { get; set; }
        public double TONG_THU_NO { get; set; }
        public double TOTAL { get; set; }
        public Nullable<System.DateTime> DAY { get; set; }
    }
}
