//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RETURN_2_PROVIDER
    {
        public int ID { get; set; }
        public Nullable<int> MA_NHA_CUNG_CAP { get; set; }
        public Nullable<int> MA_PHIEU_TRA { get; set; }
        public Nullable<System.DateTime> NGAY_LAP_PHIEU { get; set; }
        public Nullable<int> MA_NV_LAP_PHIEU { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> MA_SAN_PHAM { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<int> MA_KHO_XUAT { get; set; }
        public Nullable<double> SO_LUONG_TEMP { get; set; }
        public Nullable<int> MA_DON_VI { get; set; }
        public Nullable<double> DON_GIA_TEMP { get; set; }
    }
}
