//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TRA_NHAP_TRA_NCC
    {
        public int MA_TRA_HANG { get; set; }
        public Nullable<int> MA_SAN_PHAM { get; set; }
        public double SO_LUONG { get; set; }
    }
}
