//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WARNING_PRODUCTS
    {
        public int MA_SAN_PHAM { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public Nullable<int> MA_DON_VI { get; set; }
        public string TEN_DON_VI { get; set; }
        public Nullable<double> TON_KHO { get; set; }
    }
}
