//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmsContext : DbContext
    {
        public SmsContext()
            : base("name=SmsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHUYEN_DOI_DON_VI_TINH> CHUYEN_DOI_DON_VI_TINH { get; set; }
        public DbSet<DON_VI_TINH> DON_VI_TINH { get; set; }
        public DbSet<HOA_DON> HOA_DON { get; set; }
        public DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public DbSet<KHO> KHOes { get; set; }
        public DbSet<KHU_VUC> KHU_VUC { get; set; }
        public DbSet<KIEM_KHO_HISTORY> KIEM_KHO_HISTORY { get; set; }
        public DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public DbSet<NHA_SAN_XUAT> NHA_SAN_XUAT { get; set; }
        public DbSet<NHAP_KHO> NHAP_KHO { get; set; }
        public DbSet<NHOM_NGUOI_DUNG> NHOM_NGUOI_DUNG { get; set; }
        public DbSet<PHAN_QUYEN> PHAN_QUYEN { get; set; }
        public DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public DbSet<TRA_HANG> TRA_HANG { get; set; }
        public DbSet<XUAT_KHO> XUAT_KHO { get; set; }
    }
}
