ALTER PROCEDURE [dbo].[SP_GET_RETURN_LIST]
@TEN_KHACH_HANG NVARCHAR(100), 
@FROM_DATE DATE, 
@TO_DATE DATE,
@MA_NHAN_VIEN_NHAN INT, 
@TEN_NHAN_VIEN NVARCHAR(100)
AS
BEGIN
	SELECT 
		TRA_HANG.MA_TRA_HANG, 
		TRA_HANG.TEN_KHACH_HANG, 
		TRA_HANG.NGAY_TRA, 
		TRA_HANG.STATUS,  
		TRA_HANG.NHAN_VIEN_NHAN,
		TRA_HANG.IMPORT_FLG, 
		TRA_HANG.RETURN_FLG,
		NGUOI_DUNG.TEN_NGUOI_DUNG, 
		ISNULL(TRA_HANG.MA_HOA_DON,0) MA_HOA_DON
	FROM
		TRA_HANG, 
		NGUOI_DUNG
	WHERE
		TRA_HANG.ACTIVE = 'A'
		AND TRA_HANG.MA_TRA_HANG IN (SELECT MA_TRA_HANG FROM V_MA_TRA_HANG)
		AND (TRA_HANG.IMPORT_FLG IS NULL OR TRA_HANG.IMPORT_FLG = 'FALSE'
				OR TRA_HANG.RETURN_FLG IS NULL OR TRA_HANG.RETURN_FLG = 'FALSE')
		AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TRA_HANG.TEN_KHACH_HANG LIKE '%' +  @TEN_KHACH_HANG + '%')
		AND (@TEN_NHAN_VIEN IS NULL OR @TEN_NHAN_VIEN = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @TEN_NHAN_VIEN + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_TRA AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_TRA AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAN = 0 OR TRA_HANG.NHAN_VIEN_NHAN = @MA_NHAN_VIEN_NHAN)
		AND TRA_HANG.NHAN_VIEN_NHAN = NGUOI_DUNG.MA_NGUOI_DUNG
		ORDER BY TRA_HANG.NGAY_TRA DESC
END


CREATE PROCEDURE SP_GET_RETURN_INFO_BY_ID
@MA_TRA_HANG INT
AS
BEGIN
	SELECT 
		TRA_HANG.MA_TRA_HANG,
		TRA_HANG.TEN_KHACH_HANG, 
		TRA_HANG.NGAY_TRA, 
		TRA_HANG.NHAN_VIEN_NHAN MA_NV_NHAN, 
		NGUOI_DUNG.TEN_NGUOI_DUNG,
		TRA_HANG.GHI_CHU, 
		TRA_HANG.MA_HOA_DON
	FROM
		TRA_HANG, 
		NGUOI_DUNG
	WHERE
		TRA_HANG.ACTIVE = 'A'
		AND TRA_HANG.MA_TRA_HANG = @MA_TRA_HANG
		AND TRA_HANG.NHAN_VIEN_NHAN = NGUOI_DUNG.MA_NGUOI_DUNG
END

ALTER TABLE CHI_TIET_XUAT_KHO
ADD DON_GIA_TEMP FLOAT

ALTER TABLE CHI_TIET_TRA_HANG
ADD DON_GIA_TEMP FLOAT


ALTER PROCEDURE SP_GET_RETURN_DETAIL_BY_ID
@MA_TRA_HANG INT
AS
BEGIN
	SELECT 
		CHI_TIET_TRA_HANG.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM,
		SAN_PHAM.CODE,
		ISNULL(CHI_TIET_TRA_HANG.GIA_BAN, 0) GIA_BAN,
		CASE ISNULL(CHI_TIET_TRA_HANG.DON_GIA_TEMP, 0) 
		WHEN 0 THEN CHI_TIET_TRA_HANG.GIA_VON
		ELSE CHI_TIET_TRA_HANG.DON_GIA_TEMP
		END AS DON_GIA,
		CASE ISNULL(CHI_TIET_TRA_HANG.MA_DON_VI,0)
		WHEN 0 THEN
			SAN_PHAM.MA_DON_VI
		ELSE CHI_TIET_TRA_HANG.MA_DON_VI
		END AS MA_DON_VI,
		DON_VI_TINH.TEN_DON_VI,
		CASE ISNULL(CHI_TIET_TRA_HANG.SO_LUONG_TEMP,0)
		WHEN 0 THEN
			CHI_TIET_TRA_HANG.SO_LUONG_TRA
		ELSE CHI_TIET_TRA_HANG.SO_LUONG_TEMP
		END AS SO_LUONG
	FROM 
		CHI_TIET_TRA_HANG, 
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		CHI_TIET_TRA_HANG.ACTIVE = 'A'
		AND CHI_TIET_TRA_HANG.MA_TRA_HANG = @MA_TRA_HANG
		AND CHI_TIET_TRA_HANG.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND 
		(
			CHI_TIET_TRA_HANG.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_TRA_HANG.MA_DON_VI IS NOT NULL AND CHI_TIET_TRA_HANG.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		)
END

SELECT 
		CHI_TIET_TRA_HANG.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM,
		SAN_PHAM.CODE,
		ISNULL(CHI_TIET_TRA_HANG.GIA_BAN, 0) GIA_BAN,
		CASE ISNULL(CHI_TIET_TRA_HANG.DON_GIA_TEMP, 0) 
		WHEN 0 THEN CHI_TIET_TRA_HANG.GIA_VON
		ELSE CHI_TIET_TRA_HANG.DON_GIA_TEMP
		END AS DON_GIA,
		CASE ISNULL(CHI_TIET_TRA_HANG.MA_DON_VI,0)
		WHEN 0 THEN
			SAN_PHAM.MA_DON_VI
		ELSE CHI_TIET_TRA_HANG.MA_DON_VI
		END AS MA_DON_VI,
		DON_VI_TINH.TEN_DON_VI,
		CASE ISNULL(CHI_TIET_TRA_HANG.SO_LUONG_TEMP,0)
		WHEN 0 THEN
			CHI_TIET_TRA_HANG.SO_LUONG_TRA
		ELSE CHI_TIET_TRA_HANG.SO_LUONG_TEMP
		END AS SO_LUONG
	FROM 
		CHI_TIET_TRA_HANG, 
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		CHI_TIET_TRA_HANG.ACTIVE = 'A'
		AND CHI_TIET_TRA_HANG.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND 
		(
			CHI_TIET_TRA_HANG.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_TRA_HANG.MA_DON_VI IS NOT NULL AND CHI_TIET_TRA_HANG.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		)