ALTER PROCEDURE [dbo].[SP_GET_RETURN_LIST]
@TEN_KHACH_HANG NVARCHAR(100), 
@FROM_DATE DATE, 
@TO_DATE DATE,
@MA_NHAN_VIEN_NHAN INT, 
@TEN_NHAN_VIEN NVARCHAR(100)
AS
BEGIN
	SELECT 
		TRA_HANG.MA_TRA_HANG, 
		TRA_HANG.TEN_KHACH_HANG, 
		TRA_HANG.NGAY_TRA, 
		TRA_HANG.STATUS,  
		TRA_HANG.NHAN_VIEN_NHAN,
		TRA_HANG.IMPORT_FLG, 
		TRA_HANG.RETURN_FLG,
		NGUOI_DUNG.TEN_NGUOI_DUNG, 
		ISNULL(TRA_HANG.MA_HOA_DON,0) MA_HOA_DON
	FROM
		TRA_HANG, 
		NGUOI_DUNG
	WHERE
		TRA_HANG.ACTIVE = 'A'
		AND TRA_HANG.MA_TRA_HANG IN (SELECT MA_TRA_HANG FROM V_MA_TRA_HANG)
		AND (TRA_HANG.IMPORT_FLG IS NULL OR TRA_HANG.IMPORT_FLG = 'FALSE'
				OR TRA_HANG.RETURN_FLG IS NULL OR TRA_HANG.RETURN_FLG = 'FALSE')
		AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TRA_HANG.TEN_KHACH_HANG LIKE '%' +  @TEN_KHACH_HANG + '%')
		AND (@TEN_NHAN_VIEN IS NULL OR @TEN_NHAN_VIEN = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @TEN_NHAN_VIEN + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_TRA AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_TRA AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAN = 0 OR TRA_HANG.NHAN_VIEN_NHAN = @MA_NHAN_VIEN_NHAN)
		AND TRA_HANG.NHAN_VIEN_NHAN = NGUOI_DUNG.MA_NGUOI_DUNG
		ORDER BY TRA_HANG.NGAY_TRA DESC
END


CREATE PROCEDURE SP_GET_RETURN_INFO_BY_ID
@MA_TRA_HANG INT
AS
BEGIN
	SELECT 
		TRA_HANG.MA_TRA_HANG,
		TRA_HANG.TEN_KHACH_HANG, 
		TRA_HANG.NGAY_TRA, 
		TRA_HANG.NHAN_VIEN_NHAN MA_NV_NHAN, 
		NGUOI_DUNG.TEN_NGUOI_DUNG,
		TRA_HANG.GHI_CHU, 
		TRA_HANG.MA_HOA_DON
	FROM
		TRA_HANG, 
		NGUOI_DUNG
	WHERE
		TRA_HANG.ACTIVE = 'A'
		AND TRA_HANG.MA_TRA_HANG = @MA_TRA_HANG
		AND TRA_HANG.NHAN_VIEN_NHAN = NGUOI_DUNG.MA_NGUOI_DUNG
END

