
  ALTER FUNCTION F_GET_IMPORT_BY_PR_ID_BF_DATE
  (
	@MA_SAN_PHAM   INT, 
	@MA_KHO INT,
	@IMPORT_DATE DATE
  )
  RETURNS FLOAT
  AS
  BEGIN
	RETURN ISNULL((SELECT SUM(SO_LUONG) SO_LUONG_NHAP 
	FROM V_NHAP_KHO 
	WHERE
	MA_SAN_PHAM = @MA_SAN_PHAM 
	AND(@MA_KHO = 0 OR  MA_KHO = @MA_KHO)
	AND CAST(NGAY_NHAP AS DATE) <= CAST(@IMPORT_DATE AS DATE)),0)
  END
  
  
  ALTER FUNCTION F_GET_EXPORT_BY_PR_ID_BF_DATE
  (
	@MA_SAN_PHAM   INT, 
	@MA_KHO INT,
	@IMPORT_DATE DATE
  )
  RETURNS FLOAT
  AS
  BEGIN
	RETURN ISNULL((SELECT SUM(SO_LUONG) SO_LUONG_XUAT
	FROM V_XUAT_KHO 
	WHERE
	MA_SAN_PHAM = @MA_SAN_PHAM 
	AND(@MA_KHO = 0 OR  MA_KHO_XUAT = @MA_KHO)
	AND CAST(NGAY_XUAT AS DATE) <= CAST(@IMPORT_DATE AS DATE)),0)
  END
  
  
  CREATE FUNCTION F_GET_INVENTORY
  (
	@MA_SAN_PHAM   INT, 
	@MA_KHO INT,
	@DATE DATE
  )
  RETURNS FLOAT
  AS
  BEGIN
	RETURN (SELECT DBO.F_GET_IMPORT_BY_PR_ID_BF_DATE (@MA_SAN_PHAM,@MA_KHO, @DATE ) 
	- DBO.F_GET_EXPORT_BY_PR_ID_BF_DATE(@MA_SAN_PHAM,@MA_KHO, @DATE)) 
  END
  
SELECT DBO.F_GET_INVENTORY(23542,0,GETDATE())
  
 ALTER PROC SP_COMPARE_INVENTORY 
 @MA_KHO INT, 
 @MA_SAN_PHAM INT, 
 @TEN_SAN_PHAM NVARCHAR(100),
 @MA_NHOM INT,
 @FIRST_DATE DATE, 
 @SECOND_DATE DATE
 AS
 BEGIN
	SELECT 
		SAN_PHAM.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		SAN_PHAM.MA_DON_VI, 
		DON_VI_TINH.TEN_DON_VI, 
		DBO.F_GET_INVENTORY(SAN_PHAM.MA_SAN_PHAM,@MA_KHO,@FIRST_DATE) INVEN_FIRST_DATE, 
		DBO.F_GET_INVENTORY(SAN_PHAM.MA_SAN_PHAM,@MA_KHO,@SECOND_DATE) INVEN_SECOND_DATE, 
		ABS(DBO.F_GET_INVENTORY(SAN_PHAM.MA_SAN_PHAM,@MA_KHO,@FIRST_DATE) -  DBO.F_GET_INVENTORY(SAN_PHAM.MA_SAN_PHAM,@MA_KHO,@SECOND_DATE)) COMPARED
	FROM 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
	SAN_PHAM.ACTIVE = 'A'
	AND (@MA_SAN_PHAM = 0 OR SAN_PHAM.MA_SAN_PHAM = @MA_SAN_PHAM)
	AND(@MA_NHOM = 0 OR SAN_PHAM.MA_NHOM = @MA_NHOM)
	AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR UPPER(SAN_PHAM.TEN_SAN_PHAM) LIKE '%' + UPPER(@TEN_SAN_PHAM) + '%')
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
 END
 