ALTER PROCEDURE SP_GET_DE_OF_RE_2_PR_BY_ST_AND_INV_ID
@STORE_ID INT,
@INVOICE_ID INT
AS
BEGIN 
	SELECT 
		TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		CASE ISNULL(TRA_HANG_NCC_CHI_TIET.SO_LUONG_TEMP,0)
		WHEN 0 THEN ISNULL(TRA_HANG_NCC_CHI_TIET.SO_LUONG,0) 
		ELSE TRA_HANG_NCC_CHI_TIET.SO_LUONG_TEMP END AS SO_LUONG, 
		CASE ISNULL(TRA_HANG_NCC_CHI_TIET.MA_DON_VI,0) 
		WHEN 0 THEN SAN_PHAM.MA_DON_VI
		ELSE TRA_HANG_NCC_CHI_TIET.MA_DON_VI END AS MA_DON_VI, 
		DON_VI_TINH.TEN_DON_VI,
		CASE ISNULL(TRA_HANG_NCC_CHI_TIET.DON_GIA_TEMP,0)
		WHEN 0 THEN TRA_HANG_NCC_CHI_TIET.DON_GIA
		ELSE TRA_HANG_NCC_CHI_TIET.DON_GIA_TEMP END AS DON_GIA
	FROM 
		TRA_HANG_NCC_CHI_TIET, 
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		TRA_HANG_NCC_CHI_TIET.ACTIVE = 'A'
		AND TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC =  @INVOICE_ID 
		AND (@STORE_ID = 0 OR TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT = @STORE_ID)
		AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE XUAT_KHO.ACTIVE ='A' AND XUAT_KHO.MA_PHIEU_TRA_NCC = TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC)
		AND TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND (
			TRA_HANG_NCC_CHI_TIET.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			TRA_HANG_NCC_CHI_TIET.MA_DON_VI IS NOT NULL AND TRA_HANG_NCC_CHI_TIET.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			)
END


ALTER PROCEDURE SP_EXPORT_4_RETURN_2_PROVIDER
@ID INT,
@STORE_ID INT, 
@USER_ID INT,
@EXPORT_DATE DATE, 
@RETURN_VALUE INT OUTPUT
AS
BEGIN
	DECLARE  @SO_LUONG_TON FLOAT;
	DECLARE  @MA_SAN_PHAM INT;
	DECLARE  @LASTEST BIT;
	DECLARE  @DON_GIA FLOAT;
	DECLARE  @DON_GIA_TEMP FLOAT;
	DECLARE  @SO_LUONG FLOAT;
	DECLARE  @SO_LUONG_TEMP FLOAT;
	DECLARE  @MA_DON_VI INT;
	DECLARE  @MA_KHO_XUAT INT;
	DECLARE  @MA_XUAT_KHO INT;
	DECLARE  @FLG BIT;
	DECLARE  @NEXT_STORE_ID INT;
	
	IF @STORE_ID <> 0
		BEGIN
			DECLARE DETAIL_CURSOR CURSOR FOR
			SELECT 
				TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM,
				TRA_HANG_NCC_CHI_TIET.SO_LUONG
			FROM
				TRA_HANG_NCC_CHI_TIET
			WHERE
				TRA_HANG_NCC_CHI_TIET.ACTIVE = 'A'
				AND TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC = @ID
				AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE XUAT_KHO.MA_PHIEU_TRA_NCC = TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC AND XUAT_KHO.ACTIVE ='A') 
				AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT = @STORE_ID;
			
			SET @FLG = 'TRUE';
			
			OPEN DETAIL_CURSOR 
			FETCH NEXT FROM DETAIL_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG
			WHILE @@FETCH_STATUS = 0 
			BEGIN
				SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@STORE_ID, @MA_SAN_PHAM);
				IF @SO_LUONG_TON IS NULL OR @SO_LUONG_TON = 0 OR @SO_LUONG_TON < @SO_LUONG
				BEGIN
					SET @FLG = 'FALSE'
					BREAK;
				END
				FETCH NEXT FROM DETAIL_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG
			END;
			
			CLOSE DETAIL_CURSOR;
			DEALLOCATE DETAIL_CURSOR;
			
			IF @FLG = 'FALSE'
			BEGIN
				SET @RETURN_VALUE = 0;
			END
			ELSE
			BEGIN
				DECLARE DETAIL_CURSOR_EXPORT CURSOR FOR
				SELECT 
					TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM,
					TRA_HANG_NCC_CHI_TIET.SO_LUONG,
					TRA_HANG_NCC_CHI_TIET.DON_GIA,
					TRA_HANG_NCC_CHI_TIET.DON_GIA_TEMP,
					TRA_HANG_NCC_CHI_TIET.SO_LUONG_TEMP,
					TRA_HANG_NCC_CHI_TIET.MA_DON_VI, 
					TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT
				FROM
					TRA_HANG_NCC_CHI_TIET
				WHERE
					TRA_HANG_NCC_CHI_TIET.ACTIVE = 'A'
					AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE XUAT_KHO.MA_PHIEU_TRA_NCC = TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC AND XUAT_KHO.ACTIVE ='A') 
					AND TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC = @ID
					AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT = @STORE_ID;
				-- Insert into XUAT_KHO table
				INSERT INTO 
				XUAT_KHO 
				(	
					MA_HOA_DON, 
					LY_DO_XUAT,  --4 export for returning to provider
					MA_KHO_XUAT,
					NGAY_XUAT, 
					MA_NHAN_VIEN_XUAT,
					MA_PHIEU_TRA_NCC,
					CREATE_BY, 
					UPDATE_BY, 
					CREATE_AT, 
					UPDATE_AT, 
					ACTIVE
				)
				VALUES
				(
					@ID, 
					4, 
					@STORE_ID, 
					@EXPORT_DATE, 
					@USER_ID,
					@ID,
					@USER_ID, 
					@USER_ID, 
					GETDATE(), 
					GETDATE(),
					'A'
				); 
				SET @MA_XUAT_KHO = (SELECT SCOPE_IDENTITY());
				
				OPEN DETAIL_CURSOR_EXPORT 
				FETCH NEXT FROM DETAIL_CURSOR_EXPORT INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @DON_GIA_TEMP, @SO_LUONG_TEMP, @MA_DON_VI, @MA_KHO_XUAT
				WHILE @@FETCH_STATUS = 0 
				BEGIN
					-- Insert details into CHI_TIET_XUAT_KHO table
					INSERT INTO
					CHI_TIET_XUAT_KHO
					(
						MA_XUAT_KHO, 
						MA_SAN_PHAM, 
						SO_LUONG, 
						GIA_XUAT,
						DON_GIA_TEMP,
						SO_LUONG_TEMP, 
						MA_DON_VI,
						CREATE_BY, 
						UPDATE_BY, 
						CREATE_AT, 
						UPDATE_AT, 
						ACTIVE
					)
					VALUES
					(
						@MA_XUAT_KHO, 
						@MA_SAN_PHAM, 
						@SO_LUONG, 
						@DON_GIA, 
						@DON_GIA_TEMP,
						@SO_LUONG_TEMP, 
						@MA_DON_VI,
						@USER_ID, 
						@USER_ID,
						GETDATE(), 
						GETDATE(), 
						'A'
					);					
					FETCH NEXT FROM DETAIL_CURSOR_EXPORT INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @DON_GIA_TEMP, @SO_LUONG_TEMP, @MA_DON_VI, @MA_KHO_XUAT
				END;
			END;
		END
	ELSE
		BEGIN
			DECLARE DETAIL_CURSOR CURSOR FOR
			SELECT 
				TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM,
				TRA_HANG_NCC_CHI_TIET.SO_LUONG, 
				TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT
			FROM
				TRA_HANG_NCC_CHI_TIET
			WHERE
				TRA_HANG_NCC_CHI_TIET.ACTIVE = 'A'
				AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE XUAT_KHO.MA_PHIEU_TRA_NCC = TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC AND XUAT_KHO.ACTIVE ='A') 
				AND TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC = @ID
			ORDER BY TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT;
			
			SET @FLG = 'TRUE';
			
			OPEN DETAIL_CURSOR 
			FETCH NEXT FROM DETAIL_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG, @STORE_ID
			WHILE @@FETCH_STATUS = 0 
			BEGIN
				SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@STORE_ID, @MA_SAN_PHAM);
				IF @SO_LUONG_TON IS NULL OR @SO_LUONG_TON = 0 OR @SO_LUONG_TON < @SO_LUONG
				BEGIN
					SET @FLG = 'FALSE'
					BREAK;
				END
				FETCH NEXT FROM DETAIL_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG
			END;
			
			CLOSE DETAIL_CURSOR;
			DEALLOCATE DETAIL_CURSOR;
			
			IF @FLG = 'FALSE'
			BEGIN
				SET @RETURN_VALUE = 0;
			END
			IF @FLG = 'TRUE'
			BEGIN
				DECLARE DETAIL_CURSOR_EXPORT CURSOR FOR
				SELECT 
					TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM,
					TRA_HANG_NCC_CHI_TIET.SO_LUONG,
					TRA_HANG_NCC_CHI_TIET.DON_GIA,
					TRA_HANG_NCC_CHI_TIET.DON_GIA_TEMP,
					TRA_HANG_NCC_CHI_TIET.SO_LUONG_TEMP,
					TRA_HANG_NCC_CHI_TIET.MA_DON_VI, 
					TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT
				FROM
					TRA_HANG_NCC_CHI_TIET
				WHERE
					TRA_HANG_NCC_CHI_TIET.ACTIVE = 'A'
					AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE XUAT_KHO.MA_PHIEU_TRA_NCC = TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC AND XUAT_KHO.ACTIVE ='A') 
					AND TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC = @ID
				ORDER BY TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT;
				
				SET @STORE_ID = 0;
				
				OPEN DETAIL_CURSOR_EXPORT
				FETCH NEXT FROM DETAIL_CURSOR_EXPORT INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @DON_GIA_TEMP, @SO_LUONG_TEMP, @MA_DON_VI, @NEXT_STORE_ID
				WHILE @@FETCH_STATUS = 0 
				BEGIN
					IF @STORE_ID <> @NEXT_STORE_ID
					BEGIN
						SET @STORE_ID = @NEXT_STORE_ID;
						INSERT INTO 
						XUAT_KHO 
						(	
							MA_HOA_DON, 
							LY_DO_XUAT,  --4 export for returning to provider
							MA_KHO_XUAT,
							NGAY_XUAT, 
							MA_NHAN_VIEN_XUAT,
							MA_PHIEU_TRA_NCC,
							CREATE_BY, 
							UPDATE_BY, 
							CREATE_AT, 
							UPDATE_AT, 
							ACTIVE
						)
						VALUES
						(
							@ID, 
							4, 
							@STORE_ID, 
							@EXPORT_DATE, 
							@USER_ID,
							@ID,
							@USER_ID, 
							@USER_ID, 
							GETDATE(), 
							GETDATE(),
							'A'
						); 
						SET @MA_XUAT_KHO = (SELECT SCOPE_IDENTITY());
					END;
					-- Insert details into CHI_TIET_XUAT_KHO table
					INSERT INTO
					CHI_TIET_XUAT_KHO
					(
						MA_XUAT_KHO, 
						MA_SAN_PHAM, 
						SO_LUONG, 
						GIA_XUAT,
						DON_GIA_TEMP,
						SO_LUONG_TEMP, 
						MA_DON_VI,
						CREATE_BY, 
						UPDATE_BY, 
						CREATE_AT, 
						UPDATE_AT, 
						ACTIVE
					)
					VALUES
					(
						@MA_XUAT_KHO, 
						@MA_SAN_PHAM, 
						@SO_LUONG, 
						@DON_GIA, 
						@DON_GIA_TEMP,
						@SO_LUONG_TEMP, 
						@MA_DON_VI,
						@USER_ID, 
						@USER_ID,
						GETDATE(), 
						GETDATE(), 
						'A'
					);	
					FETCH NEXT FROM DETAIL_CURSOR_EXPORT INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @DON_GIA_TEMP, @SO_LUONG_TEMP, @MA_DON_VI, @MA_KHO_XUAT
				END;
				CLOSE DETAIL_CURSOR_EXPORT;
				DEALLOCATE DETAIL_CURSOR_EXPORT;
				SET @RETURN_VALUE = 1;
			END;
		END;
END
