ALTER PROCEDURE SP_GET_DE_OF_RE_2_PR_BY_ST_AND_INV_ID
@STORE_ID INT,
@INVOICE_ID INT
AS
BEGIN 
	SELECT 
		TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		CASE ISNULL(TRA_HANG_NCC_CHI_TIET.SO_LUONG_TEMP,0)
		WHEN 0 THEN ISNULL(TRA_HANG_NCC_CHI_TIET.SO_LUONG,0) 
		ELSE TRA_HANG_NCC_CHI_TIET.SO_LUONG_TEMP END AS SO_LUONG, 
		CASE ISNULL(TRA_HANG_NCC_CHI_TIET.MA_DON_VI,0) 
		WHEN 0 THEN SAN_PHAM.MA_DON_VI
		ELSE TRA_HANG_NCC_CHI_TIET.MA_DON_VI END AS MA_DON_VI, 
		DON_VI_TINH.TEN_DON_VI,
		CASE ISNULL(TRA_HANG_NCC_CHI_TIET.DON_GIA_TEMP,0)
		WHEN 0 THEN TRA_HANG_NCC_CHI_TIET.DON_GIA
		ELSE TRA_HANG_NCC_CHI_TIET.DON_GIA_TEMP END AS DON_GIA
	FROM 
		TRA_HANG_NCC_CHI_TIET, 
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		TRA_HANG_NCC_CHI_TIET.ACTIVE = 'A'
		AND TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC =  @INVOICE_ID 
		AND (@STORE_ID = 0 OR TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT = @STORE_ID)
		AND TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE XUAT_KHO.ACTIVE ='A' AND XUAT_KHO.MA_PHIEU_TRA_NCC = TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC)
		AND TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND (
			TRA_HANG_NCC_CHI_TIET.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			TRA_HANG_NCC_CHI_TIET.MA_DON_VI IS NOT NULL AND TRA_HANG_NCC_CHI_TIET.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			)
END

