ALTER VIEW [dbo].[V_WARNING_PRODUCTS]
AS
SELECT
	SAN_PHAM.MA_SAN_PHAM, 
	SAN_PHAM.TEN_SAN_PHAM,
	SAN_PHAM.MA_DON_VI,
	DON_VI_TINH.TEN_DON_VI, 
	DBO.F_GET_TON_TOTAL(MA_SAN_PHAM) TON_KHO
FROM 
SAN_PHAM,
DON_VI_TINH
WHERE SAN_PHAM.ACTIVE = 'A' 
AND SAN_PHAM.CO_SO_TOI_THIEU >= ISNULL(DBO.F_GET_TON_TOTAL(MA_SAN_PHAM),0)
AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI