ALTER PROCEDURE [dbo].[SP_GET_IMPORT]
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_NHAN_VIEN_NHAP INT, 
@TEN_NHAN_VIEN_NHAP NVARCHAR(100),
@LY_DO_NHAP INT, 
@MA_KHO INT, 
@TEN_KHO NVARCHAR(100),
@MA_NHA_CC INT, 
@TEN_NHA_CUNG_CAP NVARCHAR(100)
AS
BEGIN
	SELECT 
		NHAP_KHO.MA_NHAP_KHO, 
		NHAP_KHO.SO_HOA_DON, 
		NHAP_KHO.NGAY_NHAP, 
		NHAP_KHO.NHAN_VIEN_NHAP, 
		NHAP_KHO.MA_NHA_CUNG_CAP, 
		NHAP_KHO.MA_KHO, 
		NGUOI_DUNG.TEN_NGUOI_DUNG, 
		KHO.TEN_KHO, 
		NHA_CUNG_CAP.TEN_NHA_CUNG_CAP
	FROM 
		NHAP_KHO LEFT JOIN NHA_CUNG_CAP ON NHAP_KHO.MA_NHA_CUNG_CAP = NHA_CUNG_CAP.MA_NHA_CUNG_CAP,
		KHO, 
		NGUOI_DUNG
	WHERE
		NHAP_KHO.ACTIVE = 'A'
		AND (@TEN_NHAN_VIEN_NHAP IS NULL OR @TEN_NHAN_VIEN_NHAP = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%'  + @TEN_NHAN_VIEN_NHAP + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAP = 0 OR NHAN_VIEN_NHAP = @MA_NHAN_VIEN_NHAP)
		AND (@LY_DO_NHAP = 0 OR LY_DO_NHAP = @LY_DO_NHAP)
		AND (@MA_KHO = 0 OR NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR KHO.TEN_KHO LIKE '%' +  @TEN_KHO + '%')
		AND (@MA_NHA_CC = 0 OR NHAP_KHO.MA_NHA_CUNG_CAP = @MA_NHA_CC) 
		AND (@TEN_NHA_CUNG_CAP IS NULL OR @TEN_NHA_CUNG_CAP = '' OR NHA_CUNG_CAP.TEN_NHA_CUNG_CAP LIKE '%' + @TEN_NHA_CUNG_CAP + '%')
		AND NHAP_KHO.MA_KHO = KHO.MA_KHO
		AND NHAP_KHO.NHAN_VIEN_NHAP = NGUOI_DUNG.MA_NGUOI_DUNG
END


ALTER PROCEDURE SP_GET_SMS_MESSAGES
@MA_NHOM_NGUOI_DUNG INT, 
@TEN_NHOM_NGUOI_DUNG NVARCHAR(100), 
@NOI_DUNG NVARCHAR(1000), 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		ID, 
		ID_NGUOI_GUI,
		NGUOI_DUNG.TEN_NGUOI_DUNG,
		ID_NHOM_NGUOI_NHAN, 
		NHOM_NGUOI_DUNG.TEN_NHOM,
		NGAY_GUI, 
		NOI_DUNG
	FROM 
		SMS_MESSAGES
		LEFT JOIN NHOM_NGUOI_DUNG ON SMS_MESSAGES.ID_NHOM_NGUOI_NHAN = NHOM_NGUOI_DUNG.MA_NHOM, 
		NGUOI_DUNG
	WHERE
		SMS_MESSAGES.ACTIVE = 'A'
		AND (@MA_NHOM_NGUOI_DUNG = 0 OR ID_NHOM_NGUOI_NHAN = @MA_NHOM_NGUOI_DUNG)
		AND (@TEN_NHOM_NGUOI_DUNG IS NULL OR @TEN_NHOM_NGUOI_DUNG = '' OR NHOM_NGUOI_DUNG.TEN_NHOM LIKE '%' + @TEN_NHOM_NGUOI_DUNG + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_GUI AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_GUI AS DATE) <= CAST(@TO_DATE AS DATE))
		AND SMS_MESSAGES.ID_NGUOI_GUI = NGUOI_DUNG.MA_NGUOI_DUNG
	ORDER BY NGAY_GUI DESC
END