ALTER PROCEDURE [dbo].[SP_REPORT_BY_WEEK]
@START_TIME DATE, 
@END_TIME DATE
AS
BEGIN
	SELECT * FROM
	(
		SELECT 
			ISNULL(SALES.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA,
			ISNULL(SALES.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU, 
			ISNULL(SALES.TOTAL,0) AS BUGET_TOTAL,  
			ISNULL(RETURN_TABLE.TOTAL,0) AS RETURN_TOTAL,
			ISNULL(SALES.TOTAL,0) - ISNULL(RETURN_TABLE.TOTAL,0) AS TOTAL,
			ISNULL(SALES.WEEK,  RETURN_TABLE.WEEK) WEEK,
			ISNULL(SALES.YEAR,RETURN_TABLE.YEAR) YEAR,
			ISNULL(SALES.START_DATE, RETURN_TABLE.START_DATE) START_DATE, 
			ISNULL(SALES.END_DATE, RETURN_TABLE.END_DATE) END_DATE
		FROM
		(	
			SELECT 
			ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA, 
			ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
			ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0)  +  ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) TOTAL,
			DATEPART(wk, HOA_DON.NGAY_BAN) WEEK, 
			YEAR(HOA_DON.NGAY_BAN) YEAR,
			DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 0) START_DATE, 
			DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 6) END_DATE
			FROM 
			HOA_DON
			WHERE
			HOA_DON.ACTIVE = 'A'
			AND (@START_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) >= CAST(@START_TIME AS DATE))
			AND (@END_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) <= CAST(@END_TIME AS DATE))
			GROUP BY 
			DATEPART(wk, HOA_DON.NGAY_BAN),
			DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 0) ,
			DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 6), 
			YEAR(HOA_DON.NGAY_BAN)
		)SALES FULL JOIN 
		(
			SELECT 
			ISNULL(SUM(V_TRA_HANG.TOTAL),0) TOTAL, 
			DATEPART(wk, V_TRA_HANG.NGAY_TRA) WEEK, 
			YEAR(V_TRA_HANG.NGAY_TRA) YEAR,
			DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 0) START_DATE, 
			DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 6) END_DATE
			FROM 
			V_TRA_HANG
			WHERE
			(@START_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) >= CAST(@START_TIME AS DATE))
			AND (@END_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) <= CAST(@END_TIME AS DATE))
			GROUP BY 
			DATEPART(wk, V_TRA_HANG.NGAY_TRA),
			DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 0) ,
			DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 6), 
			YEAR(V_TRA_HANG.NGAY_TRA)
		)RETURN_TABLE
		ON SALES.WEEK = RETURN_TABLE.WEEK AND SALES.YEAR = RETURN_TABLE.YEAR		
		--ORDER BY SALES.YEAR, SALES.WEEK DESC 
	)TEMP
	ORDER BY TEMP.YEAR, TEMP.WEEK DESC
END
