ALTER TABLE NGUOI_DUNG 
ADD 
CONSTRAINT AK_TransactionID UNIQUE(USER_NAME) 


CREATE TABLE SMS_MASTER
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	NAME NVARCHAR(50) NOT NULL,
	VALUE NVARCHAR(100) NOT NULL,
	GHI_CHU NVARCHAR(1000), 
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)

CREATE TABLE KHACH_HANG_DEBIT_HIST
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	MA_KHACH_HANG INT FOREIGN KEY REFERENCES KHACH_HANG(MA_KHACH_HANG), 
	NO_TRUOC FLOAT,
	PHAT_SINH FLOAT, 
	NO_SAU FLOAT,
	NGAY_PHAT_SINH DATE,
	MA_NHAN_VIEN_TH INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),
	GHI_CHU NVARCHAR(1000), 
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)