CREATE PROC SP_GET_TON_KHO_BY_ID
@INPUT_ID INT 
AS
BEGIN
	DECLARE @DYN_SQL VARCHAR(MAX);
	DECLARE @MA_KHO INT;
	DECLARE @MA_SAN_PHAM INT;
	DECLARE @TEN_SAN_PHAM NVARCHAR(100)
	DECLARE @TEN_DON_VI NVARCHAR(100)
	DECLARE @SO_LUONG_TON FLOAT;
	DECLARE @GIA_BAN_1 FLOAT;
	DECLARE @GIA_BAN_2 FLOAT;
	DECLARE @GIA_BAN_3 FLOAT;
	DECLARE @CHIEC_KHAU_1 FLOAT;
	DECLARE @CHIEC_KHAU_2 FLOAT;
	DECLARE @CHIEC_KHAU_3 FLOAT;
	DECLARE @COLUMN_NAME VARCHAR (50);
	DECLARE @ID INT;
	DECLARE @SO_LUONG_KHO INT;
	DECLARE @I INT;
	
	DECLARE SAN_PHAM_MY_CURSOR CURSOR FOR
	SELECT 
	MA_SAN_PHAM, 
	TEN_SAN_PHAM, 
	TEN_DON_VI, 
	ISNULL(GIA_BAN_1,0), 
	ISNULL(GIA_BAN_2,0), 
	ISNULL(GIA_BAN_3,0), 
	ISNULL(CHIEC_KHAU_1,0), 
	ISNULL(CHIEC_KHAU_2,0), 
	ISNULL(CHIEC_KHAU_3,0)
	FROM SAN_PHAM, DON_VI_TINH
	WHERE
	SAN_PHAM.ACTIVE = 'A'
	AND DON_VI_TINH.ACTIVE = 'A'
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	AND SAN_PHAM.MA_SAN_PHAM = @INPUT_ID;
	
	SET NOCOUNT ON;
	
	CREATE TABLE #TEMP_TON_KHO 
	(
		ID INT IDENTITY(1,1) PRIMARY KEY,  
		MA_SAN_PHAM INT, 
		TEN_SAN_PHAM NVARCHAR(100), 
		TEN_DON_VI NVARCHAR(100), 
		GIA_BAN_1 FLOAT, 
		GIA_BAN_2 FLOAT, 
		GIA_BAN_3 FLOAT, 
		CHIEC_KHAU_1 FLOAT, 
		CHIEC_KHAU_2 FLOAT, 
		CHIEC_KHAU_3 FLOAT
	)
	
	SET @SO_LUONG_KHO = ISNULL((SELECT COUNT(MA_KHO) FROM KHO WHERE ACTIVE = 'A'),0);
	SET @I = 1;
	WHILE @I <= @SO_LUONG_KHO AND @I <=5
	BEGIN
		SET @COLUMN_NAME = '';
		SET @COLUMN_NAME = 'TON_KHO_' + CAST(@I AS VARCHAR)
		SET @DYN_SQL = 'ALTER TABLE #TEMP_TON_KHO ADD ' + @COLUMN_NAME +' FLOAT DEFAULT 0';
		EXEC(@DYN_SQL);
		SET @I = @I+1;
	END
	
	SET @DYN_SQL = 'ALTER TABLE #TEMP_TON_KHO ADD TOTAL FLOAT DEFAULT 0';
	EXEC(@DYN_SQL)	
	
	OPEN SAN_PHAM_MY_CURSOR 
		FETCH NEXT FROM SAN_PHAM_MY_CURSOR INTO @MA_SAN_PHAM ,@TEN_SAN_PHAM, @TEN_DON_VI, @GIA_BAN_1, @GIA_BAN_2, @GIA_BAN_3, @CHIEC_KHAU_1, @CHIEC_KHAU_2, @CHIEC_KHAU_3
		WHILE @@FETCH_STATUS = 0  
	BEGIN
		SET @SO_LUONG_TON = ISNULL(DBO.F_GET_TON_TOTAL(@MA_SAN_PHAM),0);
		INSERT INTO #TEMP_TON_KHO(MA_SAN_PHAM, TEN_SAN_PHAM, TEN_DON_VI, GIA_BAN_1, GIA_BAN_2, GIA_BAN_3, CHIEC_KHAU_1, CHIEC_KHAU_2, CHIEC_KHAU_3) 
		VALUES (@MA_SAN_PHAM, @TEN_SAN_PHAM, @TEN_DON_VI, @GIA_BAN_1, @GIA_BAN_2, @GIA_BAN_3, @CHIEC_KHAU_1, @CHIEC_KHAU_2, @CHIEC_KHAU_3);
		SET @ID = (SELECT SCOPE_IDENTITY());
		SET @DYN_SQL = 'UPDATE #TEMP_TON_KHO SET TOTAL  = ' + CAST(@SO_LUONG_TON AS VARCHAR)+ ' WHERE ID = ' + CAST(@ID AS VARCHAR);	
		EXEC(@DYN_SQL);		
		
		SET @I = 1;
		DECLARE KHO_CURSOR_IST CURSOR FOR
		SELECT MA_KHO 
		FROM KHO
		WHERE ACTIVE = 'A'
		ORDER BY MA_KHO; 
	
		OPEN KHO_CURSOR_IST 
		FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
		WHILE @@FETCH_STATUS = 0 AND @I <= 5
		BEGIN
			SET @COLUMN_NAME = '';
			SET @COLUMN_NAME = 'TON_KHO_' + CAST(@I AS VARCHAR);
			SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@MA_KHO, @MA_SAN_PHAM);
			SET @DYN_SQL = 'UPDATE #TEMP_TON_KHO SET ' + @COLUMN_NAME + ' = ' + CAST(@SO_LUONG_TON AS VARCHAR) + ' WHERE ID = ' + CAST(@ID AS VARCHAR);
			EXEC(@DYN_SQL);
			SET @I = @I+1;
			FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
		END;					
		CLOSE KHO_CURSOR_IST;
		DEALLOCATE KHO_CURSOR_IST;
		FETCH NEXT FROM SAN_PHAM_MY_CURSOR INTO @MA_SAN_PHAM ,@TEN_SAN_PHAM, @TEN_DON_VI, @GIA_BAN_1, @GIA_BAN_2, @GIA_BAN_3, @CHIEC_KHAU_1, @CHIEC_KHAU_2, @CHIEC_KHAU_3
	END;
	CLOSE SAN_PHAM_MY_CURSOR
	DEALLOCATE SAN_PHAM_MY_CURSOR
	
	SELECT TOP 999
	#TEMP_TON_KHO.*
	FROM 
	#TEMP_TON_KHO
END


EXEC SP_GET_TON_KHO_BY_ID 2

ALTER TABLE HOA_DON
ADD 
	MA_NHAN_VIEN_THU_TIEN INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG)
	
CREATE VIEW V_HOA_DON
AS
SELECT 
	HOA_DON.MA_HOA_DON, 
	HOA_DON.SO_HOA_DON, 
	HOA_DON.MA_KHACH_HANG, 
	CASE 
		WHEN HOA_DON.MA_KHACH_HANG IS NULL 
			THEN HOA_DON.TEN_KHACH_HANG
		ELSE
			KHACH_HANG.TEN_KHACH_HANG
		END AS TEN_KHACH_HANG, 
	HOA_DON.MA_NHAN_VIEN_BAN,
	NGUOI_DUNG.TEN_NGUOI_DUNG TEN_NHAN_VIEN_BAN,
	HOA_DON.NGAY_BAN, 
	HOA_DON.NGAY_GIAO, 
	HOA_DON.DIA_CHI_GIAO_HANG, 
	HOA_DON.MA_NHAN_VIEN_THU_TIEN,
	NHAN_VIEN_TT.TEN_NGUOI_DUNG TEN_NV_THU_TIEN,
	HOA_DON.STATUS,
	HOA_DON.SO_TIEN_KHACH_TRA, 
	HOA_DON.SO_TIEN_NO_GOI_DAU, 
	CHI_TIET_HOA_DON.MA_SAN_PHAM, 
	SAN_PHAM.TEN_SAN_PHAM,
	CHI_TIET_HOA_DON.SO_LUONG, 
	CHI_TIET_HOA_DON.DON_GIA, 
	CHI_TIET_HOA_DON.PHAN_TRAM_CHIEC_KHAU, 
	CHI_TIET_HOA_DON.MA_KHO_XUAT
FROM 
	HOA_DON
	LEFT JOIN KHACH_HANG ON HOA_DON.MA_KHACH_HANG = KHACH_HANG.MA_KHACH_HANG,
	CHI_TIET_HOA_DON, 
	SAN_PHAM, 
	NGUOI_DUNG,
	NGUOI_DUNG NHAN_VIEN_TT
WHERE
	HOA_DON.ACTIVE = 'A'
	AND CHI_TIET_HOA_DON.ACTIVE = 'A'
	AND HOA_DON.MA_HOA_DON = CHI_TIET_HOA_DON.MA_HOA_DON
	AND CHI_TIET_HOA_DON.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
	AND HOA_DON.MA_NHAN_VIEN_BAN = NGUOI_DUNG.MA_NGUOI_DUNG
	AND HOA_DON.MA_NHAN_VIEN_THU_TIEN = NHAN_VIEN_TT.MA_NGUOI_DUNG

	
CREATE PROCEDURE SP_GET_HOA_DON
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_NHAN_VIEN_BAN_HANG INT, 
@MA_NV_THU_TIEN INT
AS
BEGIN
	SELECT 
		MA_HOA_DON, 
		SO_HOA_DON, 
		MA_KHACH_HANG, 
		TEN_KHACH_HANG, 
		MA_NHAN_VIEN_BAN, 
		TEN_NHAN_VIEN_BAN, 
		NGAY_BAN, 
		NGAY_GIAO, 
		DIA_CHI_GIAO_HANG, 
		MA_NHAN_VIEN_THU_TIEN, 
		TEN_NV_THU_TIEN,
		STATUS, 
		SO_TIEN_KHACH_TRA, 
		SO_TIEN_NO_GOI_DAU,
		ISNULL(SUM(SO_LUONG*(DON_GIA - DON_GIA*PHAN_TRAM_CHIEC_KHAU/100)),0) AS TONG_TIEN
	FROM 
		V_HOA_DON
	WHERE 
		(@FROM_DATE IS NULL OR CAST(NGAY_BAN AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_BAN AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_BAN_HANG = 0 OR MA_NHAN_VIEN_BAN = @MA_NHAN_VIEN_BAN_HANG)
		AND (@MA_NV_THU_TIEN = 0 OR MA_NHAN_VIEN_THU_TIEN = @MA_NV_THU_TIEN)
	GROUP BY 
		MA_HOA_DON, 
		SO_HOA_DON, 
		MA_KHACH_HANG, 
		TEN_KHACH_HANG, 
		MA_NHAN_VIEN_BAN, 
		TEN_NHAN_VIEN_BAN, 
		NGAY_BAN, 
		NGAY_GIAO, 
		DIA_CHI_GIAO_HANG, 
		MA_NHAN_VIEN_THU_TIEN, 
		TEN_NV_THU_TIEN,
		STATUS, 
		SO_TIEN_KHACH_TRA, 
		SO_TIEN_NO_GOI_DAU
END

ALTER PROC SP_GET_TON_KHO_ALERT
@NAME NVARCHAR(200) 
AS
BEGIN
	DECLARE @DYN_SQL VARCHAR(MAX);
	DECLARE @MA_KHO INT;
	DECLARE @MA_SAN_PHAM INT;
	DECLARE @TEN_SAN_PHAM NVARCHAR(100)
	DECLARE @TEN_DON_VI NVARCHAR(100)
	DECLARE @SO_LUONG_TON FLOAT;
	DECLARE @MIN FLOAT;
	DECLARE @COLUMN_NAME VARCHAR (50);
	DECLARE @ID INT;
	DECLARE @SO_LUONG_KHO INT;
	DECLARE @I INT;
	
	DECLARE SAN_PHAM_MY_CURSOR CURSOR FOR
	SELECT MA_SAN_PHAM, TEN_SAN_PHAM, TEN_DON_VI, CO_SO_TOI_THIEU 
	FROM SAN_PHAM, DON_VI_TINH
	WHERE
	SAN_PHAM.ACTIVE = 'A'
	AND DON_VI_TINH.ACTIVE = 'A'
	AND (@NAME IS NULL OR @NAME = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @NAME + '%') 
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI;
	
	
	SET NOCOUNT ON;
	
	CREATE TABLE #TEMP_TON_KHO 
	(
		ID INT IDENTITY(1,1) PRIMARY KEY,  
		MA_SAN_PHAM INT, 
		TEN_SAN_PHAM NVARCHAR(100), 
		TEN_DON_VI NVARCHAR(100)
	)
	
	SET @SO_LUONG_KHO = ISNULL((SELECT COUNT(MA_KHO) FROM KHO WHERE ACTIVE = 'A'),0);
	SET @I = 1;
	WHILE @I <= @SO_LUONG_KHO AND @I <=5
	BEGIN
		SET @COLUMN_NAME = '';
		SET @COLUMN_NAME = 'TON_KHO_' + CAST(@I AS VARCHAR)
		SET @DYN_SQL = 'ALTER TABLE #TEMP_TON_KHO ADD ' + @COLUMN_NAME +' FLOAT DEFAULT 0';
		EXEC(@DYN_SQL);
		SET @I = @I+1;
	END
	
	SET @DYN_SQL = 'ALTER TABLE #TEMP_TON_KHO ADD TOTAL FLOAT DEFAULT 0';
	EXEC(@DYN_SQL)	
	
	OPEN SAN_PHAM_MY_CURSOR 
		FETCH NEXT FROM SAN_PHAM_MY_CURSOR INTO @MA_SAN_PHAM ,@TEN_SAN_PHAM, @TEN_DON_VI, @MIN
		WHILE @@FETCH_STATUS = 0  
	BEGIN
		SET @SO_LUONG_TON = ISNULL(DBO.F_GET_TON_TOTAL(@MA_SAN_PHAM),0);
		IF @SO_LUONG_TON <= @MIN 
		BEGIN
			INSERT INTO #TEMP_TON_KHO(MA_SAN_PHAM, TEN_SAN_PHAM, TEN_DON_VI) VALUES (@MA_SAN_PHAM, @TEN_SAN_PHAM, @TEN_DON_VI);
			SET @ID = (SELECT SCOPE_IDENTITY());
			SET @DYN_SQL = 'UPDATE #TEMP_TON_KHO SET TOTAL  = ' + CAST(@SO_LUONG_TON AS VARCHAR)+ ' WHERE ID = ' + CAST(@ID AS VARCHAR);	
			EXEC(@DYN_SQL);		
			
			SET @I = 1;
			DECLARE KHO_CURSOR_IST CURSOR FOR
			SELECT MA_KHO 
			FROM KHO
			WHERE ACTIVE = 'A'
			ORDER BY MA_KHO; 
		
			OPEN KHO_CURSOR_IST 
			FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
			WHILE @@FETCH_STATUS = 0 AND @I <= 5
			BEGIN
				SET @COLUMN_NAME = '';
				SET @COLUMN_NAME = 'TON_KHO_' + CAST(@I AS VARCHAR);
				SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@MA_KHO, @MA_SAN_PHAM);
				SET @DYN_SQL = 'UPDATE #TEMP_TON_KHO SET ' + @COLUMN_NAME + ' = ' + CAST(@SO_LUONG_TON AS VARCHAR) + ' WHERE ID = ' + CAST(@ID AS VARCHAR);
				EXEC(@DYN_SQL);
				SET @I = @I+1;
				FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
			END;					
			CLOSE KHO_CURSOR_IST;
			DEALLOCATE KHO_CURSOR_IST;
		END;
		FETCH NEXT FROM SAN_PHAM_MY_CURSOR INTO @MA_SAN_PHAM ,@TEN_SAN_PHAM, @TEN_DON_VI, @MIN
	END;
	CLOSE SAN_PHAM_MY_CURSOR
	DEALLOCATE SAN_PHAM_MY_CURSOR
	
	SELECT TOP 999
	#TEMP_TON_KHO.*
	FROM 
	#TEMP_TON_KHO
END
