CREATE TABLE NHOM_SAN_PHAM
(
	MA_NHOM INT IDENTITY(1,1) PRIMARY KEY, 
	TEN_NHOM NVARCHAR(50) NOT NULL,
	GHI_CHU NVARCHAR(1000), 
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)

ALTER TABLE SAN_PHAM
ADD
MA_NHOM INT FOREIGN KEY REFERENCES NHOM_SAN_PHAM(MA_NHOM)

CREATE TABLE SECURITY_QUESTIONS
(
	QUESTION_ID INT IDENTITY(1,1) PRIMARY KEY, 
	QUESTION NVARCHAR(255), 
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)

ALTER TABLE NGUOI_DUNG 
ADD EMAIL VARCHAR(255)

CREATE TABLE PERSONAL_QUESTIONS
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	USR_ID INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	QUESTION_ID INT FOREIGN KEY REFERENCES SECURITY_QUESTIONS(QUESTION_ID), 
	ANSWER NVARCHAR(255),
	ANSWER SALT(255),
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)

CREATE TABLE EXPENSES
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	LOAI_CHI SMALLINT, 
	NGUOI_CHI INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	TEN_NGUOI_NHAN NVARCHAR(255), 
	NGAY_CHI DATE, 
	TONG_CHI FLOAT, 
	GHI_CHU NVARCHAR(255),
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)


CREATE TABLE TON_KHO_MIN_MAX_KHO
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	MA_SAN_PHAM INT FOREIGN KEY REFERENCES SAN_PHAM(MA_SAN_PHAM),
	MA_KHO INT FOREIGN KEY REFERENCES KHO(MA_KHO),
	CO_SO_TOI_THIEU FLOAT, 
	CO_SO_TOI_DA FLOAT, 
	GHI_CHU NVARCHAR(255), 
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)



