CREATE  PROCEDURE SP_GET_HOA_DON_DETAIL_FOR_RETURN
@MA_HOA_DON INT
AS
BEGIN
	SELECT 
		MA_SAN_PHAM, 
		TEN_SAN_PHAM, 
		TEN_DON_VI,
		SO_LUONG, 
		(ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)*ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100)*90/100 DON_GIA, 
		SO_LUONG*(ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)*ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100)*90/100 THANH_TIEN
	FROM 
		V_HOA_DON
	WHERE 
		MA_HOA_DON = MA_HOA_DON
	AND STATUS = 3
END