CREATE PROCEDURE SP_GET_BILL_INFOR
@ID INT
AS
BEGIN
	SELECT 
		HOA_DON.MA_HOA_DON, 
		HOA_DON.SO_HOA_DON, 
		CASE ISNULL(HOA_DON.MA_KHACH_HANG,0) 
		WHEN 0 THEN
			HOA_DON.TEN_KHACH_HANG
		ELSE
			KHACH_HANG.TEN_KHACH_HANG
		END AS TEN_KHACH_HANG,
		HOA_DON.MA_KHACH_HANG,
		HOA_DON.NGAY_BAN,
		HOA_DON.NGAY_GIAO,
		HOA_DON.DIA_CHI_GIAO_HANG, 
		HOA_DON.STATUS
	FROM 
	HOA_DON
	LEFT JOIN KHACH_HANG ON HOA_DON.MA_KHACH_HANG = KHACH_HANG.MA_KHACH_HANG
	WHERE
		HOA_DON.ACTIVE = 'A'
		AND HOA_DON.MA_HOA_DON = @ID
END

CREATE PROCEDURE SP_GET_BILL_DETAIL_BY_ID
@ID INT
AS
BEGIN 
	SELECT 
	CHI_TIET_HOA_DON.MA_SAN_PHAM, 
	SAN_PHAM.TEN_SAN_PHAM,
	CASE ISNULL(CHI_TIET_HOA_DON.MA_DON_VI,0)
	WHEN 0 THEN 
		SAN_PHAM.MA_DON_VI
	ELSE CHI_TIET_HOA_DON.MA_DON_VI
	END AS MA_DON_VI, 
	DON_VI_TINH.TEN_DON_VI, 
	CASE ISNULL(CHI_TIET_HOA_DON.SO_LUONG_TEMP,0) 		
	WHEN 0 THEN 
	ISNULL(CHI_TIET_HOA_DON.SO_LUONG,0)		
	ELSE CHI_TIET_HOA_DON.SO_LUONG_TEMP
	END AS SO_LUONG, 
	CASE ISNULL(CHI_TIET_HOA_DON.DON_GIA_TEMP,0)
	WHEN 0 THEN 
		ISNULL(CHI_TIET_HOA_DON.DON_GIA,0) 
	ELSE 
		CHI_TIET_HOA_DON.DON_GIA_TEMP
	END AS DON_GIA,
	CHI_TIET_HOA_DON.PHAN_TRAM_CHIEC_KHAU, 
	CASE ISNULL(CHI_TIET_HOA_DON.MA_DON_VI,0)
	WHEN 0 THEN
		DBO.F_GET_CONVERTOR(CHI_TIET_HOA_DON.MA_SAN_PHAM, SAN_PHAM.MA_DON_VI)
	ELSE
		DBO.F_GET_CONVERTOR(CHI_TIET_HOA_DON.MA_SAN_PHAM, CHI_TIET_HOA_DON.MA_DON_VI)
	END AS HE_SO,
	CHI_TIET_HOA_DON.MA_KHO_XUAT, 
	KHO.TEN_KHO,
	0 AS DEL_FLG
	FROM 
	CHI_TIET_HOA_DON, 
	SAN_PHAM, 
	DON_VI_TINH, 
	KHO
	WHERE
	CHI_TIET_HOA_DON.ACTIVE = 'A'
	AND CHI_TIET_HOA_DON.MA_HOA_DON = @ID
	AND CHI_TIET_HOA_DON.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
	AND 
		(
			CHI_TIET_HOA_DON.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_HOA_DON.MA_DON_VI IS NOT NULL AND CHI_TIET_HOA_DON.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		)
	AND CHI_TIET_HOA_DON.MA_KHO_XUAT = KHO.MA_KHO
END