CREATE PROCEDURE SP_GET_MIN_MAX_BY_ID
@ID INT
AS
BEGIN
	SELECT 
	TON_KHO_MIN_MAX_KHO.ID,
	TON_KHO_MIN_MAX_KHO.MA_KHO, 
	KHO.TEN_KHO,
	TON_KHO_MIN_MAX_KHO.MA_SAN_PHAM, 
	SAN_PHAM.TEN_SAN_PHAM,
	DON_VI_TINH.TEN_DON_VI,	
	ISNULL(TON_KHO_MIN_MAX_KHO.CO_SO_TOI_THIEU,0) CO_SO_TOI_THIEU,
	ISNULL(TON_KHO_MIN_MAX_KHO.CO_SO_TOI_DA, 0) CO_SO_TOI_DA,
	TON_KHO_MIN_MAX_KHO.GHI_CHU
	FROM 
	TON_KHO_MIN_MAX_KHO, 
	KHO,
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
	TON_KHO_MIN_MAX_KHO.ACTIVE = 'A'
	AND TON_KHO_MIN_MAX_KHO.ID = @ID
	AND TON_KHO_MIN_MAX_KHO.MA_KHO = KHO.MA_KHO
	AND TON_KHO_MIN_MAX_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM 
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
END

EXEC SP_GET_MIN_MAX_BY_ID 1