ALTER PROCEDURE [dbo].[SP_GET_HOA_DON_DETAIL_FOR_RETURN]
@MA_HOA_DON INT
AS
BEGIN
	SELECT 
		MA_SAN_PHAM, 
		TEN_SAN_PHAM, 
		TEN_DON_VI,
		SO_LUONG, 
		SO_LUONG SO_LUONG_BAN,
		(ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)*ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100)*90/100 DON_GIA, 
		SO_LUONG*(ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)*ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100)*90/100 THANH_TIEN
	FROM 
		V_HOA_DON
	WHERE 
		MA_HOA_DON = MA_HOA_DON
	AND STATUS = 3
END

ALTER PROCEDURE SP_GET_LIST_RETURN_TO_PROVIDERS
@PROVIDER_ID INT, 
@PROVIDER_NAME NVARCHAR(100),
@FLAG INT, 
@FROM_DATE DATE, 
@TO_DATE DATE, 
@USER_ID INT, 
@USER_FULL_NAME NVARCHAR(100)
AS
BEGIN
	SELECT 
	TRA_HANG_NCC.ID, 
	TRA_HANG_NCC.MA_PHIEU_TRA, 
	TRA_HANG_NCC.NGAY_LAP_PHIEU, 
	TRA_HANG_NCC.NGUOI_LAP_PHIEU MA_NGUOI_LAP_PHIEU, 
	TRA_HANG_NCC.GHI_CHU, 
	NHA_CUNG_CAP.TEN_NHA_CUNG_CAP, 
	NGUOI_DUNG.TEN_NGUOI_DUNG TEN_NGUOI_LAP_PHIEU
	FROM
	TRA_HANG_NCC, 
	NHA_CUNG_CAP, 
	NGUOI_DUNG
	WHERE 
	TRA_HANG_NCC.ACTIVE = 'A'
	AND (@FLAG = 0 OR (@FLAG = 1 AND MA_PHIEU_TRA IS NOT  NULL) OR (@FLAG = 2 AND MA_PHIEU_TRA IS  NULL))
	AND (@PROVIDER_ID = 0 OR TRA_HANG_NCC.MA_NHA_CUNG_CAP = @PROVIDER_ID)
	AND (@PROVIDER_NAME IS NULL OR @PROVIDER_NAME = '' OR NHA_CUNG_CAP.TEN_NHA_CUNG_CAP LIKE '%' + @PROVIDER_NAME + '%')
	AND (@FROM_DATE IS NULL OR CAST(NGAY_LAP_PHIEU AS DATE) >= CAST(@FROM_DATE AS DATE))
	AND (@TO_DATE IS NULL OR CAST(NGAY_LAP_PHIEU AS DATE) <= CAST(@TO_DATE AS DATE))
	AND (@USER_ID = 0 OR TRA_HANG_NCC.NGUOI_LAP_PHIEU = @USER_ID)
	AND (@USER_FULL_NAME IS NULL OR @USER_FULL_NAME = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @USER_FULL_NAME + '%' )
	AND TRA_HANG_NCC.MA_NHA_CUNG_CAP = NHA_CUNG_CAP.MA_NHA_CUNG_CAP
	AND TRA_HANG_NCC.NGUOI_LAP_PHIEU = NGUOI_DUNG.MA_NGUOI_DUNG
	ORDER BY TRA_HANG_NCC.NGAY_LAP_PHIEU DESC
END

ALTER PROCEDURE [dbo].[SP_GET_RETURN_LIST]
@TEN_KHACH_HANG NVARCHAR(100), 
@FROM_DATE DATE, 
@TO_DATE DATE,
@MA_NHAN_VIEN_NHAN INT, 
@TEN_NHAN_VIEN NVARCHAR(100)
AS
BEGIN
	SELECT 
		TRA_HANG.MA_TRA_HANG, 
		TRA_HANG.TEN_KHACH_HANG, 
		TRA_HANG.NGAY_TRA, 
		TRA_HANG.STATUS,  
		TRA_HANG.NHAN_VIEN_NHAN,
		TRA_HANG.IMPORT_FLG, 
		TRA_HANG.RETURN_FLG,
		NGUOI_DUNG.TEN_NGUOI_DUNG
	FROM
		TRA_HANG, 
		NGUOI_DUNG
	WHERE
		TRA_HANG.ACTIVE = 'A'
		AND TRA_HANG.MA_TRA_HANG IN (SELECT MA_TRA_HANG FROM V_MA_TRA_HANG)
		AND (TRA_HANG.IMPORT_FLG IS NULL OR TRA_HANG.IMPORT_FLG = 'FALSE'
				OR TRA_HANG.RETURN_FLG IS NULL OR TRA_HANG.RETURN_FLG = 'FALSE')
		AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TRA_HANG.TEN_KHACH_HANG LIKE '%' +  @TEN_KHACH_HANG + '%')
		AND (@TEN_NHAN_VIEN IS NULL OR @TEN_NHAN_VIEN = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @TEN_NHAN_VIEN + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_TRA AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_TRA AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAN = 0 OR TRA_HANG.NHAN_VIEN_NHAN = @MA_NHAN_VIEN_NHAN)
		AND TRA_HANG.NHAN_VIEN_NHAN = NGUOI_DUNG.MA_NGUOI_DUNG
		ORDER BY TRA_HANG.NGAY_TRA DESC
END

ALTER TABLE CHI_TIET_NHAP_KHO
ADD 
MA_DON_VI INT,
SO_LUONG_TEMP FLOAT

ALTER TABLE CHI_TIET_NHAP_KHO
ADD 
DON_GIA_TEMP FLOAT

ALTER TABLE CHI_TIET_XUAT_KHO
ADD
MA_DON_VI INT,
SO_LUONG_TEMP FLOAT

ALTER TABLE NHAP_KHO 
ADD
MA_PHIEU_XUAT INT FOREIGN KEY REFERENCES XUAT_KHO(MA_XUAT_KHO)