CREATE VIEW V_TRA_HANG
AS
SELECT 
	TRA_HANG.MA_TRA_HANG, 
	TRA_HANG.MA_KHACH_HANG,
	TRA_HANG.TEN_KHACH_HANG, 
	TRA_HANG.NGAY_TRA, 
	TRA_HANG.NHAN_VIEN_NHAN MA_NGUOI_NHAN,
	SUM(ISNULL(CHI_TIET_TRA_HANG.SO_LUONG_TRA,0)*ISNULL(CHI_TIET_TRA_HANG.GIA_VON,0)) TOTAL
FROM 
TRA_HANG, 
CHI_TIET_TRA_HANG
WHERE
TRA_HANG.ACTIVE = 'A'
AND TRA_HANG.MA_TRA_HANG = CHI_TIET_TRA_HANG.MA_TRA_HANG
GROUP BY 
TRA_HANG.MA_TRA_HANG, 
TRA_HANG.MA_KHACH_HANG,
TRA_HANG.TEN_KHACH_HANG, 
TRA_HANG.NGAY_TRA, 
TRA_HANG.NHAN_VIEN_NHAN


ALTER VIEW V_ALL_CUS_RETURN_BY_MONTH
AS
SELECT
SUM(ISNULL(V_TRA_HANG.TOTAL,0)) TOTAL,
MONTH(V_TRA_HANG.NGAY_TRA) MONTH, 
YEAR(V_TRA_HANG.NGAY_TRA) YEAR 
FROM 
V_TRA_HANG
GROUP BY 
MONTH(V_TRA_HANG.NGAY_TRA), 
YEAR(V_TRA_HANG.NGAY_TRA)  


ALTER VIEW [dbo].[V_BUGET_BY_WEEK]
AS
SELECT 
ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA, 
ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0)  +  ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) TOTAL,
DATEPART(wk, HOA_DON.NGAY_BAN) WEEK, 
YEAR(HOA_DON.NGAY_BAN) YEAR,
DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 0) START_DATE, 
DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 6) END_DATE
FROM 
HOA_DON
WHERE
HOA_DON.ACTIVE = 'A'
GROUP BY 
DATEPART(wk, HOA_DON.NGAY_BAN),
DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 0) ,
DATEADD(wk, DATEDIFF(wk, 0, HOA_DON.NGAY_BAN), 6), 
YEAR(HOA_DON.NGAY_BAN)
GO


CREATE VIEW V_ALL_CUS_RETURN_BY_WEEK
AS
SELECT 
ISNULL(SUM(V_TRA_HANG.TOTAL),0) TOTAL, 
DATEPART(wk, V_TRA_HANG.NGAY_TRA) WEEK, 
YEAR(V_TRA_HANG.NGAY_TRA) YEAR,
DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 0) START_DATE, 
DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 6) END_DATE
FROM 
V_TRA_HANG
GROUP BY 
DATEPART(wk, V_TRA_HANG.NGAY_TRA),
DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 0) ,
DATEADD(wk, DATEDIFF(wk, 0, V_TRA_HANG.NGAY_TRA), 6), 
YEAR(V_TRA_HANG.NGAY_TRA)
GO


CREATE VIEW V_STATISTICS_BY_MONTH
AS
SELECT 
ISNULL(V_BUGET_BY_MONTH.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA, 
ISNULL(V_BUGET_BY_MONTH.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU,
ISNULL(V_BUGET_BY_MONTH.TOTAL,0) BUGET_TOTAL,
ISNULL(V_ALL_CUS_RETURN_BY_MONTH.TOTAL,0) RETURN_TOTAL, 
ISNULL(V_BUGET_BY_MONTH.TOTAL,0) - ISNULL(V_ALL_CUS_RETURN_BY_MONTH.TOTAL,0) TOTAL,
V_BUGET_BY_MONTH.MONTH, 
V_BUGET_BY_MONTH.YEAR
FROM
V_BUGET_BY_MONTH
FULL JOIN V_ALL_CUS_RETURN_BY_MONTH
ON V_BUGET_BY_MONTH.MONTH = V_ALL_CUS_RETURN_BY_MONTH.MONTH
AND V_BUGET_BY_MONTH.YEAR = V_ALL_CUS_RETURN_BY_MONTH.YEAR
WHERE V_BUGET_BY_MONTH.YEAR > (YEAR(GETDATE()) -2)


CREATE VIEW V_STATISTICS_BY_WEEK
AS
SELECT 
ISNULL(V_BUGET_BY_WEEK.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA, 
ISNULL(V_BUGET_BY_WEEK.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU,
ISNULL(V_BUGET_BY_WEEK.TOTAL,0) BUGET_TOTAL,
ISNULL(V_ALL_CUS_RETURN_BY_WEEK.TOTAL,0) RETURN_TOTAL, 
ISNULL(V_BUGET_BY_WEEK.TOTAL,0) - ISNULL(V_ALL_CUS_RETURN_BY_WEEK.TOTAL,0) TOTAL,
V_BUGET_BY_WEEK.WEEK, 
V_BUGET_BY_WEEK.YEAR, 
V_BUGET_BY_WEEK.START_DATE, 
V_BUGET_BY_WEEK.END_DATE
FROM
V_BUGET_BY_WEEK
FULL JOIN V_ALL_CUS_RETURN_BY_WEEK
ON V_BUGET_BY_WEEK.WEEK = V_ALL_CUS_RETURN_BY_WEEK.WEEK
AND V_BUGET_BY_WEEK.YEAR = V_ALL_CUS_RETURN_BY_WEEK.YEAR
WHERE V_BUGET_BY_WEEK.YEAR > (YEAR(GETDATE()) -2)



CREATE PROCEDURE SP_GET_STATISTICS_BY_MONTH
AS
SELECT
 ISNULL(V_STATISTICS_BY_MONTH.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA,
 ISNULL(V_STATISTICS_BY_MONTH.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU,
 ISNULL(V_STATISTICS_BY_MONTH.BUGET_TOTAL,0) BUGET_TOTAL,
 ISNULL(V_STATISTICS_BY_MONTH.RETURN_TOTAL,0) RETURN_TOTAL,
 ISNULL(V_STATISTICS_BY_MONTH.TOTAL,0) TOTAL,
 V_STATISTICS_BY_MONTH.MONTH,
 V_STATISTICS_BY_MONTH.YEAR
FROM 
V_STATISTICS_BY_MONTH
WHERE
V_STATISTICS_BY_MONTH.YEAR = YEAR(GETDATE())


CREATE PROCEDURE SP_GET_STATISTICS_OF_YEAR
AS
SELECT 
ISNULL(SUM(V_STATISTICS_BY_MONTH.SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA, 
ISNULL(SUM(V_STATISTICS_BY_MONTH.SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
ISNULL(SUM(V_STATISTICS_BY_MONTH.BUGET_TOTAL),0) BUGET_TOTAL,
ISNULL(SUM(V_STATISTICS_BY_MONTH.RETURN_TOTAL),0) RETURN_TOTAL,
ISNULL(SUM(V_STATISTICS_BY_MONTH.TOTAL),0) TOTAL
FROM V_STATISTICS_BY_MONTH
WHERE
V_STATISTICS_BY_MONTH.YEAR = YEAR(GETDATE())


CREATE PROCEDURE SP_GET_STATISTICS_BY_WEEK_OF_YEAR
AS
SELECT 
ISNULL(V_BUGET_BY_WEEK.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA, 
ISNULL(V_BUGET_BY_WEEK.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU,
ISNULL(V_BUGET_BY_WEEK.TOTAL,0) BUGET_TOTAL,
ISNULL(V_ALL_CUS_RETURN_BY_WEEK.TOTAL,0) RETURN_TOTAL, 
ISNULL(V_BUGET_BY_WEEK.TOTAL,0) - ISNULL(V_ALL_CUS_RETURN_BY_WEEK.TOTAL,0) TOTAL,
V_BUGET_BY_WEEK.WEEK, 
V_BUGET_BY_WEEK.YEAR, 
V_BUGET_BY_WEEK.START_DATE, 
V_BUGET_BY_WEEK.END_DATE
FROM
V_BUGET_BY_WEEK
FULL JOIN V_ALL_CUS_RETURN_BY_WEEK
ON V_BUGET_BY_WEEK.WEEK = V_ALL_CUS_RETURN_BY_WEEK.WEEK
AND V_BUGET_BY_WEEK.YEAR = V_ALL_CUS_RETURN_BY_WEEK.YEAR
WHERE V_BUGET_BY_WEEK.YEAR = YEAR(GETDATE())


ALTER PROCEDURE SP_REPORT_BY_MONTH
@START_TIME DATE, 
@END_TIME DATE
AS
BEGIN
	SELECT 
	ISNULL(SALES.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA,
	ISNULL(SALES.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU, 
	ISNULL(SALES.TOTAL,0) AS BUGET_TOTAL,  
	ISNULL(RETURN_TABLE.TOTAL,0) AS RETURN_TOTAL,
	ISNULL(SALES.TOTAL,0) - ISNULL(RETURN_TABLE.TOTAL,0) AS TOTAL,
	SALES.MONTH,  
	SALES.YEAR
	FROM
	(
		SELECT 
		ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA, 
		ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
		ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) + ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) TOTAL,
		MONTH(HOA_DON.NGAY_BAN) MONTH, 
		YEAR(HOA_DON.NGAY_BAN) YEAR
		FROM
		HOA_DON
		WHERE 
		ACTIVE = 'A'
		AND (@START_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) >= CAST(@START_TIME AS DATE))
		AND (@END_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) <= CAST(@END_TIME AS DATE))
		GROUP BY 
		MONTH(HOA_DON.NGAY_BAN),
		YEAR(HOA_DON.NGAY_BAN) 
	) SALES FULL JOIN
	(
		SELECT
		SUM(ISNULL(V_TRA_HANG.TOTAL,0)) TOTAL,
		MONTH(V_TRA_HANG.NGAY_TRA) MONTH, 
		YEAR(V_TRA_HANG.NGAY_TRA) YEAR 
		FROM 
		V_TRA_HANG
		WHERE 
		(@START_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) >= CAST(@START_TIME AS DATE))
		AND (@END_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) <= CAST(@END_TIME AS DATE))
		GROUP BY 
		MONTH(V_TRA_HANG.NGAY_TRA), 
		YEAR(V_TRA_HANG.NGAY_TRA) 
	)RETURN_TABLE
	ON SALES.MONTH = RETURN_TABLE.MONTH AND SALES.YEAR = RETURN_TABLE.YEAR	
	ORDER BY SALES.YEAR DESC
END
GO


ALTER PROCEDURE SP_REPORT_BY_DAY
@START_TIME DATE, 
@END_TIME DATE
AS
BEGIN
	SELECT 
	ISNULL(SALES.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA,
	ISNULL(SALES.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU, 
	ISNULL(SALES.TOTAL,0) AS BUGET_TOTAL,  
	ISNULL(RETURN_TABLE.TOTAL,0) AS RETURN_TOTAL,
	ISNULL(SALES.TOTAL,0) - ISNULL(RETURN_TABLE.TOTAL,0) AS TOTAL,
	ISNULL(SALES.NGAY_BAN, RETURN_TABLE.NGAY_TRA) DAY
	FROM
	(
		SELECT 
		ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA, 
		ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
		ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) + ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) TOTAL,
		HOA_DON.NGAY_BAN
		FROM
		HOA_DON
		WHERE 
		ACTIVE = 'A'
		AND (@START_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) >= CAST(@START_TIME AS DATE))
		AND (@END_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) <= CAST(@END_TIME AS DATE))
		GROUP BY 
		MONTH(HOA_DON.NGAY_BAN),
		YEAR(HOA_DON.NGAY_BAN) 
	) SALES FULL JOIN
	(
		SELECT
		SUM(ISNULL(V_TRA_HANG.TOTAL,0)) TOTAL,
		V_TRA_HANG.NGAY_TRA
		FROM 
		V_TRA_HANG
		WHERE 
		(@START_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) >= CAST(@START_TIME AS DATE))
		AND (@END_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) <= CAST(@END_TIME AS DATE))
		GROUP BY 
		MONTH(V_TRA_HANG.NGAY_TRA), 
		YEAR(V_TRA_HANG.NGAY_TRA) 
	)RETURN_TABLE
	ON SALES.MONTH = RETURN_TABLE.MONTH AND SALES.YEAR = RETURN_TABLE.YEAR	
	ORDER BY SALES.YEAR DESC
END
GO



