ALTER VIEW [dbo].[V_REPORT_TOTAL]
AS
SELECT 
ISNULL(SALES.SO_TIEN_KHACH_TRA,0) SO_TIEN_KHACH_TRA,
ISNULL(SALES.SO_TIEN_NO_GOI_DAU,0) SO_TIEN_NO_GOI_DAU, 
ISNULL(SALES.TOTAL,0) AS BUGET_TOTAL,  
ISNULL(RETURN_TABLE.TOTAL,0) AS RETURN_TOTAL,
ISNULL(EXPENSES.TONG_CHI,0) TONG_CHI,
ISNULL(NHAP_KHO.TONG_NHAP,0) TONG_NHAP,
ISNULL(KHACH_HANG_DEBIT_HIST.TONG_PHAT_SINH,0) TONG_THU_NO,
ISNULL(SALES.SO_TIEN_KHACH_TRA,0) - ISNULL(RETURN_TABLE.TOTAL,0) +  ISNULL(KHACH_HANG_DEBIT_HIST.TONG_PHAT_SINH,0) - ISNULL(EXPENSES.TONG_CHI,0) - ISNULL(NHAP_KHO.TONG_NHAP,0) AS TOTAL,
ISNULL(ISNULL(ISNULL(ISNULL(SALES.NGAY_BAN,RETURN_TABLE.NGAY_TRA),EXPENSES.NGAY_CHI),NHAP_KHO.NGAY_NHAP),KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH) DAY
FROM
(
	SELECT 
	ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA, 
	ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
	ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) + ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) TOTAL,
	HOA_DON.NGAY_BAN
	FROM
	HOA_DON
	WHERE 
	ACTIVE = 'A'
	--AND (@START_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) >= CAST(@START_TIME AS DATE))
	--AND (@END_TIME IS NULL OR CAST(HOA_DON.NGAY_BAN AS DATE) <= CAST(@END_TIME AS DATE))
	GROUP BY 
	HOA_DON.NGAY_BAN
) SALES FULL JOIN
(
	SELECT
	SUM(ISNULL(V_TRA_HANG.TOTAL,0)) TOTAL,
	V_TRA_HANG.NGAY_TRA
	FROM 
	V_TRA_HANG
	--WHERE 
	--(@START_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) >= CAST(@START_TIME AS DATE))
	--AND (@END_TIME IS NULL OR CAST(V_TRA_HANG.NGAY_TRA AS DATE) <= CAST(@END_TIME AS DATE))
	GROUP BY 
	V_TRA_HANG.NGAY_TRA
)RETURN_TABLE ON SALES.NGAY_BAN = RETURN_TABLE.NGAY_TRA
FULL JOIN 
(
	SELECT 
		EXPENSES.NGAY_CHI, 
		ISNULL(SUM(EXPENSES.TONG_CHI),0) TONG_CHI
	FROM
	EXPENSES
	WHERE ACTIVE = 'A'
	--AND (@START_TIME IS NULL OR CAST(EXPENSES.NGAY_CHI AS DATE) >= CAST(@START_TIME AS DATE))
	--AND (@END_TIME IS NULL OR CAST(EXPENSES.NGAY_CHI AS DATE) <= CAST(@END_TIME AS DATE))
	GROUP BY EXPENSES.NGAY_CHI
)EXPENSES ON SALES.NGAY_BAN = EXPENSES.NGAY_CHI
FULL JOIN 
(
	SELECT 
	NHAP_KHO.NGAY_NHAP, 
	ISNULL(SUM(ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG,0)* ISNULL(CHI_TIET_NHAP_KHO.GIA_VON,0)),0) TONG_NHAP
	FROM
	NHAP_KHO, 
	CHI_TIET_NHAP_KHO
	WHERE
	NHAP_KHO.ACTIVE = 'A'
	AND CHI_TIET_NHAP_KHO.ACTIVE = 'A'
	AND NHAP_KHO.LY_DO_NHAP = 0 
	AND NHAP_KHO.MA_NHAP_KHO = CHI_TIET_NHAP_KHO.MA_NHAP_KHO
	AND NHAP_KHO.NGAY_NHAP IS NOT NULL
	--AND (@START_TIME IS NULL OR CAST(NHAP_KHO.NGAY_NHAP AS DATE) >= CAST(@START_TIME AS DATE))
	--AND (@END_TIME IS NULL OR CAST(NHAP_KHO.NGAY_NHAP AS DATE) <= CAST(@END_TIME AS DATE))
	GROUP BY NHAP_KHO.NGAY_NHAP
)NHAP_KHO ON SALES.NGAY_BAN = NHAP_KHO.NGAY_NHAP
FULL JOIN 
(
	SELECT 
	KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH, 
	ISNULL(SUM(KHACH_HANG_DEBIT_HIST.PHAT_SINH),0) TONG_PHAT_SINH
	FROM
	KHACH_HANG_DEBIT_HIST
	WHERE
	ACTIVE = 'A'
	AND PHAT_SINH > 0
	GROUP BY KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH
)KHACH_HANG_DEBIT_HIST ON SALES.NGAY_BAN = KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH 




ALTER PROCEDURE [dbo].[SP_REPORT_BY_DAY_ALL]
@START_TIME DATE, 
@END_TIME DATE
AS
BEGIN	
	SELECT * FROM V_REPORT_TOTAL
	WHERE
	(@START_TIME IS NULL OR CAST(V_REPORT_TOTAL.DAY AS DATE) >= CAST(@START_TIME AS DATE))
	AND (@END_TIME IS NULL OR CAST(V_REPORT_TOTAL.DAY AS DATE) <= CAST(@END_TIME AS DATE))
	ORDER BY DAY DESC
END

