ALTER PROC GET_KHACH_HANG_ALERT
@NAME NVARCHAR(100)
AS
BEGIN
	CREATE TABLE #LocalTempTable(
	KIND INT,
	MAX_DEBIT FLOAT, 
	MAX_MONTH INT,
	KIND_NAME NVARCHAR(100))

	CREATE TABLE #TEMP
	(
		MA_KHACH_HANG INT, 
		TEN_KHACH_HANG NVARCHAR(200),
		MA_THE_KHACH_HANG VARCHAR(50), 
		DIA_CHI NVARCHAR(200), 
		SO_DIEN_THOAI VARCHAR(50), 
		EMAIL VARCHAR(50), 
		MA_KHU_VUC INT, 
		DOANH_SO FLOAT, 
		NO_GOI_DAU FLOAT, 
		NGAY_PHAT_SINH_NO DATE, 
		KIND INT,
		TEN_KHU_VUC NVARCHAR(100), 
		KIND_NAME NVARCHAR(200)
	)
	DECLARE  @MAX_DEBIT FLOAT
	DECLARE  @MAX_MONTH INT

	SET @MAX_DEBIT = (SELECT TOP 1 CAST(VALUE AS FLOAT) AS INT
	FROM SMS_MASTER
	WHERE 
	ACTIVE = 'A'
	AND NAME = 'MAX_DEBIT_KIND_1')

	SET  @MAX_MONTH = (SELECT TOP 1 CAST(VALUE AS FLOAT) AS INT
	FROM SMS_MASTER
	WHERE 
	ACTIVE = 'A'
	AND NAME = 'MAX_MOUNTH_KIND_1')


	INSERT INTO #LocalTempTable
	VALUES (1, @MAX_DEBIT, @MAX_MONTH, N'Khách hàng công ty, công trình')

	SET @MAX_DEBIT = (SELECT TOP 1 CAST(VALUE AS FLOAT) AS INT
	FROM SMS_MASTER
	WHERE 
	ACTIVE = 'A'
	AND NAME = 'MAX_DEBIT_KIND_2')

	SET  @MAX_MONTH = (SELECT TOP 1 CAST(VALUE AS FLOAT) AS INT
	FROM SMS_MASTER
	WHERE 
	ACTIVE = 'A'
	AND NAME = 'MAX_MOUNTH_KIND_2')

	INSERT INTO #LocalTempTable
	VALUES (2, @MAX_DEBIT, @MAX_MONTH , N'Khách hàng thân thiết')

	SET @MAX_DEBIT = (SELECT TOP 1 CAST(VALUE AS FLOAT) AS INT
	FROM SMS_MASTER
	WHERE 
	ACTIVE = 'A'
	AND NAME = 'MAX_DEBIT_KIND_3')

	SET  @MAX_MONTH = (SELECT TOP 1 CAST(VALUE AS FLOAT) AS INT
	FROM SMS_MASTER
	WHERE 
	ACTIVE = 'A'
	AND NAME = 'MAX_MOUNTH_KIND_3')

	INSERT INTO #LocalTempTable
	VALUES (3, @MAX_DEBIT, @MAX_MONTH , N'Khách hàng thường')
	
	INSERT INTO #TEMP
	SELECT * FROM
	(
		SELECT 
		KHACH_HANG.MA_KHACH_HANG, 
		KHACH_HANG.TEN_KHACH_HANG, 
		KHACH_HANG.MA_THE_KHACH_HANG, 
		KHACH_HANG.DIA_CHI, 
		KHACH_HANG.SO_DIEN_THOAI, 
		KHACH_HANG.EMAIL, 
		KHACH_HANG.MA_KHU_VUC, 
		KHACH_HANG.DOANH_SO, 
		KHACH_HANG.NO_GOI_DAU, 
		KHACH_HANG.NGAY_PHAT_SINH_NO, 
		KHACH_HANG.KIND,
		KHU_VUC.TEN_KHU_VUC, 
		#LocalTempTable.KIND_NAME KIND_NAME
		FROM 
		KHACH_HANG,
		KHU_VUC, 
		#LocalTempTable
		WHERE 
		KHACH_HANG.ACTIVE = 'A'
		AND (@NAME IS NULL OR @NAME = '' OR  KHACH_HANG.TEN_KHACH_HANG LIKE '%' + @NAME + '%')
		AND (KHACH_HANG.NO_GOI_DAU >= #LocalTempTable.MAX_DEBIT 
		OR KHACH_HANG.NGAY_PHAT_SINH_NO <= DATEADD( MONTH, (-1*#LocalTempTable.MAX_MONTH), GETDATE()))
		AND KHACH_HANG.KIND = #LocalTempTable.KIND
		AND KHACH_HANG.MA_KHU_VUC = KHU_VUC.MA_KHU_VUC		
	)TAB
	
	SELECT * FROM #TEMP
END

EXEC GET_KHACH_HANG_ALERT ''

