ALTER TABLE KHO
ADD
MA_NGUOI_DUNG_DAU INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG)

ALTER TABLE CHI_TIET_HOA_DON
ADD
MA_KHO_XUAT INT FOREIGN KEY REFERENCES KHO(MA_KHO)


ALTER TABLE KHACH_HANG
ADD
NGAY_PHAT_SINH_NO DATE 