CREATE PROCEDURE SP_IMPORT_REPORTER
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		SUM(V_NHAP_KHO.SO_LUONG) SO_LUONG, 
		V_NHAP_KHO.GIA_VON, 
		SUM(V_NHAP_KHO.SO_LUONG)*GIA_VON VALUE 
	FROM
	V_NHAP_KHO, 
	SAN_PHAM
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_NHAP_KHO.LY_DO_NHAP = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP <= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP >= @TO_DATE)
		AND V_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
	GROUP BY 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_NHAP_KHO.GIA_VON
END 


ALTER PROCEDURE SP_IMPORT_REPORTER_DETAIL
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT
		V_NHAP_KHO.NGAY_NHAP, 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI, 
		SUM(V_NHAP_KHO.SO_LUONG) SO_LUONG, 
		V_NHAP_KHO.GIA_VON, 
		SUM(V_NHAP_KHO.SO_LUONG)*GIA_VON VALUE 
	FROM
	V_NHAP_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_NHAP_KHO.LY_DO_NHAP = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_NHAP_KHO.GIA_VON, 
		V_NHAP_KHO.NGAY_NHAP, 
		DON_VI_TINH.TEN_DON_VI
	ORDER BY V_NHAP_KHO.NGAY_NHAP
END 

CREATE FUNCTION F_IMPORT_REPORTER_SUM
(
	@KIND INT, 
	@MA_KHO INT,
	@MA_SAN_PHAM INT, 
	@TEN_SAN_PHAM NVARCHAR(200),
	@FROM_DATE DATE, 
	@TO_DATE DATE
)
RETURNS FLOAT
BEGIN
	RETURN
	(
		SELECT
		ISNULL(SUM(VALUE),0) VALUE
		FROM
		(
			SELECT
				SUM(V_NHAP_KHO.SO_LUONG)*GIA_VON VALUE 
			FROM
			V_NHAP_KHO, 
			SAN_PHAM
			WHERE 
				(@KIND IS NULL OR @KIND = -1 OR V_NHAP_KHO.LY_DO_NHAP = @KIND)
				AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_KHO.MA_KHO = @MA_KHO)
				AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
				AND (@FROM_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP >= @FROM_DATE)
				AND (@TO_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP <= @TO_DATE)
				AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
				AND V_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
			GROUP BY 
				V_NHAP_KHO.MA_SAN_PHAM, 
				SAN_PHAM.TEN_SAN_PHAM, 
				V_NHAP_KHO.GIA_VON, 
				V_NHAP_KHO.NGAY_NHAP
		)TEMP
	)
END 

ALTER PROCEDURE SP_IMPORT_REPORTER_SUM
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
		SELECT
		ISNULL(SUM(VALUE),0) VALUE
		FROM
		(
			SELECT
				SUM(V_NHAP_KHO.SO_LUONG)*GIA_VON VALUE 
			FROM
			V_NHAP_KHO, 
			SAN_PHAM
			WHERE 
				(@KIND IS NULL OR @KIND = -1 OR V_NHAP_KHO.LY_DO_NHAP = @KIND)
				AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_KHO.MA_KHO = @MA_KHO)
				AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
				AND (@FROM_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP >= @FROM_DATE)
				AND (@TO_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP <= @TO_DATE)
				AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
				AND V_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
			GROUP BY 
				V_NHAP_KHO.MA_SAN_PHAM, 
				SAN_PHAM.TEN_SAN_PHAM, 
				V_NHAP_KHO.GIA_VON, 
				V_NHAP_KHO.NGAY_NHAP
		)TEMP
END 