ALTER PROCEDURE [dbo].[SP_GET_HOA_DON_INFO]
@MA_HOA_DON INT
AS
BEGIN
	SELECT 
		HOA_DON.MA_HOA_DON, 
		HOA_DON.SO_HOA_DON, 
		HOA_DON.MA_KHACH_HANG, 
		CASE WHEN HOA_DON.MA_KHACH_HANG IS NULL
				THEN HOA_DON.TEN_KHACH_HANG
			ELSE
				KHACH_HANG.TEN_KHACH_HANG 
		END AS TEN_KHACH_HANG,
		HOA_DON.MA_NHAN_VIEN_BAN, 
		NV_BAN.TEN_NGUOI_DUNG AS TEN_NGUOI_BAN,
		HOA_DON.NGAY_BAN, 
		HOA_DON.NGAY_GIAO,
		HOA_DON.DIA_CHI_GIAO_HANG,
		HOA_DON.STATUS, 
		HOA_DON.SO_TIEN_KHACH_TRA, 
		HOA_DON.SO_TIEN_NO_GOI_DAU, 
		HOA_DON.MA_NHAN_VIEN_THU_TIEN, 
		NV_TT.TEN_NGUOI_DUNG TEN_NV_TT, 
		ISNULL(SUM(CHI_TIET_HOA_DON.SO_LUONG*CHI_TIET_HOA_DON.DON_GIA), 0) TONG_TIEN, 
		ISNULL(SUM(CHI_TIET_HOA_DON.SO_LUONG*CHI_TIET_HOA_DON.DON_GIA*PHAN_TRAM_CHIEC_KHAU/100), 0) CHIEC_KHAU
	FROM 
		HOA_DON
		JOIN CHI_TIET_HOA_DON ON HOA_DON.MA_HOA_DON =  CHI_TIET_HOA_DON.MA_HOA_DON
		LEFT JOIN KHACH_HANG ON HOA_DON.MA_KHACH_HANG = KHACH_HANG.MA_KHACH_HANG
		JOIN NGUOI_DUNG NV_BAN ON HOA_DON.MA_NHAN_VIEN_BAN = NV_BAN.MA_NGUOI_DUNG
		LEFT JOIN NGUOI_DUNG NV_TT ON HOA_DON.MA_NHAN_VIEN_THU_TIEN = NV_TT.MA_NGUOI_DUNG
	WHERE
		HOA_DON.MA_HOA_DON = @MA_HOA_DON
		AND HOA_DON.ACTIVE = 'A'
	GROUP BY 	
	HOA_DON.MA_HOA_DON, 
	HOA_DON.SO_HOA_DON, 
	HOA_DON.MA_KHACH_HANG, 
	CASE WHEN HOA_DON.MA_KHACH_HANG IS NULL
			THEN HOA_DON.TEN_KHACH_HANG
		ELSE
			KHACH_HANG.TEN_KHACH_HANG 
	END,
	HOA_DON.MA_NHAN_VIEN_BAN, 
	NV_BAN.TEN_NGUOI_DUNG,
	HOA_DON.NGAY_BAN, 
	HOA_DON.NGAY_GIAO,
	HOA_DON.DIA_CHI_GIAO_HANG,
	HOA_DON.STATUS, 
	HOA_DON.SO_TIEN_KHACH_TRA, 
	HOA_DON.SO_TIEN_NO_GOI_DAU, 
	HOA_DON.MA_NHAN_VIEN_THU_TIEN, 
	NV_TT.TEN_NGUOI_DUNG
END