ALTER TABLE SMS_MASTER
ALTER COLUMN VALUE NVARCHAR(1000);


ALTER TABLE KHACH_HANG
ALTER COLUMN SO_DIEN_THOAI VARCHAR(100);


CREATE PROC SP_GET_EXPORT_DETAIL_BY_ID
@ID INT
AS
BEGIN
	SELECT
	XUAT_KHO.MA_HOA_DON, 
	XUAT_KHO.LY_DO_XUAT, 
	XUAT_KHO.MA_KHO_NHAN,
	KHO_XUAT.TEN_KHO TEN_KHO_XUAT, 
	XUAT_KHO.MA_KHO_XUAT, 
	KHO_NHAP.TEN_KHO TEN_KHO_NHAP, 
	CHI_TIET_XUAT_KHO.MA_SAN_PHAM, 
	SAN_PHAM.TEN_SAN_PHAM,
	CASE ISNULL(CHI_TIET_XUAT_KHO.MA_DON_VI,0)
	WHEN 0 THEN 
		SAN_PHAM.MA_DON_VI
	ELSE CHI_TIET_XUAT_KHO.MA_DON_VI
	END AS MA_DON_VI, 
	DON_VI_TINH.TEN_DON_VI, 
	CASE ISNULL(CHI_TIET_XUAT_KHO.SO_LUONG_TEMP,0) 		
	WHEN 0 THEN 
	ISNULL(CHI_TIET_XUAT_KHO.SO_LUONG,0)		
	ELSE CHI_TIET_XUAT_KHO.SO_LUONG_TEMP
	END AS SO_LUONG, 
	CASE ISNULL(CHI_TIET_XUAT_KHO.DON_GIA_TEMP,0)
	WHEN 0 THEN 
		ISNULL(CHI_TIET_XUAT_KHO.GIA_VON,0)
	ELSE 
		CHI_TIET_XUAT_KHO.DON_GIA_TEMP 
	END AS DON_GIA
	FROM 
	XUAT_KHO 
	LEFT JOIN KHO KHO_NHAP ON XUAT_KHO.MA_KHO_NHAN = KHO_NHAP.MA_KHO,
	CHI_TIET_XUAT_KHO,
	SAN_PHAM, 
	DON_VI_TINH, 
	KHO KHO_XUAT	
	WHERE
	XUAT_KHO.MA_XUAT_KHO = @ID
	AND XUAT_KHO.MA_XUAT_KHO = CHI_TIET_XUAT_KHO.MA_XUAT_KHO
	AND CHI_TIET_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
	AND DON_VI_TINH.MA_DON_VI = 
		CASE ISNULL(CHI_TIET_XUAT_KHO.MA_DON_VI,0)
		WHEN 0 THEN 
			 SAN_PHAM.MA_DON_VI
		ELSE CHI_TIET_XUAT_KHO.MA_DON_VI END
	AND XUAT_KHO.MA_KHO_XUAT = KHO_XUAT.MA_KHO
END
