CREATE PROCEDURE SP_GET_HOA_DON_CAN_XUAT_KHO
@MA_KHO INT, 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT DISTINCT
		MA_HOA_DON, 
		SO_HOA_DON, 
		MA_KHACH_HANG, 
		TEN_KHACH_HANG, 
		MA_NHAN_VIEN_BAN,
		TEN_NHAN_VIEN_BAN, 
		NGAY_BAN, 
		NGAY_GIAO, 
		DIA_CHI_GIAO_HANG
	FROM 
		V_HOA_DON
	WHERE
		STATUS = 2
		AND (@MA_KHO = 0 OR MA_KHO_XUAT = @MA_KHO)
		AND (@FROM_DATE IS NULL OR CAST(NGAY_BAN AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_BAN AS DATE) <= CAST(@TO_DATE AS DATE)) 
END


CREATE PROCEDURE SP_GET_HD_DETAIL_FOR_EXPORT
@MA_KHO INT, 
@MA_HOA_DON INT
AS 
BEGIN
	SELECT 
		MA_SAN_PHAM, 
		TEN_SAN_PHAM, 
		SO_LUONG, 
		TEN_DON_VI
	FROM 
		V_HOA_DON
	WHERE 
		MA_HOA_DON = @MA_HOA_DON
		AND MA_KHO_XUAT = @MA_KHO
END

===============
ALTER FUNCTION F_CHECK_REMAIN
@MA_HOA_DON INT
RETURNS BIT
AS
BEGIN
	DECLARE  @COUNT_IN_BILL INT;
	DECLARE  @COUNT_IN_EXPORT INT;
	
	SELECT 
		@COUNT_IN_BILL = COUNT(MA_KHO_XUAT)
	FROM 
		CHI_TIET_HOA_DON
	WHERE
	MA_HOA_DON = @MA_HOA_DON;
	
	SELECT 
		@COUNT_IN_EXPORT = COUNT(MA_KHO_XUAT)
	FROM
		XUAT_KHO
	WHERE
		MA_HOA_DON = @MA_HOA_DON;
		
	IF @COUNT_IN_BILL = @COUNT_IN_EXPORT
	BEGIN
		RETURN 'FALSE';
	END
	ELSE
	BEGIN
		RETURN 'TRUE';
	END
END

CREATE PROCEDURE SP_SALE_EXPORT
@MA_KHO INT, 
@MA_HOA_DON INT, 
@MA_NHAN_VIEN_THUC_HIEN INT, 
@TEN_KHACH_HANG NVARCHAR(100),
@RETURN_VALUE INT OUTPUT
AS
BEGIN 
	DECLARE  @SO_LUONG_TON FLOAT;
	DECLARE  @MA_SAN_PHAM INT;
	DECLARE  @LASTEST BIT;
	DECLARE  @DON_GIA FLOAT;
	DECLARE  @SO_LUONG FLOAT;
	DECLARE  @MA_XUAT_KHO INT;
	DECLARE  @FLG BIT;
	DECLARE  @CHECKED_FLG BIT;
	
	DECLARE CHI_TIEC_HOA_DON_CURSOR CURSOR FOR
	SELECT 
	MA_SAN_PHAM, 
	SO_LUONG, 
	DON_GIA - DON_GIA*PHAN_TRAM_CHIEC_KHAU/100
	FROM
	CHI_TIET_HOA_DON
	WHERE
	ACTIVE = 'A'
	AND MA_HOA_DON = @MA_HOA_DON
	AND MA_KHO_XUAT = @MA_KHO
	SET @FLG = 'TRUE';
	
	OPEN CHI_TIEC_HOA_DON_CURSOR
	FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@MA_KHO, @MA_SAN_PHAM);
		IF @SO_LUONG_TON IS NULL OR @SO_LUONG_TON = 0 OR @SO_LUONG_TON < @SO_LUONG
		BEGIN
			SET @FLG = 'FALSE'
			BREAK;
		END
		FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA
	END;
		
	CLOSE CHI_TIEC_HOA_DON_CURSOR;
	DEALLOCATE CHI_TIEC_HOA_DON_CURSOR;
	
	IF @FLG = 'FALSE'
	BEGIN
		SET @RETURN_VALUE = 0;
	END
	ELSE
	BEGIN
		DECLARE CHI_TIEC_HOA_DON_CURSOR_EXPORT CURSOR FOR
		SELECT 
		MA_SAN_PHAM, 
		SO_LUONG, 
		DON_GIA - DON_GIA*PHAN_TRAM_CHIEC_KHAU/100
		FROM
		CHI_TIET_HOA_DON
		WHERE
		ACTIVE = 'A'
		AND MA_HOA_DON = @MA_HOA_DON
		AND MA_KHO_XUAT = @MA_KHO
		
		
		
		INSERT INTO 
		XUAT_KHO 
		(	
			MA_HOA_DON, 
			LY_DO_XUAT,  --0
			MA_KHO_XUAT,
			NGAY_XUAT, 
			MA_NHAN_VIEN_XUAT, 
			TEN_NGUOI_NHAN_HANG, 
			CREATE_BY, 
			UPDATE_BY, 
			CREATE_AT, 
			UPDATE_AT, 
			ACTIVE
		)
		VALUES
		(
			@MA_HOA_DON, 
			0, 
			@MA_KHO, 
			GETDATE(), 
			@MA_NHAN_VIEN_THUC_HIEN, 
			@TEN_KHACH_HANG, 
			@MA_NHAN_VIEN_THUC_HIEN, 
			@MA_NHAN_VIEN_THUC_HIEN, 
			GETDATE(), 
			GETDATE(),
			'A'
		)
		SET @MA_XUAT_KHO = (SELECT SCOPE_IDENTITY());
		
		SET @CHECKED_FLG = DBO.F_CHECK_REMAIN(@MA_HOA_DON)
		
		IF @CHECKED_FLG = 'FALSE'
		BEGIN
			UPDATE HOA_DON
			SET
			STATUS = 3, 
			UPDATE_BY = @MA_NHAN_VIEN_THUC_HIEN, 
			UPDATE_AT = GETDATE()
			WHERE 
			MA_HOA_DON = @MA_HOA_DON
		END
		
		OPEN CHI_TIEC_HOA_DON_CURSOR_EXPORT
		FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR_EXPORT INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA
		WHILE @@FETCH_STATUS = 0 
		BEGIN
			
			INSERT INTO
			CHI_TIET_XUAT_KHO
			(
				MA_XUAT_KHO, 
				MA_SAN_PHAM, 
				SO_LUONG, 
				GIA_XUAT, 
				CREATE_BY, 
				UPDATE_BY, 
				CREATE_AT, 
				UPDATE_AT, 
				ACTIVE
			)
			VALUES
			(
				@MA_XUAT_KHO, 
				@MA_SAN_PHAM, 
				@SO_LUONG, 
				@DON_GIA, 
				@MA_NHAN_VIEN_THUC_HIEN, 
				@MA_NHAN_VIEN_THUC_HIEN,
				GETDATE(), 
				GETDATE(), 
				'A'
			)
			FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR_EXPORT INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA
		END;
	
	END
END