CREATE PROCEDURE SP_GET_HOA_DON_CAN_XUAT_KHO
@MA_KHO INT, 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT DISTINCT
		MA_HOA_DON, 
		SO_HOA_DON, 
		MA_KHACH_HANG, 
		TEN_KHACH_HANG, 
		MA_NHAN_VIEN_BAN,
		TEN_NHAN_VIEN_BAN, 
		NGAY_BAN, 
		NGAY_GIAO, 
		DIA_CHI_GIAO_HANG
	FROM 
		V_HOA_DON
	WHERE
		STATUS = 2
		AND (@MA_KHO = 0 OR MA_KHO_XUAT = @MA_KHO)
		AND (@FROM_DATE IS NULL OR CAST(NGAY_BAN AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_BAN AS DATE) <= CAST(@TO_DATE AS DATE)) 
END


CREATE PROCEDURE SP_GET_HD_DETAIL_FOR_EXPORT
@MA_KHO INT, 
@MA_HOA_DON INT
AS 
BEGIN
	SELECT 
		MA_SAN_PHAM, 
		TEN_SAN_PHAM, 
		SO_LUONG, 
		TEN_DON_VI
	FROM 
		V_HOA_DON
	WHERE 
		MA_HOA_DON = @MA_HOA_DON
		AND MA_KHO_XUAT = @MA_KHO
END

CREATE FUNCTION F_CHECK_REMAIN
@MA_HOA_DON INT
RETURNS BIT
AS
BEGIN
	DECLARE  @COUNT_IN_BILL INT;
	DECLARE  @COUNT_IN_EXPORT INT;
	
	SELECT 
		@COUNT_IN_BILL = COUNT(MA_KHO_XUAT)
	FROM 
		CHI_TIET_HOA_DON
	WHERE
	MA_HOA_DON = @MA_HOA_DON;
	
	SELECT 
		@COUNT_IN_EXPORT = COUNT(MA_KHO_XUAT)
	FROM
		XUAT_KHO
	WHERE
		MA_HOA_DON = @MA_HOA_DON;
		
	IF @COUNT_IN_BILL = @COUNT_IN_EXPORT
	BEGIN
		RETURN 'TRUE';
	END
	ELSE
	BEGIN
		RETURN 'FALSE';
	END
END

CREATE PROCEDURE SP_SALE_EXPORT
@MA_KHO INT, 
@MA_HOA_DON INT
AS
BEGIN 
END