
ALTER PROCEDURE [dbo].[SP_SALE_EXPORT]
@MA_KHO INT, 
@MA_HOA_DON INT, 
@MA_NHAN_VIEN_THUC_HIEN INT, 
@TEN_KHACH_HANG NVARCHAR(100),
@RETURN_VALUE INT OUTPUT
AS
BEGIN 
	DECLARE  @SO_LUONG_TON FLOAT;
	DECLARE  @MA_SAN_PHAM INT;
	DECLARE  @LASTEST BIT;
	DECLARE  @DON_GIA FLOAT;
	DECLARE  @SO_LUONG FLOAT;
	DECLARE  @DON_GIA_TEMP FLOAT;
	DECLARE  @SO_LUONG_TEMP FLOAT;
	DECLARE  @MA_DON_VI INT;
	DECLARE  @MA_XUAT_KHO INT;
	DECLARE  @FLG BIT;
	DECLARE  @CHECKED_FLG BIT;
	DECLARE  @STAUTS INT;
	DECLARE  @STORE_ID INT;
	DECLARE  @NEXT_STORE_ID INT;	
	
	SELECT 
	@STAUTS = (DBO.F_SUM_QUANTITY_BY_BILL_ID(MA_HOA_DON) - DBO.F_SUM_EXPORTED_BY_BILL_ID(MA_HOA_DON))
	FROM 
	HOA_DON
	WHERE
	MA_HOA_DON = @MA_HOA_DON AND ACTIVE = 'A'
	
	IF @STAUTS <= 0 
		SET @RETURN_VALUE = -1 
	ELSE
	BEGIN
		IF @MA_KHO <> 0
		BEGIN 
			DECLARE CHI_TIEC_HOA_DON_CURSOR CURSOR FOR
			SELECT 
			MA_SAN_PHAM, 
			SO_LUONG, 
			ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)* ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100
			FROM
			CHI_TIET_HOA_DON
			WHERE
			ACTIVE = 'A'
			AND MA_HOA_DON = @MA_HOA_DON
			AND MA_KHO_XUAT = @MA_KHO
			SET @FLG = 'TRUE';
			
			OPEN CHI_TIEC_HOA_DON_CURSOR
			FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR 
				INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA		
			WHILE @@FETCH_STATUS = 0 
			BEGIN
				SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@MA_KHO, @MA_SAN_PHAM);
				IF @SO_LUONG_TON IS NULL OR @SO_LUONG_TON = 0 OR @SO_LUONG_TON < @SO_LUONG
				BEGIN
					SET @FLG = 'FALSE'
					BREAK;
				END
				FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR 
					INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA
			END;
				
			CLOSE CHI_TIEC_HOA_DON_CURSOR;
			DEALLOCATE CHI_TIEC_HOA_DON_CURSOR;
			
			IF @FLG = 'FALSE'
			BEGIN
				SET @RETURN_VALUE = 0;
			END
			ELSE
			BEGIN
				DECLARE CHI_TIEC_HOA_DON_CURSOR_EXPORT CURSOR FOR
				SELECT 
				MA_SAN_PHAM, 
				SO_LUONG, 
				ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)*ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100, 
				ISNULL(DON_GIA_TEMP,0) - ISNULL(DON_GIA_TEMP,0)*ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100,
				SO_LUONG_TEMP, 
				MA_DON_VI
				FROM
				CHI_TIET_HOA_DON
				WHERE
				ACTIVE = 'A'
				AND MA_HOA_DON = @MA_HOA_DON
				AND MA_KHO_XUAT = @MA_KHO
				
				
				
				INSERT INTO 
				XUAT_KHO 
				(	
					MA_HOA_DON, 
					LY_DO_XUAT,  --0
					MA_KHO_XUAT,
					NGAY_XUAT, 
					MA_NHAN_VIEN_XUAT, 
					TEN_NGUOI_NHAN_HANG, 
					CREATE_BY, 
					UPDATE_BY, 
					CREATE_AT, 
					UPDATE_AT, 
					ACTIVE
				)
				VALUES
				(
					@MA_HOA_DON, 
					0, 
					@MA_KHO, 
					GETDATE(), 
					@MA_NHAN_VIEN_THUC_HIEN, 
					@TEN_KHACH_HANG, 
					@MA_NHAN_VIEN_THUC_HIEN, 
					@MA_NHAN_VIEN_THUC_HIEN, 
					GETDATE(), 
					GETDATE(),
					'A'
				)
				SET @MA_XUAT_KHO = (SELECT SCOPE_IDENTITY());
				
				SET @CHECKED_FLG = DBO.F_CHECK_REMAIN(@MA_HOA_DON)
				
				IF @CHECKED_FLG = 'FALSE'
				BEGIN
					UPDATE HOA_DON
					SET
					STATUS = 3, 
					UPDATE_BY = @MA_NHAN_VIEN_THUC_HIEN, 
					UPDATE_AT = GETDATE()
					WHERE 
					MA_HOA_DON = @MA_HOA_DON
				END
				
				OPEN CHI_TIEC_HOA_DON_CURSOR_EXPORT
				FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR_EXPORT 
					INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @DON_GIA_TEMP, @SO_LUONG_TEMP, @MA_DON_VI
				WHILE @@FETCH_STATUS = 0 
				BEGIN					
					INSERT INTO
					CHI_TIET_XUAT_KHO
					(
						MA_XUAT_KHO, 
						MA_SAN_PHAM, 
						SO_LUONG, 
						GIA_XUAT, 
						SO_LUONG_TEMP,
						DON_GIA_TEMP,
						MA_DON_VI,
						CREATE_BY, 
						UPDATE_BY, 
						CREATE_AT, 
						UPDATE_AT, 
						ACTIVE
					)
					VALUES
					(
						@MA_XUAT_KHO, 
						@MA_SAN_PHAM, 
						@SO_LUONG, 
						@DON_GIA, 
						@SO_LUONG_TEMP,
						@DON_GIA_TEMP,
						@MA_DON_VI,
						@MA_NHAN_VIEN_THUC_HIEN, 
						@MA_NHAN_VIEN_THUC_HIEN,
						GETDATE(), 
						GETDATE(), 
						'A'
					)
					FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR_EXPORT 
						INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @DON_GIA_TEMP, @SO_LUONG_TEMP, @MA_DON_VI
				END;
				CLOSE CHI_TIEC_HOA_DON_CURSOR_EXPORT;
				DEALLOCATE CHI_TIEC_HOA_DON_CURSOR_EXPORT;
				
				SET @RETURN_VALUE = 1;
				
			END;
		END
		ELSE
		BEGIN
			DECLARE CHI_TIEC_HOA_DON_CURSOR CURSOR FOR
			SELECT 
			MA_SAN_PHAM, 
			SO_LUONG, 
			ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)* ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100, 
			MA_KHO_XUAT
			FROM
			CHI_TIET_HOA_DON
			WHERE
			ACTIVE = 'A'
			AND MA_HOA_DON = @MA_HOA_DON
			AND MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE MA_HOA_DON = @MA_HOA_DON)
			ORDER BY MA_KHO_XUAT;
			
			SET @FLG = 'TRUE';
			
			OPEN CHI_TIEC_HOA_DON_CURSOR
			FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @STORE_ID
			WHILE @@FETCH_STATUS = 0 
			BEGIN
				SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@STORE_ID, @MA_SAN_PHAM);
				IF @SO_LUONG_TON IS NULL OR @SO_LUONG_TON = 0 OR @SO_LUONG_TON < @SO_LUONG
				BEGIN
					SET @FLG = 'FALSE'
					BREAK;
				END
				FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG, @DON_GIA, @STORE_ID
			END;
			
			CLOSE CHI_TIEC_HOA_DON_CURSOR;
			DEALLOCATE CHI_TIEC_HOA_DON_CURSOR;
			
			IF @FLG = 'FALSE'
			BEGIN
				SET @RETURN_VALUE = 0;
			END
			
			IF @FLG = 'TRUE'
			BEGIN
				UPDATE HOA_DON
				SET
					STATUS = 3, 
					UPDATE_BY = @MA_NHAN_VIEN_THUC_HIEN, 
					UPDATE_AT = GETDATE()
				WHERE 
					MA_HOA_DON = @MA_HOA_DON;
				
				DECLARE CHI_TIEC_HOA_DON_CURSOR1 CURSOR FOR
				SELECT 
					MA_SAN_PHAM, 
					SO_LUONG, 
					ISNULL(DON_GIA,0) - ISNULL(DON_GIA,0)*ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100 DON_GIA, 
					ISNULL(DON_GIA_TEMP,0) - ISNULL(DON_GIA_TEMP,0)* ISNULL(PHAN_TRAM_CHIEC_KHAU,0)/100 DON_GIA_TEMP,
					SO_LUONG_TEMP, 
					MA_DON_VI,
					MA_KHO_XUAT
				FROM
				CHI_TIET_HOA_DON
				WHERE
				ACTIVE = 'A'
				AND MA_HOA_DON = @MA_HOA_DON
				AND MA_KHO_XUAT NOT IN (SELECT MA_KHO_XUAT FROM XUAT_KHO WHERE MA_HOA_DON = @MA_HOA_DON)
				ORDER BY MA_KHO_XUAT;
				
				SET @STORE_ID = 0;
				OPEN CHI_TIEC_HOA_DON_CURSOR1
				FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR1 
					INTO 
					@MA_SAN_PHAM, 
					@SO_LUONG, 
					@DON_GIA, 
					@DON_GIA_TEMP, 
					@SO_LUONG_TEMP, 
					@MA_DON_VI, 
					@NEXT_STORE_ID
				WHILE @@FETCH_STATUS = 0 
				BEGIN
					IF @STORE_ID <> @NEXT_STORE_ID
					BEGIN
						SET @STORE_ID = @NEXT_STORE_ID;
						INSERT INTO 
							XUAT_KHO 
							(	
								MA_HOA_DON, 
								LY_DO_XUAT,  --0
								MA_KHO_XUAT,
								NGAY_XUAT, 
								MA_NHAN_VIEN_XUAT, 
								TEN_NGUOI_NHAN_HANG, 
								CREATE_BY, 
								UPDATE_BY, 
								CREATE_AT, 
								UPDATE_AT, 
								ACTIVE
							)
							VALUES
							(
								@MA_HOA_DON, 
								0, 
								@STORE_ID, 
								GETDATE(), 
								@MA_NHAN_VIEN_THUC_HIEN, 
								@TEN_KHACH_HANG, 
								@MA_NHAN_VIEN_THUC_HIEN, 
								@MA_NHAN_VIEN_THUC_HIEN, 
								GETDATE(), 
								GETDATE(),
								'A'
							)
						SET @MA_XUAT_KHO = (SELECT SCOPE_IDENTITY());
					END;
					INSERT INTO
					CHI_TIET_XUAT_KHO
					(
						MA_XUAT_KHO, 
						MA_SAN_PHAM, 
						SO_LUONG, 
						GIA_XUAT, 
						SO_LUONG_TEMP,
						DON_GIA_TEMP,
						MA_DON_VI,
						CREATE_BY, 
						UPDATE_BY, 
						CREATE_AT, 
						UPDATE_AT, 
						ACTIVE
					)
					VALUES
					(
						@MA_XUAT_KHO, 
						@MA_SAN_PHAM, 
						@SO_LUONG, 
						@DON_GIA, 
						@SO_LUONG_TEMP,
						@DON_GIA_TEMP,
						@MA_DON_VI,
						@MA_NHAN_VIEN_THUC_HIEN, 
						@MA_NHAN_VIEN_THUC_HIEN,
						GETDATE(), 
						GETDATE(), 
						'A'
					)
					FETCH NEXT FROM CHI_TIEC_HOA_DON_CURSOR1 
						INTO 
						@MA_SAN_PHAM, 
						@SO_LUONG, 
						@DON_GIA, 
						@DON_GIA_TEMP, 
						@SO_LUONG_TEMP, 
						@MA_DON_VI, 
						@NEXT_STORE_ID
				END;
				
				CLOSE CHI_TIEC_HOA_DON_CURSOR1;
				DEALLOCATE CHI_TIEC_HOA_DON_CURSOR1;
				SET @RETURN_VALUE = 1;
			END
		END
	END;
END


ALTER TABLE HOA_DON
ADD SO_DIEN_THOAI VARCHAR(20)

ALTER PROCEDURE [dbo].[SP_GET_HOA_DON_INFO]
@MA_HOA_DON INT
AS
BEGIN
	SELECT 
		HOA_DON.MA_HOA_DON, 
		HOA_DON.SO_HOA_DON, 
		HOA_DON.MA_KHACH_HANG, 
		CASE WHEN HOA_DON.MA_KHACH_HANG IS NULL
				THEN HOA_DON.TEN_KHACH_HANG
			ELSE
				KHACH_HANG.TEN_KHACH_HANG 
		END AS TEN_KHACH_HANG,
		CASE WHEN HOA_DON.MA_KHACH_HANG IS NULL
				THEN HOA_DON.SO_DIEN_THOAI
			ELSE
				KHACH_HANG.SO_DIEN_THOAI 
		END AS SO_DIEN_THOAI,
		HOA_DON.MA_NHAN_VIEN_BAN, 
		NV_BAN.TEN_NGUOI_DUNG AS TEN_NGUOI_BAN,
		HOA_DON.NGAY_BAN, 
		HOA_DON.NGAY_GIAO,
		HOA_DON.DIA_CHI_GIAO_HANG,
		HOA_DON.STATUS, 
		HOA_DON.SO_TIEN_KHACH_TRA, 
		HOA_DON.SO_TIEN_NO_GOI_DAU, 
		HOA_DON.MA_NHAN_VIEN_THU_TIEN, 
		NV_TT.TEN_NGUOI_DUNG TEN_NV_TT, 
		ISNULL(SUM(CHI_TIET_HOA_DON.SO_LUONG_TEMP*CHI_TIET_HOA_DON.DON_GIA_TEMP), 0) TONG_TIEN, 
		ISNULL(SUM(CHI_TIET_HOA_DON.SO_LUONG_TEMP*CHI_TIET_HOA_DON.DON_GIA_TEMP*PHAN_TRAM_CHIEC_KHAU/100), 0) CHIEC_KHAU
	FROM 
		HOA_DON
		LEFT JOIN CHI_TIET_HOA_DON ON HOA_DON.MA_HOA_DON =  CHI_TIET_HOA_DON.MA_HOA_DON
		LEFT JOIN KHACH_HANG ON HOA_DON.MA_KHACH_HANG = KHACH_HANG.MA_KHACH_HANG
		JOIN NGUOI_DUNG NV_BAN ON HOA_DON.MA_NHAN_VIEN_BAN = NV_BAN.MA_NGUOI_DUNG
		LEFT JOIN NGUOI_DUNG NV_TT ON HOA_DON.MA_NHAN_VIEN_THU_TIEN = NV_TT.MA_NGUOI_DUNG
	WHERE
		HOA_DON.MA_HOA_DON = @MA_HOA_DON
		AND HOA_DON.ACTIVE = 'A'
	GROUP BY 	
	HOA_DON.MA_HOA_DON, 
	HOA_DON.SO_HOA_DON, 
	HOA_DON.MA_KHACH_HANG, 
	CASE WHEN HOA_DON.MA_KHACH_HANG IS NULL
			THEN HOA_DON.TEN_KHACH_HANG
		ELSE
			KHACH_HANG.TEN_KHACH_HANG 
	END,
	CASE WHEN HOA_DON.MA_KHACH_HANG IS NULL
				THEN HOA_DON.SO_DIEN_THOAI
			ELSE
				KHACH_HANG.SO_DIEN_THOAI 
		END,
	HOA_DON.MA_NHAN_VIEN_BAN, 
	NV_BAN.TEN_NGUOI_DUNG,
	HOA_DON.NGAY_BAN, 
	HOA_DON.NGAY_GIAO,
	HOA_DON.DIA_CHI_GIAO_HANG,
	HOA_DON.STATUS, 
	HOA_DON.SO_TIEN_KHACH_TRA, 
	HOA_DON.SO_TIEN_NO_GOI_DAU, 
	HOA_DON.MA_NHAN_VIEN_THU_TIEN, 
	NV_TT.TEN_NGUOI_DUNG
END

ALTER PROCEDURE [dbo].[SP_GET_IMPORT]
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_NHAN_VIEN_NHAP INT, 
@TEN_NHAN_VIEN_NHAP NVARCHAR(100),
@LY_DO_NHAP INT, 
@MA_KHO INT, 
@TEN_KHO NVARCHAR(100),
@MA_NHA_CC INT, 
@TEN_NHA_CUNG_CAP NVARCHAR(100)
AS
BEGIN
	SELECT 
		NHAP_KHO.MA_NHAP_KHO, 
		NHAP_KHO.SO_HOA_DON, 
		NHAP_KHO.NGAY_NHAP, 
		NHAP_KHO.NHAN_VIEN_NHAP, 
		NHAP_KHO.MA_NHA_CUNG_CAP, 
		NHAP_KHO.MA_KHO, 
		NGUOI_DUNG.TEN_NGUOI_DUNG, 
		KHO.TEN_KHO, 
		NHA_CUNG_CAP.TEN_NHA_CUNG_CAP, 
		NHAP_KHO.LY_DO_NHAP, 
		ISNULL(SUM(ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG,0)*ISNULL(CHI_TIET_NHAP_KHO.GIA_VON,0)),0) VAL
	FROM 
		NHAP_KHO LEFT JOIN NHA_CUNG_CAP ON NHAP_KHO.MA_NHA_CUNG_CAP = NHA_CUNG_CAP.MA_NHA_CUNG_CAP,
		CHI_TIET_NHAP_KHO, 
		KHO, 
		NGUOI_DUNG
	WHERE
		NHAP_KHO.ACTIVE = 'A'
		AND (@TEN_NHAN_VIEN_NHAP IS NULL OR @TEN_NHAN_VIEN_NHAP = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%'  + @TEN_NHAN_VIEN_NHAP + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAP = 0 OR NHAN_VIEN_NHAP = @MA_NHAN_VIEN_NHAP)
		AND (@LY_DO_NHAP = -1 OR LY_DO_NHAP = @LY_DO_NHAP)
		AND (@MA_KHO = 0 OR NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR KHO.TEN_KHO LIKE '%' +  @TEN_KHO + '%')
		AND (@MA_NHA_CC = 0 OR NHAP_KHO.MA_NHA_CUNG_CAP = @MA_NHA_CC) 
		AND (@TEN_NHA_CUNG_CAP IS NULL OR @TEN_NHA_CUNG_CAP = '' OR NHA_CUNG_CAP.TEN_NHA_CUNG_CAP LIKE '%' + @TEN_NHA_CUNG_CAP + '%')
		AND NHAP_KHO.MA_KHO = KHO.MA_KHO
		AND NHAP_KHO.NHAN_VIEN_NHAP = NGUOI_DUNG.MA_NGUOI_DUNG
		AND NHAP_KHO.MA_NHAP_KHO = CHI_TIET_NHAP_KHO.MA_NHAP_KHO
	GROUP BY
		NHAP_KHO.MA_NHAP_KHO, 
		NHAP_KHO.SO_HOA_DON, 
		NHAP_KHO.NGAY_NHAP, 
		NHAP_KHO.NHAN_VIEN_NHAP, 
		NHAP_KHO.MA_NHA_CUNG_CAP, 
		NHAP_KHO.MA_KHO, 
		NGUOI_DUNG.TEN_NGUOI_DUNG, 
		KHO.TEN_KHO, 
		NHA_CUNG_CAP.TEN_NHA_CUNG_CAP, 
		NHAP_KHO.LY_DO_NHAP
END