CREATE TABLE TRA_HANG_NCC
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	MA_NHA_CUNG_CAP INT FOREIGN KEY REFERENCES NHA_CUNG_CAP(MA_NHA_CUNG_CAP), 
	MA_PHIEU_TRA INT FOREIGN KEY REFERENCES TRA_HANG(MA_TRA_HANG), 
	NGAY_LAP_PHIEU DATE, 
	NGUOI_LAP_PHIEU INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	GHI_CHU NVARCHAR(1000),
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)

CREATE TABLE TRA_HANG_NCC_CHI_TIET
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MA_PHIEU_TRA_NCC INT FOREIGN KEY REFERENCES TRA_HANG_NCC(ID), 
	MA_SAN_PHAM INT FOREIGN KEY REFERENCES SAN_PHAM(MA_SAN_PHAM),
	SO_LUONG FLOAT, 
	DON_GIA FLOAT, 
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
)