ALTER PROCEDURE [dbo].[SP_GET_CHI_TIET_PHIEU_XUAT_CHUYEN]
@MA_XUAT_KHO INT
AS
BEGIN
	SELECT
		 CHI_TIET_XUAT_KHO.MA_SAN_PHAM, 
		 SAN_PHAM.TEN_SAN_PHAM, 
		 SAN_PHAM.CODE, 
		 CHI_TIET_XUAT_KHO.SO_LUONG, 
		 CHI_TIET_XUAT_KHO.MA_DON_VI, 
		 CHI_TIET_XUAT_KHO.SO_LUONG_TEMP, 
		 DBO.F_GET_CONVERTOR(CHI_TIET_XUAT_KHO.MA_SAN_PHAM,CHI_TIET_XUAT_KHO.MA_DON_VI) HE_SO,
		 0 DEL_FLG
	FROM
		CHI_TIET_XUAT_KHO,
		SAN_PHAM
	WHERE 
		(CHI_TIET_XUAT_KHO.ACTIVE = 'A' OR CHI_TIET_XUAT_KHO.ACTIVE = 'W')
	AND CHI_TIET_XUAT_KHO.MA_XUAT_KHO = @MA_XUAT_KHO
	AND CHI_TIET_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM	
END

ALTER PROCEDURE SP_IMPORT_TRANSFER
@MA_PHIEU_CHUYEN INT, 
@NGAY_NHAP DATE,
@MA_NHAN_VIEN INT,
@MA_KHO INT,
@GHI_CHU NVARCHAR(1000), 
@RETURN_VALUE INT OUTPUT
AS
BEGIN
	DECLARE @MA_SAN_PHAM INT;
	DECLARE @MA_DON_VI INT;
	DECLARE @SO_LUONG_TEMP FLOAT;
	DECLARE @SO_LUONG FLOAT;
	DECLARE @ID INT;
	
	DECLARE TRANSFER_DEDTAIL_CURSOR CURSOR FOR
	SELECT 
		CHI_TIET_XUAT_KHO.MA_SAN_PHAM, 
		CHI_TIET_XUAT_KHO.SO_LUONG, 
		CHI_TIET_XUAT_KHO.MA_DON_VI, 
		CHI_TIET_XUAT_KHO.SO_LUONG_TEMP
	FROM
		CHI_TIET_XUAT_KHO
	WHERE
		ACTIVE = 'A'
		AND MA_XUAT_KHO = @MA_PHIEU_CHUYEN
		
	BEGIN TRANSACTION
	BEGIN TRY
		INSERT INTO 
			NHAP_KHO(NGAY_NHAP, NHAN_VIEN_NHAP, MA_KHO, LY_DO_NHAP, GHI_CHU, MA_PHIEU_XUAT, CREATE_BY, UPDATE_BY, CREATE_AT, UPDATE_AT, ACTIVE)
		VALUES
			(@NGAY_NHAP, @MA_NHAN_VIEN, @MA_KHO, 3, @GHI_CHU, @MA_PHIEU_CHUYEN, @MA_NHAN_VIEN, @MA_NHAN_VIEN, GETDATE(), GETDATE(), 'A')
		SET @ID = (SELECT SCOPE_IDENTITY());
		OPEN TRANSFER_DEDTAIL_CURSOR
		FETCH NEXT FROM TRANSFER_DEDTAIL_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG, @MA_DON_VI, @SO_LUONG_TEMP
		WHILE @@FETCH_STATUS = 0 
		BEGIN
			INSERT INTO CHI_TIET_NHAP_KHO(MA_NHAP_KHO, MA_SAN_PHAM, SO_LUONG, MA_DON_VI, SO_LUONG_TEMP, CREATE_BY, UPDATE_BY, CREATE_AT, UPDATE_AT, ACTIVE)
			VALUES(@ID, @MA_SAN_PHAM, @SO_LUONG, @MA_DON_VI, @SO_LUONG_TEMP, @MA_NHAN_VIEN, @MA_NHAN_VIEN, GETDATE(), GETDATE(), 'A');			
			FETCH NEXT FROM TRANSFER_DEDTAIL_CURSOR INTO @MA_SAN_PHAM, @SO_LUONG, @MA_DON_VI, @SO_LUONG_TEMP
		END
		CLOSE TRANSFER_DEDTAIL_CURSOR;
		DEALLOCATE TRANSFER_DEDTAIL_CURSOR;	
		COMMIT TRANSACTION;		
		SET @RETURN_VALUE = 1
	END TRY
	BEGIN CATCH
		SET @RETURN_VALUE = -1
		ROLLBACK TRANSACTION
	END CATCH
END

ALTER PROCEDURE [dbo].[SP_GET_IMPORT]
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_NHAN_VIEN_NHAP INT, 
@TEN_NHAN_VIEN_NHAP NVARCHAR(100),
@LY_DO_NHAP INT, 
@MA_KHO INT, 
@TEN_KHO NVARCHAR(100),
@MA_NHA_CC INT, 
@TEN_NHA_CUNG_CAP NVARCHAR(100)
AS
BEGIN
	SELECT 
		NHAP_KHO.MA_NHAP_KHO, 
		NHAP_KHO.SO_HOA_DON, 
		NHAP_KHO.NGAY_NHAP, 
		NHAP_KHO.NHAN_VIEN_NHAP, 
		NHAP_KHO.MA_NHA_CUNG_CAP, 
		NHAP_KHO.MA_KHO, 
		NGUOI_DUNG.TEN_NGUOI_DUNG, 
		KHO.TEN_KHO, 
		NHA_CUNG_CAP.TEN_NHA_CUNG_CAP, 
		NHAP_KHO.LY_DO_NHAP
	FROM 
		NHAP_KHO LEFT JOIN NHA_CUNG_CAP ON NHAP_KHO.MA_NHA_CUNG_CAP = NHA_CUNG_CAP.MA_NHA_CUNG_CAP,
		KHO, 
		NGUOI_DUNG
	WHERE
		NHAP_KHO.ACTIVE = 'A'
		AND (@TEN_NHAN_VIEN_NHAP IS NULL OR @TEN_NHAN_VIEN_NHAP = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%'  + @TEN_NHAN_VIEN_NHAP + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAP = 0 OR NHAN_VIEN_NHAP = @MA_NHAN_VIEN_NHAP)
		AND (@LY_DO_NHAP = 0 OR LY_DO_NHAP = @LY_DO_NHAP)
		AND (@MA_KHO = 0 OR NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR KHO.TEN_KHO LIKE '%' +  @TEN_KHO + '%')
		AND (@MA_NHA_CC = 0 OR NHAP_KHO.MA_NHA_CUNG_CAP = @MA_NHA_CC) 
		AND (@TEN_NHA_CUNG_CAP IS NULL OR @TEN_NHA_CUNG_CAP = '' OR NHA_CUNG_CAP.TEN_NHA_CUNG_CAP LIKE '%' + @TEN_NHA_CUNG_CAP + '%')
		AND NHAP_KHO.MA_KHO = KHO.MA_KHO
		AND NHAP_KHO.NHAN_VIEN_NHAP = NGUOI_DUNG.MA_NGUOI_DUNG
END

ALTER PROCEDURE [dbo].[SP_IMPORT_REPORTER_DETAIL]
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT
		V_NHAP_KHO.NGAY_NHAP, 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI, 
		SUM(V_NHAP_KHO.SO_LUONG) SO_LUONG, 
		ISNULL(V_NHAP_KHO.GIA_VON, 0) GIA_VON, 
		ISNULL(SUM(V_NHAP_KHO.SO_LUONG)*GIA_VON,0) VALUE 
	FROM
	V_NHAP_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_NHAP_KHO.LY_DO_NHAP = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_NHAP_KHO.GIA_VON, 
		V_NHAP_KHO.NGAY_NHAP, 
		DON_VI_TINH.TEN_DON_VI
	ORDER BY V_NHAP_KHO.NGAY_NHAP
END 

ALTER PROCEDURE [dbo].[SP_IMPORT_REPORTER]
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI,
		SUM(V_NHAP_KHO.SO_LUONG) SO_LUONG, 
		ISNULL(V_NHAP_KHO.GIA_VON,0) GIA_VON, 
		ISNULL(SUM(V_NHAP_KHO.SO_LUONG)*GIA_VON,0) VALUE 
	FROM
	V_NHAP_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_NHAP_KHO.LY_DO_NHAP = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_NHAP_KHO.GIA_VON, 
		DON_VI_TINH.TEN_DON_VI
END 

CREATE PROCEDURE SP_GET_PRODUC_4_RETURN
@TEN_SAN_PHAM NVARCHAR(100)
AS
BEGIN
	SELECT 
		MA_SAN_PHAM,
		CODE, 
		TEN_SAN_PHAM, 
		ISNULL(GIA_BAN_3*90/100, 0) DON_GIA
	FROM 
	SAN_PHAM
	WHERE
		ACTIVE = 'A'
	AND (CODE  LIKE '%' + @TEN_SAN_PHAM  + '%' OR TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM  + '%')
END

ALTER TABLE CHI_TIET_TRA_HANG
ADD MA_DON_VI INT, 
	SO_LUONG_TEMP FLOAT
