ALTER PROCEDURE [dbo].[SP_IMPORT_REPORTER_DETAIL]
@KIND INT, 
@MA_KHO INT,
@TEN_KHO NVARCHAR(200),
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT
		V_NHAP_KHO.NGAY_NHAP, 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI, 
		SUM(V_NHAP_KHO.SO_LUONG) SO_LUONG, 
		ISNULL(V_NHAP_KHO.GIA_VON, 0) GIA_VON, 
		ISNULL(SUM(V_NHAP_KHO.SO_LUONG)*GIA_VON,0) VALUE 
	FROM
	V_NHAP_KHO, 
	KHO,
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_NHAP_KHO.LY_DO_NHAP = @KIND)
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_NHAP_KHO.NGAY_NHAP <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND V_NHAP_KHO.MA_KHO = KHO.MA_KHO
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_NHAP_KHO.GIA_VON, 
		V_NHAP_KHO.NGAY_NHAP, 
		DON_VI_TINH.TEN_DON_VI
	ORDER BY V_NHAP_KHO.NGAY_NHAP
END 


ALTER PROCEDURE [dbo].[SP_EXPORT_REPORT]
@KIND INT, 
@MA_KHO INT,
@TEN_KHO NVARCHAR(200),
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG),0) SO_LUONG, 
		ISNULL(V_XUAT_KHO.GIA_XUAT, 0) GIA_XUAT,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT,0) VALUE 
	FROM
	V_XUAT_KHO, 
	KHO,
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND V_XUAT_KHO.MA_KHO_XUAT = KHO.MA_KHO
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_XUAT_KHO.GIA_XUAT, 
		DON_VI_TINH.TEN_DON_VI
END 

ALTER PROCEDURE [dbo].[SP_EXPORT_REPORT_SUM]
@KIND INT, 
@MA_KHO INT,
@TEN_KHO NVARCHAR(200),
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
		SELECT
		ISNULL(SUM(VALUE),0) VALUE
		FROM
		(
			SELECT
				SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT VALUE 
			FROM
			V_XUAT_KHO, 
			KHO,
			SAN_PHAM
			WHERE 
				(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
				AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
				AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
				AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
				AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
				AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
				AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
				AND  V_XUAT_KHO.MA_KHO_XUAT = KHO.MA_KHO
				AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
			GROUP BY 
				V_XUAT_KHO.MA_SAN_PHAM, 
				SAN_PHAM.TEN_SAN_PHAM, 
				V_XUAT_KHO.GIA_XUAT, 
				V_XUAT_KHO.NGAY_XUAT
		)TEMP
END 


ALTER PROCEDURE [dbo].[SP_EXPORT_REPORT_DETAIL]
@KIND INT, 
@MA_KHO INT,
@TEN_KHO NVARCHAR(200),
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT
		V_XUAT_KHO.NGAY_XUAT, 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI, 
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG),0) SO_LUONG, 
		ISNULL(V_XUAT_KHO.GIA_XUAT,0)  GIA_XUAT,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT,0) VALUE 
	FROM
	V_XUAT_KHO, 
	KHO,
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
		AND V_XUAT_KHO.MA_KHO_XUAT  = KHO.MA_KHO
		AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_XUAT_KHO.GIA_XUAT, 
		V_XUAT_KHO.NGAY_XUAT, 
		DON_VI_TINH.TEN_DON_VI
	ORDER BY V_XUAT_KHO.NGAY_XUAT DESC
END 

ALTER PROCEDURE [dbo].[SP_GET_NHAP_XUAT]
@MA_KHO INT,
@TEN_KHO NVARCHAR(200),
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		V_NHAP_XUAT_DETAIL.NGAY_NHAP_XUAT, 
		V_NHAP_XUAT_DETAIL.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI,
		ISNULL(SUM(V_NHAP_XUAT_DETAIL.SO_LUONG_NHAP), 0) SO_LUONG_NHAP, 
		ISNULL(SUM(V_NHAP_XUAT_DETAIL.SO_LUONG_XUAT),0) SO_LUONG_XUAT
	FROM 
		V_NHAP_XUAT_DETAIL, 
		KHO,
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		(@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_XUAT_DETAIL.MA_KHO = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_NHAP_XUAT_DETAIL.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_NHAP_XUAT_DETAIL.NGAY_NHAP_XUAT >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_NHAP_XUAT_DETAIL.NGAY_NHAP_XUAT <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
		AND V_NHAP_XUAT_DETAIL.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_NHAP_XUAT_DETAIL.NGAY_NHAP_XUAT, 
		V_NHAP_XUAT_DETAIL.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI
	ORDER BY V_NHAP_XUAT_DETAIL.NGAY_NHAP_XUAT
END

ALTER PROCEDURE [dbo].[SP_GET_PHIEU_XUAT_KHO_BAN_LE]
@MA_KHO INT, 
@TEN_KHO NVARCHAR(200),
@MA_NHAN_VIEN_XUAT INT, 
@TEN_NHAN_VIEN_XUAT NVARCHAR(100), 
@MA_KHACH_HANG INT, 
@TEN_KHACH_HANG NVARCHAR(100), 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		XUAT_KHO.MA_XUAT_KHO, 
		KHO.TEN_KHO,
		XUAT_KHO.MA_HOA_DON,
		XUAT_KHO.NGAY_XUAT, 
		XUAT_KHO.MA_NHAN_VIEN_XUAT, 
		NGUOI_DUNG.TEN_NGUOI_DUNG TEN_NHAN_VIEN_XK, 
		XUAT_KHO.TEN_NGUOI_NHAN_HANG, 
		HOA_DON.SO_HOA_DON, 
		HOA_DON.MA_KHACH_HANG, 
		HOA_DON.TEN_KHACH_HANG, 
		HOA_DON.DIA_CHI_GIAO_HANG
	FROM 
		XUAT_KHO,
		(
			SELECT DISTINCT MA_HOA_DON, SO_HOA_DON, MA_KHACH_HANG, TEN_KHACH_HANG, DIA_CHI_GIAO_HANG
			FROM V_HOA_DON 
			WHERE ((@MA_KHACH_HANG = 0 OR MA_KHACH_HANG = @MA_KHACH_HANG) AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TEN_KHACH_HANG LIKE '%' + @TEN_KHACH_HANG + '%'))
		)HOA_DON, 
		NGUOI_DUNG, 
		KHO
	WHERE 
		XUAT_KHO.ACTIVE = 'A'
		AND (@MA_KHO = 0 OR MA_KHO_XUAT = @MA_KHO)
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
		AND (@MA_NHAN_VIEN_XUAT = 0 OR XUAT_KHO.MA_NHAN_VIEN_XUAT = @MA_NHAN_VIEN_XUAT)
		AND (@TEN_NHAN_VIEN_XUAT IS NULL OR @TEN_NHAN_VIEN_XUAT = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @TEN_NHAN_VIEN_XUAT + '%')
		AND (@FROM_DATE IS NULL OR CAST(XUAT_KHO.NGAY_XUAT AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(XUAT_KHO.NGAY_XUAT AS DATE) <= CAST(@TO_DATE AS DATE))
		AND XUAT_KHO.MA_HOA_DON = HOA_DON.MA_HOA_DON
		AND XUAT_KHO.MA_NHAN_VIEN_XUAT = NGUOI_DUNG.MA_NGUOI_DUNG
		AND XUAT_KHO.MA_KHO_XUAT = KHO.MA_KHO
	ORDER BY NGAY_XUAT
END


ALTER PROCEDURE [dbo].[SP_GET_HOA_DON_CAN_XUAT_KHO]
@MA_KHACH_HANG INT, 
@TEN_KHACH_HANG NVARCHAR(100),
@MA_KHO INT, 
@TEN_KHO NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT DISTINCT
		MA_HOA_DON, 
		SO_HOA_DON, 
		MA_KHACH_HANG, 
		TEN_KHACH_HANG, 
		MA_NHAN_VIEN_BAN,
		TEN_NHAN_VIEN_BAN, 
		NGAY_BAN, 
		NGAY_GIAO, 
		DIA_CHI_GIAO_HANG
	FROM 
		V_HOA_DON,
		KHO
	WHERE
		STATUS = 2
		AND (@MA_KHACH_HANG = 0 OR MA_KHACH_HANG = @MA_KHACH_HANG)
		AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TEN_KHACH_HANG LIKE '%' + @TEN_KHACH_HANG + '%')
		AND (@MA_KHO = 0 OR MA_KHO_XUAT = @MA_KHO)		
		AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
		AND V_HOA_DON.MA_KHO_XUAT = KHO.MA_KHO
		AND (@FROM_DATE IS NULL OR CAST(NGAY_BAN AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_BAN AS DATE) <= CAST(@TO_DATE AS DATE)) 
END