ALTER PROCEDURE [dbo].[SP_GET_BILL_INFOR]
@ID INT
AS
BEGIN
	SELECT 
		HOA_DON.MA_HOA_DON, 
		HOA_DON.SO_HOA_DON, 
		CASE ISNULL(HOA_DON.MA_KHACH_HANG,0) 
		WHEN 0 THEN
			HOA_DON.TEN_KHACH_HANG
		ELSE
			KHACH_HANG.TEN_KHACH_HANG
		END AS TEN_KHACH_HANG,
		CASE ISNULL(HOA_DON.MA_KHACH_HANG,0) 
		WHEN 0 THEN
			HOA_DON.SO_DIEN_THOAI
		ELSE
			KHACH_HANG.SO_DIEN_THOAI
		END AS SO_DIEN_THOAI,
		CASE ISNULL(HOA_DON.MA_KHACH_HANG,0)
		WHEN 0 THEN 3
		ELSE
			KHACH_HANG.KIND
		END AS KIND,
		HOA_DON.MA_KHACH_HANG,
		HOA_DON.NGAY_BAN,
		HOA_DON.NGAY_GIAO,
		HOA_DON.DIA_CHI_GIAO_HANG, 
		HOA_DON.STATUS
	FROM 
	HOA_DON
	LEFT JOIN KHACH_HANG ON HOA_DON.MA_KHACH_HANG = KHACH_HANG.MA_KHACH_HANG
	WHERE
		HOA_DON.ACTIVE = 'A'
		AND HOA_DON.MA_HOA_DON = @ID
END