ALTER PROCEDURE SP_GET_PHIEU_XUAT_KHO_BAN_LE
@MA_KHO INT, 
@MA_NHAN_VIEN_XUAT INT, 
@TEN_NHAN_VIEN_XUAT NVARCHAR(100), 
@MA_KHACH_HANG INT, 
@TEN_KHACH_HANG NVARCHAR(100), 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		XUAT_KHO.MA_XUAT_KHO, 
		KHO.TEN_KHO,
		XUAT_KHO.MA_HOA_DON,
		XUAT_KHO.NGAY_XUAT, 
		XUAT_KHO.MA_NHAN_VIEN_XUAT, 
		NGUOI_DUNG.TEN_NGUOI_DUNG TEN_NHAN_VIEN_XK, 
		XUAT_KHO.TEN_NGUOI_NHAN_HANG, 
		HOA_DON.SO_HOA_DON, 
		HOA_DON.MA_KHACH_HANG, 
		HOA_DON.TEN_KHACH_HANG, 
		HOA_DON.DIA_CHI_GIAO_HANG
	FROM 
		XUAT_KHO,
		(
			SELECT DISTINCT MA_HOA_DON, SO_HOA_DON, MA_KHACH_HANG, TEN_KHACH_HANG, DIA_CHI_GIAO_HANG
			FROM V_HOA_DON 
			WHERE ((@MA_KHACH_HANG = 0 OR MA_KHACH_HANG = @MA_KHACH_HANG) AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TEN_KHACH_HANG LIKE '%' + @TEN_KHACH_HANG + '%'))
		)HOA_DON, 
		NGUOI_DUNG, 
		KHO
	WHERE 
		XUAT_KHO.ACTIVE = 'A'
		AND (@MA_KHO = 0 OR MA_KHO_XUAT = @MA_KHO)
		AND (@MA_NHAN_VIEN_XUAT = 0 OR XUAT_KHO.MA_NHAN_VIEN_XUAT = @MA_NHAN_VIEN_XUAT)
		AND (@TEN_NHAN_VIEN_XUAT IS NULL OR @TEN_NHAN_VIEN_XUAT = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @TEN_NHAN_VIEN_XUAT + '%')
		AND (@FROM_DATE IS NULL OR CAST(XUAT_KHO.NGAY_XUAT AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(XUAT_KHO.NGAY_XUAT AS DATE) <= CAST(@TO_DATE AS DATE))
		AND XUAT_KHO.MA_HOA_DON = HOA_DON.MA_HOA_DON
		AND XUAT_KHO.MA_NHAN_VIEN_XUAT = NGUOI_DUNG.MA_NGUOI_DUNG
		AND XUAT_KHO.MA_KHO_XUAT = KHO.MA_KHO
	ORDER BY NGAY_XUAT
END


EXEC SP_GET_PHIEU_XUAT_KHO_BAN_LE 0,0,'',0,'',NULL,NULL;

CREATE PROCEDURE SP_DELETE_EXPORT_4_SALE
@MA_XUAT_KHO INT, 
@MA_NHAN_VIEN_TH INT, 
@RETURN_VALUE INT OUTPUT
AS
BEGIN
	DECLARE  @MA_HOA_DON INT;
	SELECT @MA_HOA_DON = MA_HOA_DON
	FROM XUAT_KHO
	WHERE ACTIVE = 'A' AND MA_XUAT_KHO = @MA_XUAT_KHO;
	IF @MA_HOA_DON IS NOT NULL
	BEGIN
		BEGIN TRY
			UPDATE 
				HOA_DON
			SET
				STATUS = 2,
				UPDATE_BY = @MA_NHAN_VIEN_TH,
				UPDATE_AT = GETDATE()
			WHERE
				MA_HOA_DON = @MA_HOA_DON;
			UPDATE 
				CHI_TIET_XUAT_KHO
			SET 
				ACTIVE = 'I', 
				UPDATE_BY = @MA_NHAN_VIEN_TH,
				UPDATE_AT = GETDATE()
			WHERE
				MA_XUAT_KHO = @MA_XUAT_KHO;
			UPDATE XUAT_KHO
			SET 
				ACTIVE = 'I', 
				UPDATE_BY = @MA_NHAN_VIEN_TH,
				UPDATE_AT = GETDATE()
			WHERE 
				MA_XUAT_KHO = @MA_XUAT_KHO;
			SET @RETURN_VALUE = 1
		END TRY
		BEGIN CATCH
			SET @RETURN_VALUE = 0
		END CATCH
	END;
END