CREATE FUNCTION F_GET_STORE_PERMISSION
(
	@USR_ID INT, 
	@STORE_ID INT
)
RETURNS INT
AS
BEGIN
	RETURN ISNULL((SELECT ISNULL(USR_ID,'0') + ISNULL(IS_DEFAULT,'0') FROM USER_STORE WHERE MA_KHO = @STORE_ID AND USR_ID = @USR_ID AND ACTIVE = 'A'),0);
END




ALTER PROCEDURE SP_GET_USER_STORE
 @USR_ID INT, 
 @USR_NAME NVARCHAR(250)
 AS
 BEGIN
	DECLARE @I INT;
	DECLARE @ID INT;
	DECLARE @MA_KHO INT;
	DECLARE @SO_LUONG_KHO INT;
	DECLARE @PERMISSION INT;
	DECLARE @MA_NGUOI_DUNG INT;
	DECLARE @TEN_NGUOI_DUNG NVARCHAR(250);
	DECLARE @COLUMN_NAME VARCHAR(50);
	DECLARE @DYN_SQL VARCHAR(MAX);
	DECLARE USRS_CURSOR CURSOR FOR
	SELECT 
		MA_NGUOI_DUNG, 
		TEN_NGUOI_DUNG
	FROM NGUOI_DUNG
	WHERE 
		ACTIVE = 'A'
		AND (@USR_ID = 0 OR NGUOI_DUNG.MA_NGUOI_DUNG = @USR_ID)
		AND (@USR_NAME IS NULL OR @USR_NAME = '' OR UPPER(TEN_NGUOI_DUNG) LIKE '%' + @USR_NAME + '%')
	
	CREATE TABLE #USER_STORE_TEMP 
	(
		ID INT IDENTITY(1,1) PRIMARY KEY,  
		USR_ID INT, 
		USR_NAME NVARCHAR(250)
	)

	SET @SO_LUONG_KHO = ISNULL((SELECT COUNT(MA_KHO) FROM KHO WHERE ACTIVE = 'A'),0);
	SET @I = 1;
	
	WHILE @I <= @SO_LUONG_KHO
	BEGIN
		SET @COLUMN_NAME = '';
		SET @COLUMN_NAME = 'KHO_ID_' + CAST(@I AS VARCHAR)
		SET @DYN_SQL = 'ALTER TABLE #USER_STORE_TEMP ADD ' + @COLUMN_NAME +' INT DEFAULT 0';
		EXEC(@DYN_SQL);
		SET @I = @I+1;
	END
	
	OPEN USRS_CURSOR 
			FETCH NEXT FROM USRS_CURSOR INTO @MA_NGUOI_DUNG ,@TEN_NGUOI_DUNG
			WHILE @@FETCH_STATUS = 0  
	BEGIN
		SET @I = 1;
		DECLARE KHO_CURSOR_IST CURSOR FOR
		SELECT MA_KHO 
		FROM KHO
		WHERE ACTIVE = 'A'
		ORDER BY MA_KHO; 
		
		INSERT INTO #USER_STORE_TEMP(USR_ID, USR_NAME) VALUES (@MA_NGUOI_DUNG, @TEN_NGUOI_DUNG);
		SET @ID = (SELECT SCOPE_IDENTITY());
		
		OPEN KHO_CURSOR_IST 
		FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
		WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @COLUMN_NAME = '';
			SET @COLUMN_NAME = 'KHO_ID_' + CAST(@I AS VARCHAR);
			SET @PERMISSION = DBO.F_GET_STORE_PERMISSION(@MA_NGUOI_DUNG, @MA_KHO);
			SET @DYN_SQL = 'UPDATE #USER_STORE_TEMP SET ' + @COLUMN_NAME + ' = ' + CAST(@PERMISSION AS VARCHAR) + ' WHERE ID = ' + CAST(@ID AS VARCHAR);
			EXEC(@DYN_SQL);
			SET @I = @I+1;
			FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
		END;					
		CLOSE KHO_CURSOR_IST;
		DEALLOCATE KHO_CURSOR_IST;
				
		FETCH NEXT FROM USRS_CURSOR INTO @MA_NGUOI_DUNG ,@TEN_NGUOI_DUNG		
		
	END
	
	CLOSE USRS_CURSOR
	DEALLOCATE USRS_CURSOR
	
	SELECT TOP 999
	#USER_STORE_TEMP.*
	FROM 
	#USER_STORE_TEMP
		
 END
