ALTER TABLE XUAT_KHO
ADD
	MA_PHIEU_TRA_NCC INT FOREIGN KEY REFERENCES TRA_HANG_NCC(ID)
;
ALTER TABLE SAN_PHAM 
ADD CODE VARCHAR(30);
 
CREATE UNIQUE INDEX UNIQUE_SAN_PHAM_CODE ON SAN_PHAM(CODE) WHERE CODE IS NOT NULL
;

CREATE PROCEDURE SP_GET_EXPORTED_BY_BILL_ID
