ALTER VIEW [dbo].[V_NHAP_XUAT_DETAIL]
AS
SELECT 
ISNULL(A.MA_KHO, B.MA_KHO) MA_KHO, 
ISNULL(A.MA_SAN_PHAM,B.MA_SAN_PHAM) MA_SAN_PHAM, 
ISNULL(A.NGAY_NHAP, B.NGAY_XUAT) NGAY_NHAP_XUAT,
ISNULL(A.SO_LUONG_NHAP,0) SO_LUONG_NHAP, 
ISNULL(B.SO_LUONG_XUAT,0) SO_LUONG_XUAT
FROM
(
	SELECT 
		V_NHAP_KHO.MA_KHO MA_KHO,
		V_NHAP_KHO.MA_SAN_PHAM, 
		V_NHAP_KHO.NGAY_NHAP,
		ISNULL(SUM(V_NHAP_KHO.SO_LUONG), 0) AS SO_LUONG_NHAP
	FROM 
		V_NHAP_KHO 
	GROUP BY V_NHAP_KHO.MA_SAN_PHAM, V_NHAP_KHO.MA_KHO, V_NHAP_KHO.NGAY_NHAP
)A
FULL JOIN 
(
	SELECT 
		V_XUAT_KHO.MA_KHO_XUAT MA_KHO,
		V_XUAT_KHO.MA_SAN_PHAM, 
		V_XUAT_KHO.NGAY_XUAT,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG), 0) AS SO_LUONG_XUAT
	FROM 
		V_XUAT_KHO 
	GROUP BY V_XUAT_KHO.MA_SAN_PHAM, V_XUAT_KHO.MA_KHO_XUAT,V_XUAT_KHO.NGAY_XUAT
)B
ON A.MA_KHO = B.MA_KHO AND A.MA_SAN_PHAM = B.MA_SAN_PHAM AND A.NGAY_NHAP = B.NGAY_XUAT
GO


