CREATE PROC SP_GET_TON_KHO_BY_ID
@INPUT_ID INT 
AS
BEGIN
	DECLARE @DYN_SQL VARCHAR(MAX);
	DECLARE @MA_KHO INT;
	DECLARE @MA_SAN_PHAM INT;
	DECLARE @TEN_SAN_PHAM NVARCHAR(100)
	DECLARE @TEN_DON_VI NVARCHAR(100)
	DECLARE @SO_LUONG_TON FLOAT;
	DECLARE @GIA_BAN_1 FLOAT;
	DECLARE @GIA_BAN_2 FLOAT;
	DECLARE @GIA_BAN_3 FLOAT;
	DECLARE @CHIEC_KHAU_1 FLOAT;
	DECLARE @CHIEC_KHAU_2 FLOAT;
	DECLARE @CHIEC_KHAU_3 FLOAT;
	DECLARE @COLUMN_NAME VARCHAR (50);
	DECLARE @ID INT;
	DECLARE @SO_LUONG_KHO INT;
	DECLARE @I INT;
	
	DECLARE SAN_PHAM_MY_CURSOR CURSOR FOR
	SELECT MA_SAN_PHAM, TEN_SAN_PHAM, TEN_DON_VI, GIA_BAN_1, GIA_BAN_2, GIA_BAN_3, CHIEC_KHAU_1, CHIEC_KHAU_2, CHIEC_KHAU_3
	FROM SAN_PHAM, DON_VI_TINH
	WHERE
	SAN_PHAM.ACTIVE = 'A'
	AND DON_VI_TINH.ACTIVE = 'A'
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	AND SAN_PHAM.MA_SAN_PHAM = @INPUT_ID;
	
	SET NOCOUNT ON;
	
	CREATE TABLE #TEMP_TON_KHO 
	(
		ID INT IDENTITY(1,1) PRIMARY KEY,  
		MA_SAN_PHAM INT, 
		TEN_SAN_PHAM NVARCHAR(100), 
		TEN_DON_VI NVARCHAR(100), 
		GIA_BAN_1 FLOAT, 
		GIA_BAN_2 FLOAT, 
		GIA_BAN_3 FLOAT, 
		CHIEC_KHAU_1 FLOAT, 
		CHIEC_KHAU_2 FLOAT, 
		CHIEC_KHAU_3 FLOAT
	)
	
	SET @SO_LUONG_KHO = ISNULL((SELECT COUNT(MA_KHO) FROM KHO WHERE ACTIVE = 'A'),0);
	SET @I = 1;
	WHILE @I <= @SO_LUONG_KHO AND @I <=5
	BEGIN
		SET @COLUMN_NAME = '';
		SET @COLUMN_NAME = 'TON_KHO_' + CAST(@I AS VARCHAR)
		SET @DYN_SQL = 'ALTER TABLE #TEMP_TON_KHO ADD ' + @COLUMN_NAME +' FLOAT DEFAULT 0';
		EXEC(@DYN_SQL);
		SET @I = @I+1;
	END
	
	SET @DYN_SQL = 'ALTER TABLE #TEMP_TON_KHO ADD TOTAL FLOAT DEFAULT 0';
	EXEC(@DYN_SQL)	
	
	OPEN SAN_PHAM_MY_CURSOR 
		FETCH NEXT FROM SAN_PHAM_MY_CURSOR INTO @MA_SAN_PHAM ,@TEN_SAN_PHAM, @TEN_DON_VI, @GIA_BAN_1, @GIA_BAN_2, @GIA_BAN_3, @CHIEC_KHAU_1, @CHIEC_KHAU_2, @CHIEC_KHAU_3
		WHILE @@FETCH_STATUS = 0  
	BEGIN
		SET @SO_LUONG_TON = ISNULL(DBO.F_GET_TON_TOTAL(@MA_SAN_PHAM),0);
		INSERT INTO #TEMP_TON_KHO(MA_SAN_PHAM, TEN_SAN_PHAM, TEN_DON_VI, GIA_BAN_1, GIA_BAN_2, GIA_BAN_3, CHIEC_KHAU_1, CHIEC_KHAU_2, CHIEC_KHAU_3) 
		VALUES (@MA_SAN_PHAM, @TEN_SAN_PHAM, @TEN_DON_VI, @GIA_BAN_1, @GIA_BAN_2, @GIA_BAN_3, @CHIEC_KHAU_1, @CHIEC_KHAU_2, @CHIEC_KHAU_3);
		SET @ID = (SELECT SCOPE_IDENTITY());
		SET @DYN_SQL = 'UPDATE #TEMP_TON_KHO SET TOTAL  = ' + CAST(@SO_LUONG_TON AS VARCHAR)+ ' WHERE ID = ' + CAST(@ID AS VARCHAR);	
		EXEC(@DYN_SQL);		
		
		SET @I = 1;
		DECLARE KHO_CURSOR_IST CURSOR FOR
		SELECT MA_KHO 
		FROM KHO
		WHERE ACTIVE = 'A'
		ORDER BY MA_KHO; 
	
		OPEN KHO_CURSOR_IST 
		FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
		WHILE @@FETCH_STATUS = 0 AND @I <= 5
		BEGIN
			SET @COLUMN_NAME = '';
			SET @COLUMN_NAME = 'TON_KHO_' + CAST(@I AS VARCHAR);
			SET @SO_LUONG_TON = DBO.F_GET_TON_KHO(@MA_KHO, @MA_SAN_PHAM);
			SET @DYN_SQL = 'UPDATE #TEMP_TON_KHO SET ' + @COLUMN_NAME + ' = ' + CAST(@SO_LUONG_TON AS VARCHAR) + ' WHERE ID = ' + CAST(@ID AS VARCHAR);
			EXEC(@DYN_SQL);
			SET @I = @I+1;
			FETCH NEXT FROM KHO_CURSOR_IST INTO @MA_KHO
		END;					
		CLOSE KHO_CURSOR_IST;
		DEALLOCATE KHO_CURSOR_IST;
		FETCH NEXT FROM SAN_PHAM_MY_CURSOR INTO @MA_SAN_PHAM ,@TEN_SAN_PHAM, @TEN_DON_VI, @GIA_BAN_1, @GIA_BAN_2, @GIA_BAN_3, @CHIEC_KHAU_1, @CHIEC_KHAU_2, @CHIEC_KHAU_3
	END;
	CLOSE SAN_PHAM_MY_CURSOR
	DEALLOCATE SAN_PHAM_MY_CURSOR
	
	SELECT TOP 999
	#TEMP_TON_KHO.*
	FROM 
	#TEMP_TON_KHO
END


