ALTER PROCEDURE [dbo].[SP_GET_IMPORT_DETAIL_BY_ID_4_EDIT]
@MA_NHAP_KHO INT
AS
BEGIN
	SELECT 
		CHI_TIET_NHAP_KHO.MA_SAN_PHAM,
		SAN_PHAM.TEN_SAN_PHAM,
		CASE ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG_TEMP, 0) 
			WHEN 0 THEN CHI_TIET_NHAP_KHO.SO_LUONG
			ELSE CHI_TIET_NHAP_KHO.SO_LUONG_TEMP END AS SO_LUONG,
		CASE ISNULL(CHI_TIET_NHAP_KHO.DON_GIA_TEMP, 0) 
			WHEN 0 THEN  CHI_TIET_NHAP_KHO.GIA_VON
			ELSE CHI_TIET_NHAP_KHO.DON_GIA_TEMP END AS DON_GIA,
		CASE ISNULL(CHI_TIET_NHAP_KHO.MA_DON_VI,0)
			WHEN 0 THEN SAN_PHAM.MA_DON_VI
			ELSE CHI_TIET_NHAP_KHO.MA_DON_VI END AS MA_DON_VI, 
		DON_VI_TINH.TEN_DON_VI, 
		ISNULL(DBO.F_GET_CONVERTOR(CHI_TIET_NHAP_KHO.MA_SAN_PHAM,CHI_TIET_NHAP_KHO.MA_DON_VI),1) HE_SO
	FROM
		CHI_TIET_NHAP_KHO, 
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		CHI_TIET_NHAP_KHO.ACTIVE = 'A'
		AND CHI_TIET_NHAP_KHO.MA_NHAP_KHO = @MA_NHAP_KHO
		AND CHI_TIET_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND 
		(
			CHI_TIET_NHAP_KHO.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_NHAP_KHO.MA_DON_VI IS NOT NULL AND CHI_TIET_NHAP_KHO.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		) 
END
