ALTER PROCEDURE SP_GET_IMPORT
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_NHAN_VIEN_NHAP INT, 
@LY_DO_NHAP INT, 
@MA_KHO INT, 
@MA_NHA_CC INT
AS
BEGIN
	SELECT 
		NHAP_KHO.MA_NHAP_KHO, 
		NHAP_KHO.SO_HOA_DON, 
		NHAP_KHO.NGAY_NHAP, 
		NHAP_KHO.NHAN_VIEN_NHAP, 
		NHAP_KHO.MA_NHA_CUNG_CAP, 
		NHAP_KHO.MA_KHO, 
		NGUOI_DUNG.TEN_NGUOI_DUNG, 
		KHO.TEN_KHO, 
		NHA_CUNG_CAP.TEN_NHA_CUNG_CAP
	FROM 
		NHAP_KHO LEFT JOIN NHA_CUNG_CAP ON NHAP_KHO.MA_NHA_CUNG_CAP = NHA_CUNG_CAP.MA_NHA_CUNG_CAP,
		KHO, 
		NGUOI_DUNG
	WHERE
		NHAP_KHO.ACTIVE = 'A'
		AND(@FROM_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_NHAP AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAP = 0 OR NHAN_VIEN_NHAP = @MA_NHAN_VIEN_NHAP)
		AND (@LY_DO_NHAP = 0 OR LY_DO_NHAP = @LY_DO_NHAP)
		AND (@MA_KHO = 0 OR NHAP_KHO.MA_KHO = @MA_KHO)
		AND (@MA_NHA_CC = 0 OR NHAP_KHO.MA_NHA_CUNG_CAP = @MA_NHA_CC) 
		AND NHAP_KHO.MA_KHO = KHO.MA_KHO
		AND NHAP_KHO.NHAN_VIEN_NHAP = NGUOI_DUNG.MA_NGUOI_DUNG
END


CREATE VIEW V_IMPORT_DETAIL
AS
SELECT 
	CHI_TIET_NHAP_KHO.MA_NHAP_KHO,
	CHI_TIET_NHAP_KHO.MA_SAN_PHAM, 
	SAN_PHAM.TEN_SAN_PHAM,
	SAN_PHAM.MA_DON_VI,
	DON_VI_TINH.TEN_DON_VI,
	CHI_TIET_NHAP_KHO.SO_LUONG, 
	CHI_TIET_NHAP_KHO.GIA_VON
FROM
	CHI_TIET_NHAP_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
WHERE
	CHI_TIET_NHAP_KHO.ACTIVE = 'A'
	AND CHI_TIET_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI

CREATE PROCEDURE SP_GET_IMPORT_DETAIL_BY_ID
@IMPORT_ID INT
AS
BEGIN
	SELECT 
	MA_SAN_PHAM, 
	TEN_SAN_PHAM, 
	MA_DON_VI, 
	TEN_DON_VI, 
	SO_LUONG, 
	GIA_VON
	FROM 
	V_IMPORT_DETAIL
	WHERE 
	MA_NHAP_KHO = @IMPORT_ID
END