ALTER TABLE TRA_HANG
ADD MA_KHACH_HANG INT


ALTER PROCEDURE [dbo].[SP_GET_RETURN_INFO_BY_ID]
@MA_TRA_HANG INT
AS
BEGIN
	SELECT 
		TRA_HANG.MA_TRA_HANG,
		TRA_HANG.MA_KHACH_HANG,
		TRA_HANG.TEN_KHACH_HANG, 
		TRA_HANG.NGAY_TRA, 
		TRA_HANG.NHAN_VIEN_NHAN MA_NV_NHAN, 
		NGUOI_DUNG.TEN_NGUOI_DUNG,
		TRA_HANG.GHI_CHU, 
		TRA_HANG.MA_HOA_DON
	FROM
		TRA_HANG, 
		NGUOI_DUNG
	WHERE
		TRA_HANG.ACTIVE = 'A'
		AND TRA_HANG.MA_TRA_HANG = @MA_TRA_HANG
		AND TRA_HANG.NHAN_VIEN_NHAN = NGUOI_DUNG.MA_NGUOI_DUNG
END
