ALTER TABLE TRA_HANG
ADD
	IMPORT_FLG BIT, 
	RETURN_FLG BIT


ALTER PROCEDURE SP_GET_RETURN_LIST
@TEN_KHACH_HANG NVARCHAR(100), 
@FROM_DATE DATE, 
@TO_DATE DATE,
@MA_NHAN_VIEN_NHAN INT, 
@TEN_NHAN_VIEN NVARCHAR(100)
AS
BEGIN
	SELECT 
		TRA_HANG.MA_TRA_HANG, 
		TRA_HANG.TEN_KHACH_HANG, 
		TRA_HANG.NGAY_TRA, 
		TRA_HANG.STATUS,  
		TRA_HANG.NHAN_VIEN_NHAN,
		NGUOI_DUNG.TEN_NGUOI_DUNG
	FROM
		TRA_HANG, 
		NGUOI_DUNG
	WHERE
		TRA_HANG.ACTIVE = 'A'
		AND (TRA_HANG.IMPORT_FLG IS NULL OR TRA_HANG.IMPORT_FLG = 'TRUE')
		AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TRA_HANG.TEN_KHACH_HANG LIKE '%' +  @TEN_KHACH_HANG + '%')
		AND (@TEN_NHAN_VIEN IS NULL OR @TEN_NHAN_VIEN = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @TEN_NHAN_VIEN + '%')
		AND (@FROM_DATE IS NULL OR CAST(NGAY_TRA AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_TRA AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_NHAN = 0 OR TRA_HANG.NHAN_VIEN_NHAN = @MA_NHAN_VIEN_NHAN)
		AND TRA_HANG.NHAN_VIEN_NHAN = NGUOI_DUNG.MA_NGUOI_DUNG
END


CREATE PROCEDURE SP_GET_REFUND_DETAIL
@MA_TRA_HANG INT
AS
BEGIN
	SELECT 
	CHI_TIET_TRA_HANG.MA_TRA_HANG, 
	CHI_TIET_TRA_HANG.MA_SAN_PHAM, 
	ISNULL(CHI_TIET_TRA_HANG.SO_LUONG_TRA,0) SO_LUONG_TRA, 
	ISNULL(CHI_TIET_TRA_HANG.GIA_VON,0) GIA_VON,
	ISNULL(CHI_TIET_TRA_HANG.SO_LUONG_TRA, 0) * ISNULL(CHI_TIET_TRA_HANG.GIA_VON, 0) TONG_TIEN,
	SAN_PHAM.TEN_SAN_PHAM,
	DON_VI_TINH.TEN_DON_VI
	FROM 
	CHI_TIET_TRA_HANG, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE
	CHI_TIET_TRA_HANG.ACTIVE = 'A'
	AND CHI_TIET_TRA_HANG.MA_TRA_HANG = @MA_TRA_HANG
	AND CHI_TIET_TRA_HANG.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM 
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
END