ALTER PROCEDURE [dbo].[SP_GET_INVENTORY]
@MA_KHO INT,
@TEN_KHO NVARCHAR(200),
@GROUP_ID INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200)
AS
SELECT TOP 999
	SAN_PHAM.MA_SAN_PHAM, 
	SAN_PHAM.TEN_SAN_PHAM, 
	DON_VI_TINH.TEN_DON_VI,
	ISNULL(SUM(SO_LUONG_TON),0) SO_LUONG_TON,
	ISNULL(SUM(SO_LUONG_TON),0)*SAN_PHAM.GIA_BAN_1 VALUE
FROM
SAN_PHAM
LEFT JOIN V_NHAP_XUAT_KHO ON V_NHAP_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_XUAT_KHO.MA_KHO = @MA_KHO)
JOIN KHO ON V_NHAP_XUAT_KHO.MA_KHO = KHO.MA_KHO AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%' )
JOIN DON_VI_TINH ON SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
WHERE
SAN_PHAM.ACTIVE = 'A'
AND (@GROUP_ID = 0 OR SAN_PHAM.MA_NHOM = @GROUP_ID)
AND SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%'
GROUP BY SAN_PHAM.MA_SAN_PHAM,SAN_PHAM.TEN_SAN_PHAM, DON_VI_TINH.TEN_DON_VI,SAN_PHAM.GIA_BAN_1
ORDER BY SAN_PHAM.MA_SAN_PHAM

ALTER PROC [dbo].[SP_GET_VALUE_OF_INVENTORY]
@MA_KHO INT,
@TEN_KHO NVARCHAR(200),
@GROUP_ID INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200)
AS
SELECT 
ISNULL(SUM(VALUE),0) VALUE
FROM
(
	SELECT 
		ISNULL(SUM(SO_LUONG_TON),0)*SAN_PHAM.GIA_BAN_1 VALUE
	FROM
	SAN_PHAM
	LEFT JOIN V_NHAP_XUAT_KHO ON V_NHAP_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_NHAP_XUAT_KHO.MA_KHO = @MA_KHO)
	JOIN KHO ON V_NHAP_XUAT_KHO.MA_KHO = KHO.MA_KHO AND (@TEN_KHO IS NULL OR @TEN_KHO = '' OR UPPER(KHO.TEN_KHO) LIKE '%' + UPPER(@TEN_KHO) + '%')
	JOIN DON_VI_TINH ON SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	WHERE
	SAN_PHAM.ACTIVE = 'A'
	AND (@GROUP_ID = 0 OR SAN_PHAM.MA_NHOM = @GROUP_ID)
	AND SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%'
	GROUP BY SAN_PHAM.MA_SAN_PHAM,SAN_PHAM.TEN_SAN_PHAM, DON_VI_TINH.TEN_DON_VI,SAN_PHAM.GIA_BAN_1
)TEMP



CREATE FUNCTION F_GET_MIN_BY_STORE
(
	@STORE_ID INT, 
	@PRODUCT_ID INT
)RETURNS FLOAT
AS
BEGIN
	RETURN (SELECT TOP 1 ISNULL(CO_SO_TOI_THIEU,0) FROM TON_KHO_MIN_MAX_KHO
	WHERE ACTIVE = 'A' AND MA_KHO = @STORE_ID AND MA_SAN_PHAM = @PRODUCT_ID)
END



create PROC SP_GET_WARNING_BY_STORE
@STORE_ID INT, 
@PRODUCT_NAME NVARCHAR(100)
AS
BEGIN
	SELECT 
	SAN_PHAM.MA_SAN_PHAM,
	SAN_PHAM.TEN_SAN_PHAM,
	SAN_PHAM.CODE,
	SAN_PHAM.MA_DON_VI,
	DON_VI_TINH.TEN_DON_VI, 
	ISNULL(dbo.F_GET_TON_KHO(@STORE_ID,SAN_PHAM.MA_SAN_PHAM),0) INVENTORY, 
	ISNULL(dbo.F_GET_MIN_BY_STORE(@STORE_ID, SAN_PHAM.MA_SAN_PHAM),0) INVENTORY_MIN
	FROM 
	SAN_PHAM JOIN DON_VI_TINH ON SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	WHERE
	SAN_PHAM.ACTIVE = 'A'
	AND (@PRODUCT_NAME IS NULL OR @PRODUCT_NAME = '' OR UPPER(TEN_SAN_PHAM) LIKE '%' + UPPER(@PRODUCT_NAME) + '%')
	AND (dbo.F_GET_MIN_BY_STORE(@STORE_ID, SAN_PHAM.MA_SAN_PHAM) >= dbo.F_GET_TON_KHO(@STORE_ID,SAN_PHAM.MA_SAN_PHAM))
END


CREATE PROCEDURE SP_GET_EXPENSES
@KIND INT, 
@RECIVER NVARCHAR(100), 
@USR_ID INT, 
@USER_NAME NVARCHAR(100), 
@TOTAL_FROM FLOAT, 
@TOTAL_TO FLOAT, 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		EXPENSES.ID, 
		ISNULL(EXPENSES.LOAI_CHI,0)  LOAI_CHI,
		EXPENSES.NGUOI_CHI, 
		NGUOI_DUNG.TEN_NGUOI_DUNG,
		EXPENSES.TEN_NGUOI_NHAN,
		EXPENSES.NGAY_CHI, 
		ISNULL(EXPENSES.TONG_CHI,0) TONG_CHI, 
		EXPENSES.GHI_CHU
	FROM
	EXPENSES, 
	NGUOI_DUNG
	WHERE 
	EXPENSES.ACTIVE = 'A'
	AND (@KIND =0 OR EXPENSES.LOAI_CHI = @KIND)
	AND (@RECIVER IS NULL OR @RECIVER = '' OR UPPER(EXPENSES.TEN_NGUOI_NHAN) LIKE '%' + UPPER(@RECIVER) + '%')
	AND (@USR_ID = 0 OR EXPENSES.NGUOI_CHI = @USR_ID)
	AND (@USER_NAME IS NULL OR @USER_NAME = '' OR UPPER(NGUOI_DUNG.TEN_NGUOI_DUNG) LIKE '%' + UPPER(@USER_NAME) + '%')
	AND EXPENSES.TONG_CHI BETWEEN @TOTAL_FROM AND @TOTAL_TO
	AND (@FROM_DATE IS NULL OR CAST(EXPENSES.NGAY_CHI AS DATE) >= CAST(@FROM_DATE AS DATE))
	AND (@TO_DATE IS NULL OR  CAST(EXPENSES.NGAY_CHI AS DATE) <= CAST(@TO_DATE AS DATE))  
	AND EXPENSES.NGUOI_CHI = NGUOI_DUNG.MA_NGUOI_DUNG
END

ALTER PROCEDURE [dbo].[SP_GET_EXPENSES]
@KIND INT, 
@RECIVER NVARCHAR(100), 
@USR_ID INT, 
@USER_NAME NVARCHAR(100), 
@TOTAL_FROM FLOAT, 
@TOTAL_TO FLOAT, 
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		EXPENSES.ID, 
		ISNULL(EXPENSES.LOAI_CHI,0)  LOAI_CHI,
		EXPENSES.NGUOI_CHI, 
		NGUOI_DUNG.TEN_NGUOI_DUNG,
		EXPENSES.TEN_NGUOI_NHAN,
		EXPENSES.NGAY_CHI, 
		ISNULL(EXPENSES.TONG_CHI,0) TONG_CHI, 
		EXPENSES.GHI_CHU
	FROM
	EXPENSES, 
	NGUOI_DUNG
	WHERE 
	EXPENSES.ACTIVE = 'A'
	AND (@KIND =0 OR EXPENSES.LOAI_CHI = @KIND)
	AND (@RECIVER IS NULL OR @RECIVER = '' OR UPPER(EXPENSES.TEN_NGUOI_NHAN) LIKE '%' + UPPER(@RECIVER) + '%')
	AND (@USR_ID = 0 OR EXPENSES.NGUOI_CHI = @USR_ID)
	AND (@USER_NAME IS NULL OR @USER_NAME = '' OR UPPER(NGUOI_DUNG.TEN_NGUOI_DUNG) LIKE '%' + UPPER(@USER_NAME) + '%')
	AND (@TOTAL_FROM IS NULL OR @TOTAL_FROM = 0 OR EXPENSES.TONG_CHI >= @TOTAL_FROM)
	AND (@TOTAL_TO IS NULL OR @TOTAL_TO = 0 OR  EXPENSES.TONG_CHI <= @TOTAL_TO)
	AND (@FROM_DATE IS NULL OR CAST(EXPENSES.NGAY_CHI AS DATE) >= CAST(@FROM_DATE AS DATE))
	AND (@TO_DATE IS NULL OR  CAST(EXPENSES.NGAY_CHI AS DATE) <= CAST(@TO_DATE AS DATE))  
	AND EXPENSES.NGUOI_CHI = NGUOI_DUNG.MA_NGUOI_DUNG
END

