ALTER TABLE CHUYEN_DOI_DON_VI_TINH
ADD
	GIA_BAN_1 FLOAT, 
	GIA_BAN_2 FLOAT, 
	GIA_BAN_3 FLOAT, 
	CHIEC_KHAU_1 FLOAT, 
	CHIEC_KHAU_2 FLOAT, 
	CHIEC_KHAU_3 FLOAT

ALTER TABLE CHI_TIET_HOA_DON
ADD	
	DON_GIA_TEMP FLOAT, 
	SO_LUONG_TEMP FLOAT, 
	MA_DON_VI INT
	
ALTER PROCEDURE [dbo].[SP_GET_DON_VI_TINH]
@MA_SAN_PHAM INT
AS
BEGIN
	SELECT 
		MA_SAN_PHAM,
		SAN_PHAM.MA_DON_VI, 
		TEN_DON_VI,
		1 AS HE_SO, 
		GIA_BAN_1, 
		GIA_BAN_2, 
		GIA_BAN_3, 
		CHIEC_KHAU_1, 
		CHIEC_KHAU_2, 
		CHIEC_KHAU_3
	FROM 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
	SAN_PHAM.ACTIVE = 'A' AND MA_SAN_PHAM = @MA_SAN_PHAM
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	UNION 
	SELECT 
		MA_SAN_PHAN MA_SAN_PHAM, 
		MA_DON_VI_VAO MA_DON_VI, 
		TEN_DON_VI,
		HE_SO, 
		GIA_BAN_1, 
		GIA_BAN_2, 
		GIA_BAN_3, 
		CHIEC_KHAU_1, 
		CHIEC_KHAU_2, 
		CHIEC_KHAU_3
	FROM 
	CHUYEN_DOI_DON_VI_TINH, 
	DON_VI_TINH
	WHERE 
	CHUYEN_DOI_DON_VI_TINH.ACTIVE = 'A' AND MA_SAN_PHAN = @MA_SAN_PHAM
	AND CHUYEN_DOI_DON_VI_TINH.MA_DON_VI_VAO = DON_VI_TINH.MA_DON_VI 
END

CREATE PROCEDURE SP_GET_PRICE_BY_UNIT
@MA_SAN_PHAM INT,
@MA_DON_VI INT
AS
BEGIN
	SELECT 
		MA_SAN_PHAM,
		SAN_PHAM.MA_DON_VI, 
		TEN_DON_VI,
		1 AS HE_SO, 
		GIA_BAN_1, 
		GIA_BAN_2, 
		GIA_BAN_3, 
		CHIEC_KHAU_1, 
		CHIEC_KHAU_2, 
		CHIEC_KHAU_3
	FROM 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
	SAN_PHAM.ACTIVE = 'A' AND MA_SAN_PHAM = @MA_SAN_PHAM
	AND SAN_PHAM.MA_DON_VI = @MA_DON_VI
	AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	UNION 
	SELECT 
		MA_SAN_PHAN MA_SAN_PHAM, 
		MA_DON_VI_VAO MA_DON_VI, 
		TEN_DON_VI,
		HE_SO, 
		GIA_BAN_1, 
		GIA_BAN_2, 
		GIA_BAN_3, 
		CHIEC_KHAU_1, 
		CHIEC_KHAU_2, 
		CHIEC_KHAU_3
	FROM 
	CHUYEN_DOI_DON_VI_TINH, 
	DON_VI_TINH
	WHERE 
	CHUYEN_DOI_DON_VI_TINH.ACTIVE = 'A' AND MA_SAN_PHAN = @MA_SAN_PHAM
	AND CHUYEN_DOI_DON_VI_TINH.MA_DON_VI_VAO = @MA_DON_VI
	AND CHUYEN_DOI_DON_VI_TINH.MA_DON_VI_VAO = DON_VI_TINH.MA_DON_VI 
END


ALTER PROCEDURE [dbo].[SP_GET_IMPORT_DETAIL_BY_ID_4_EDIT]
@MA_NHAP_KHO INT
AS
BEGIN
	SELECT 
		SAN_PHAM.CODE,
		CHI_TIET_NHAP_KHO.MA_SAN_PHAM,
		SAN_PHAM.TEN_SAN_PHAM,
		CASE ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG_TEMP, 0) 
			WHEN 0 THEN CHI_TIET_NHAP_KHO.SO_LUONG
			ELSE CHI_TIET_NHAP_KHO.SO_LUONG_TEMP END AS SO_LUONG,
		CASE ISNULL(CHI_TIET_NHAP_KHO.DON_GIA_TEMP, 0) 
			WHEN 0 THEN  CHI_TIET_NHAP_KHO.GIA_VON
			ELSE CHI_TIET_NHAP_KHO.DON_GIA_TEMP END AS DON_GIA,
		CASE ISNULL(CHI_TIET_NHAP_KHO.MA_DON_VI,0)
			WHEN 0 THEN SAN_PHAM.MA_DON_VI
			ELSE CHI_TIET_NHAP_KHO.MA_DON_VI END AS MA_DON_VI, 
		DON_VI_TINH.TEN_DON_VI, 
		ISNULL(DBO.F_GET_CONVERTOR(CHI_TIET_NHAP_KHO.MA_SAN_PHAM,CHI_TIET_NHAP_KHO.MA_DON_VI),1) HE_SO
	FROM
		CHI_TIET_NHAP_KHO, 
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		CHI_TIET_NHAP_KHO.ACTIVE = 'A'
		AND CHI_TIET_NHAP_KHO.MA_NHAP_KHO = @MA_NHAP_KHO
		AND CHI_TIET_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND 
		(
			CHI_TIET_NHAP_KHO.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_NHAP_KHO.MA_DON_VI IS NOT NULL AND CHI_TIET_NHAP_KHO.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		) 
END

ALTER PROCEDURE [dbo].[SP_GET_IMPORT_DETAIL_BY_ID]
@IMPORT_ID INT
AS
BEGIN
	SELECT 
	MA_SAN_PHAM, 
	TEN_SAN_PHAM, 
	MA_DON_VI, 
	TEN_DON_VI, 
	SO_LUONG, 
	GIA_VON
	FROM 
	V_IMPORT_DETAIL
	WHERE 
	MA_NHAP_KHO = @IMPORT_ID
END


exec SP_GET_IMPORT_DETAIL_BY_ID_4_EDIT 3