ALTER VIEW [dbo].[V_RETURN_2_PROVIDER]
AS
SELECT 
TRA_HANG_NCC.ID,
TRA_HANG_NCC.MA_NHA_CUNG_CAP,
TRA_HANG_NCC.MA_PHIEU_TRA,
TRA_HANG_NCC.NGAY_LAP_PHIEU,
TRA_HANG_NCC.NGUOI_LAP_PHIEU MA_NV_LAP_PHIEU,
TRA_HANG_NCC.GHI_CHU,
TRA_HANG_NCC_CHI_TIET.MA_SAN_PHAM,
TRA_HANG_NCC_CHI_TIET.SO_LUONG,
TRA_HANG_NCC_CHI_TIET.DON_GIA,
TRA_HANG_NCC_CHI_TIET.MA_KHO_XUAT,
TRA_HANG_NCC_CHI_TIET.SO_LUONG_TEMP,
TRA_HANG_NCC_CHI_TIET.MA_DON_VI,
TRA_HANG_NCC_CHI_TIET.DON_GIA_TEMP
FROM 
TRA_HANG_NCC,-- LEFT JOIN XUAT_KHO ON TRA_HANG_NCC.ID = XUAT_KHO.MA_PHIEU_TRA_NCC AND XUAT_KHO.ACTIVE = 'A',
TRA_HANG_NCC_CHI_TIET, 
XUAT_KHO
WHERE
TRA_HANG_NCC.ACTIVE = 'A'
AND TRA_HANG_NCC_CHI_TIET.ACTIVE = 'A'
AND (
	(TRA_HANG_NCC.MA_PHIEU_TRA IS NULL AND TRA_HANG_NCC.ID = XUAT_KHO.MA_PHIEU_TRA_NCC AND XUAT_KHO.ACTIVE = 'A')
	OR
	(TRA_HANG_NCC.MA_PHIEU_TRA IS NOT NULL)
	)
AND TRA_HANG_NCC.ID = TRA_HANG_NCC_CHI_TIET.MA_PHIEU_TRA_NCC
GO



CREATE PROCEDURE SP_GET_REPORT_RETURN_2_PROVIDER
@PROVIDER_ID INT, 
@PROVIDER_NAME NVARCHAR(100), 
@FROM_DATE DATE, 
@TO_DATE DATE, 
AS
BEGIN
	SELECT 
		V_RETURN_2_PROVIDER.ID, 
		V_RETURN_2_PROVIDER.MA_NHA_CUNG_CAP, 
		NHA_CUNG_CAP.TEN_NHA_CUNG_CAP,
		V_RETURN_2_PROVIDER.NGAY_LAP_PHIEU, 
		NGUOI_DUNG.TEN_NGUOI_DUNG,
		ISNULL(SUM(V_RETURN_2_PROVIDER.SO_LUONG*ISNULL(V_RETURN_2_PROVIDER.DON_GIA,0)),0) TOTAL
	FROM 
	V_RETURN_2_PROVIDER, 
	NHA_CUNG_CAP, 
	NGUOI_DUNG
	WHERE
	(@PROVIDER_ID = 0 OR V_RETURN_2_PROVIDER.MA_NHA_CUNG_CAP = @PROVIDER_ID)
	AND (@PROVIDER_NAME IS NULL OR @PROVIDER_NAME = '' OR NHA_CUNG_CAP.TEN_NHA_CUNG_CAP LIKE '%' + @PROVIDER_NAME + '%')
	AND (@FROM_DATE IS NULL OR CAST(V_RETURN_2_PROVIDER.NGAY_LAP_PHIEU AS DATE) >= CAST(@FROM_DATE AS DATE))
	AND (@TO_DATE IS NULL OR CAST(V_RETURN_2_PROVIDER.NGAY_LAP_PHIEU AS DATE) <= CAST(@TO_DATE AS DATE))
	AND V_RETURN_2_PROVIDER.MA_NHA_CUNG_CAP = NHA_CUNG_CAP.MA_NHA_CUNG_CAP
	AND V_RETURN_2_PROVIDER.MA_NV_LAP_PHIEU = NGUOI_DUNG.MA_NGUOI_DUNG
	GROUP BY 
	V_RETURN_2_PROVIDER.ID, 
	V_RETURN_2_PROVIDER.MA_NHA_CUNG_CAP, 
	NHA_CUNG_CAP.TEN_NHA_CUNG_CAP,
	V_RETURN_2_PROVIDER.NGAY_LAP_PHIEU, 
	NGUOI_DUNG.TEN_NGUOI_DUNG
END

ALTER PROCEDURE SP_GET_REPORT_DEBT_COLLECTION
@CUSTOMER_ID INT, 
@CUSTOMER_NAME NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN 
	SELECT 
		KHACH_HANG_DEBIT_HIST.ID,
		KHACH_HANG_DEBIT_HIST.MA_KHACH_HANG, 
		KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH, 
		ISNULL(KHACH_HANG_DEBIT_HIST.PHAT_SINH,0) PHAT_SINH,
		KHACH_HANG.TEN_KHACH_HANG
	FROM
		KHACH_HANG_DEBIT_HIST, 
		KHACH_HANG
	WHERE 
		KHACH_HANG_DEBIT_HIST.ACTIVE = 'A'
		AND KHACH_HANG_DEBIT_HIST.PHAT_SINH >0
		AND (@FROM_DATE IS NULL OR CAST(KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@CUSTOMER_ID = 0 OR KHACH_HANG_DEBIT_HIST.MA_KHACH_HANG = @CUSTOMER_ID)
		AND (@CUSTOMER_NAME IS NULL OR @CUSTOMER_NAME = '' OR UPPER(KHACH_HANG.TEN_KHACH_HANG) LIKE '%' + UPPER(@CUSTOMER_NAME) + '%')
		AND KHACH_HANG_DEBIT_HIST.MA_KHACH_HANG = KHACH_HANG.MA_KHACH_HANG
END



