CREATE FUNCTION GET_TOTAL_AMOUNT(@MA_HOA_DON INT)
RETURNS FLOAT
BEGIN
	RETURN (
		SELECT
			ISNULL(SUM(AMOUNT),0)
		FROM
			(	
				 SELECT 
				 MA_HOA_DON,
				 SO_LUONG, 
				 DON_GIA, 
				 SO_LUONG*DON_GIA AMOUNT
				 FROM 
				 CHI_TIET_HOA_DON
				 WHERE
				 ACTIVE = 'A'
				 AND MA_HOA_DON = @MA_HOA_DON
			)TEMP
			GROUP BY MA_HOA_DON
		)
END

CREATE FUNCTION GET_TOTAL_DISCOUNT(@MA_HOA_DON INT)
RETURNS FLOAT
BEGIN
	RETURN (
		SELECT
			ISNULL(SUM(DISCOUNT),0)
		FROM
			(	
				 SELECT 
				 MA_HOA_DON,
				 SO_LUONG*DON_GIA*PHAN_TRAM_CHIEC_KHAU/100 DISCOUNT
				 FROM 
				 CHI_TIET_HOA_DON
				 WHERE
				 ACTIVE = 'A'
				 AND MA_HOA_DON = @MA_HOA_DON
			)TEMP
			GROUP BY MA_HOA_DON
		)
END

CREATE PROC GET_HOA_DON 
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_KHACH_HANG INT
AS
BEGIN
	 SELECT 
	 MA_HOA_DON, 
	 SO_HOA_DON, 
	 ISNULL(DBO.GET_TOTAL_AMOUNT(MA_HOA_DON),0)  AMOUNT, 
	 ISNULL(DBO.GET_TOTAL_DISCOUNT(MA_HOA_DON),0)  DISCOUNT, 
	 ISNULL(DBO.GET_TOTAL_AMOUNT(MA_HOA_DON),0) - ISNULL(DBO.GET_TOTAL_DISCOUNT(MA_HOA_DON),0) REAL_AMOUNT,
	 NGAY_BAN
	 FROM 
	 HOA_DON
	 WHERE 
	 ACTIVE = 'A'
	 AND MA_KHACH_HANG = @MA_KHACH_HANG
	 AND STATUS >=2
	 AND CAST(NGAY_BAN AS DATE) BETWEEN CAST(@FROM_DATE AS DATE) AND CAST(@TO_DATE AS DATE)
END


CREATE PROC GET_SUM_HOA_DON_BY_CUS_ID
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_KHACH_HANG INT
AS
BEGIN
	SELECT 
		ISNULL(SUM(AMOUNT),0) TOTAL_AMOUNT, 
		ISNULL(SUM(DISCOUNT),0) TOTAL_DISCOUNT, 
		ISNULL(SUM(REAL_AMOUNT),0) TOTAL_REAL_AMOUNT
	FROM 
	(
		 SELECT 
		 ISNULL(DBO.GET_TOTAL_AMOUNT(MA_HOA_DON),0)  AMOUNT, 
		 ISNULL(DBO.GET_TOTAL_DISCOUNT(MA_HOA_DON),0)  DISCOUNT, 
		 ISNULL(DBO.GET_TOTAL_AMOUNT(MA_HOA_DON),0) - ISNULL(DBO.GET_TOTAL_DISCOUNT(MA_HOA_DON),0) REAL_AMOUNT,
		 NGAY_BAN
		 FROM 
		 HOA_DON
		 WHERE 
		 ACTIVE = 'A'
		 AND MA_KHACH_HANG = @MA_KHACH_HANG
		 AND STATUS >=2
		 AND CAST(NGAY_BAN AS DATE) BETWEEN CAST(@FROM_DATE AS DATE) AND CAST(@TO_DATE AS DATE)
	 )TEMP
END

ALTER TABLE HOA_DON
ADD
SO_TIEN_KHACH_TRA FLOAT, 
SO_TIEN_NO_GOI_DAU FLOAT

ALTER TABLE KHACH_HANG_DEBIT_HIST
ADD MA_HOA_DON INT FOREIGN KEY REFERENCES HOA_DON(MA_HOA_DON)


INSERT INTO SMS_MASTER
(
	NAME, 
	VALUE, 
	GHI_CHU, 
	CREATE_BY, 
	UPDATE_BY, 
	CREATE_AT, 
	UPDATE_AT, 
	ACTIVE
)
VALUES
(
	'MAX_DEBIT_KIND_1', 
	'100000000', 
	NULL, 
	1, 
	1, 
	GETDATE(), 
	GETDATE(),
	'A'
)


INSERT INTO SMS_MASTER
(
	NAME, 
	VALUE, 
	GHI_CHU, 
	CREATE_BY, 
	UPDATE_BY, 
	CREATE_AT, 
	UPDATE_AT, 
	ACTIVE
)
VALUES
(
	'MAX_DEBIT_KIND_2', 
	'50000000', 
	NULL, 
	1, 
	1, 
	GETDATE(), 
	GETDATE(),
	'A'
)

INSERT INTO SMS_MASTER
(
	NAME, 
	VALUE, 
	GHI_CHU, 
	CREATE_BY, 
	UPDATE_BY, 
	CREATE_AT, 
	UPDATE_AT, 
	ACTIVE
)
VALUES
(
	'MAX_DEBIT_KIND_3', 
	'10000000', 
	NULL, 
	1, 
	1, 
	GETDATE(), 
	GETDATE(),
	'A'
)


INSERT INTO SMS_MASTER
(
	NAME, 
	VALUE, 
	GHI_CHU, 
	CREATE_BY, 
	UPDATE_BY, 
	CREATE_AT, 
	UPDATE_AT, 
	ACTIVE
)
VALUES
(
	'MAX_MOUNTH_KIND_1', 
	'3', 
	NULL, 
	1, 
	1, 
	GETDATE(), 
	GETDATE(),
	'A'
)


INSERT INTO SMS_MASTER
(
	NAME, 
	VALUE, 
	GHI_CHU, 
	CREATE_BY, 
	UPDATE_BY, 
	CREATE_AT, 
	UPDATE_AT, 
	ACTIVE
)
VALUES
(
	'MAX_MOUNTH_KIND_2', 
	'2', 
	NULL, 
	1, 
	1, 
	GETDATE(), 
	GETDATE(),
	'A'
)

INSERT INTO SMS_MASTER
(
	NAME, 
	VALUE, 
	GHI_CHU, 
	CREATE_BY, 
	UPDATE_BY, 
	CREATE_AT, 
	UPDATE_AT, 
	ACTIVE
)
VALUES
(
	'MAX_MOUNTH_KIND_3', 
	'1', 
	NULL, 
	1, 
	1, 
	GETDATE(), 
	GETDATE(),
	'A'
)