CREATE TABLE SMS_MESSAGES
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	ID_NGUOI_GUI INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	ID_NHOM_NGUOI_NHAN  INT FOREIGN KEY REFERENCES NHOM_NGUOI_DUNG(MA_NHOM), 
	NGAY_GUI DATE, 
	NOI_DUNG NTEXT,
	CREATE_BY INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG), 
	UPDATE_BY  INT FOREIGN KEY REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),  
	CREATE_AT DATE, 
	UPDATE_AT DATE,
	ACTIVE CHAR(1)
) 

CREATE PROCEDURE SP_GET_HOA_DON_CHUA_TT
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_KHACH_HANG INT, 
@TEN_KHACH_HANG NVARCHAR(100),
@MA_NHAN_VIEN_BAN INT, 
@TEN_NV_BAN NVARCHAR(100),
@MA_NHAN_VIEN_TT INT, 
@TEN_NV_TT NVARCHAR(100)
AS
SELECT 
MA_HOA_DON, 
SO_HOA_DON, 
MA_KHACH_HANG, 
TEN_KHACH_HANG, 
MA_NHAN_VIEN_BAN,
TEN_NHAN_VIEN_BAN, 
NGAY_BAN, 
NGAY_GIAO, 
DIA_CHI_GIAO_HANG,
ISNULL(SUM(SO_LUONG*DON_GIA),0) TONG_TIEN
ISNULL(SUM(SO_LUONG*DON_GIA*PHAN_TRAM_CHIEC_KHAU/100),0) CHIEC_KHAU,
ISNULL(SUM(SO_LUONG*DON_GIA),0) -  ISNULL(SUM(SO_LUONG*DON_GIA*PHAN_TRAM_CHIEC_KHAU/100),0) THUC_THU
FROM
V_HOA_DON
WHERE
STATUS = 1
AND (@MA_KHACH_HANG = 0 OR MA_KHACH_HANG = @MA_KHACH_HANG)
AND (@TEN_KHACH_HANG IS NULL OR @TEN_KHACH_HANG = '' OR TEN_KHACH_HANG LIKE '%' + @TEN_KHACH_HANG + '%')
AND (@MA_NHAN_VIEN_BAN = 0 OR MA_NHAN_VIEN_BAN = @MA_NHAN_VIEN_BAN)
AND (@TEN_NV_BAN IS NULL OR @TEN_NV_BAN = '' OR TEN_NHAN_VIEN_BAN LIKE '%' + @TEN_NV_BAN + '%')
AND (@MA_NHAN_VIEN_TT = 0 OR MA_NHAN_VIEN_THU_TIEN = @MA_NHAN_VIEN_TT)
AND (@TEN_NV_TT IS NULL OR @TEN_NV_TT = '' OR TEN_NV_THU_TIEN LIKE '%' + @TEN_NV_TT + '%')
AND (@FROM_DATE IS NULL OR CAST(NGAY_BAN AS DATE) >= CAST(@FROM_DATE AS DATE))
AND (@TO_DATE IS NULL OR CAST(NGAY_BAN AS DATE) <= CAST(@TO_DATE AS DATE))
GROUP BY 
MA_HOA_DON, 
SO_HOA_DON, 
MA_KHACH_HANG, 
TEN_KHACH_HANG, 
MA_NHAN_VIEN_BAN,
TEN_NHAN_VIEN_BAN, 
NGAY_BAN, 
NGAY_GIAO, 
DIA_CHI_GIAO_HANG
