ALTER TABLE CHI_TIET_TRA_HANG
ADD PHAN_TRAM_KHAU_HAO FLOAT

ALTER PROCEDURE [dbo].[SP_GET_RETURN_DETAIL_BY_ID]
@MA_TRA_HANG INT
AS
BEGIN
	SELECT 
		CHI_TIET_TRA_HANG.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM,
		SAN_PHAM.CODE,
		ISNULL(CHI_TIET_TRA_HANG.GIA_BAN, 0) GIA_BAN,
		CASE ISNULL(CHI_TIET_TRA_HANG.DON_GIA_TEMP, 0) 
		WHEN 0 THEN CHI_TIET_TRA_HANG.GIA_VON
		ELSE CHI_TIET_TRA_HANG.DON_GIA_TEMP
		END AS DON_GIA,
		CASE ISNULL(CHI_TIET_TRA_HANG.MA_DON_VI,0)
		WHEN 0 THEN
			SAN_PHAM.MA_DON_VI
		ELSE CHI_TIET_TRA_HANG.MA_DON_VI
		END AS MA_DON_VI,
		DON_VI_TINH.TEN_DON_VI,
		CASE ISNULL(CHI_TIET_TRA_HANG.SO_LUONG_TEMP,0)
		WHEN 0 THEN
			CHI_TIET_TRA_HANG.SO_LUONG_TRA
		ELSE CHI_TIET_TRA_HANG.SO_LUONG_TEMP
		END AS SO_LUONG, 
		ISNULL(DBO.F_GET_CONVERTOR(CHI_TIET_TRA_HANG.MA_SAN_PHAM,CHI_TIET_TRA_HANG.MA_DON_VI),1) HE_SO, 
		CHI_TIET_TRA_HANG.PHAN_TRAM_KHAU_HAO
	FROM 
		CHI_TIET_TRA_HANG, 
		SAN_PHAM, 
		DON_VI_TINH
	WHERE
		CHI_TIET_TRA_HANG.ACTIVE = 'A'
		AND CHI_TIET_TRA_HANG.MA_TRA_HANG = @MA_TRA_HANG
		AND CHI_TIET_TRA_HANG.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND 
		(
			CHI_TIET_TRA_HANG.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_TRA_HANG.MA_DON_VI IS NOT NULL AND CHI_TIET_TRA_HANG.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		)
END


ALTER VIEW [dbo].[V_TRA_HANG]
AS
SELECT 
	TRA_HANG.MA_TRA_HANG, 
	TRA_HANG.MA_KHACH_HANG,
	TRA_HANG.TEN_KHACH_HANG, 
	TRA_HANG.NGAY_TRA, 
	TRA_HANG.NHAN_VIEN_NHAN MA_NGUOI_NHAN,
	SUM(ISNULL(CHI_TIET_TRA_HANG.SO_LUONG_TRA,0)*ISNULL(CHI_TIET_TRA_HANG.GIA_VON,0))*(100 - ISNULL(CHI_TIET_TRA_HANG.PHAN_TRAM_KHAU_HAO,0))/100 TOTAL
FROM 
TRA_HANG, 
CHI_TIET_TRA_HANG
WHERE
TRA_HANG.ACTIVE = 'A'
AND TRA_HANG.MA_TRA_HANG = CHI_TIET_TRA_HANG.MA_TRA_HANG
GROUP BY 
TRA_HANG.MA_TRA_HANG, 
TRA_HANG.MA_KHACH_HANG,
TRA_HANG.TEN_KHACH_HANG, 
TRA_HANG.NGAY_TRA, 
TRA_HANG.NHAN_VIEN_NHAN, 
CHI_TIET_TRA_HANG.PHAN_TRAM_KHAU_HAO
GO


SELECT 
ISNULL(SUM(SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA,
ISNULL(SUM(SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
ISNULL(SUM(TOTAL),0) BUGET_TOTAL, 
ISNULL(SUM(RETURN_TOTAL),0) RETURN_TOTAL,
ISNULL(SUM(TONG_CHI),0) TONG_CHI,
ISNULL(SUM(TONG_NHAP),0) TONG_NHAP,
ISNULL(SUM(TONG_PHAT_SINH),0) TONG_THU_NO,
ISNULL(SUM(ISNULL(TEMP.SO_TIEN_KHACH_TRA,0) 
	- ISNULL(TEMP.RETURN_TOTAL,0) 
	+ ISNULL(TEMP.TONG_PHAT_SINH,0) 
	- ISNULL(TEMP.TONG_CHI,0) 
	- ISNULL(TEMP.TONG_NHAP,0)),0) AS TOTAL,
NGAY_BAN DAY
FROM
(
	SELECT 
	ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) SO_TIEN_KHACH_TRA, 
	ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) SO_TIEN_NO_GOI_DAU,
	ISNULL(SUM(HOA_DON.SO_TIEN_KHACH_TRA),0) + ISNULL(SUM(HOA_DON.SO_TIEN_NO_GOI_DAU),0) TOTAL,
	0 AS RETURN_TOTAL,
	0 AS TONG_CHI,
	0 AS TONG_NHAP,
	0 AS TONG_PHAT_SINH,
	
	HOA_DON.NGAY_BAN
	FROM
	HOA_DON
	WHERE 
	ACTIVE = 'A'
	GROUP BY 
	HOA_DON.NGAY_BAN

	UNION ALL

	SELECT
	0 AS SO_TIEN_KHACH_TRA, 
	0 AS SO_TIEN_NO_GOI_DAU, 
	0 AS TOTAL,
	SUM(ISNULL(V_TRA_HANG.TOTAL,0)) RETURN_TOTAL,
	0 AS TONG_CHI,
	0 AS TONG_NHAP,
	0 AS TONG_PHAT_SINH,
	V_TRA_HANG.NGAY_TRA
	FROM 
	V_TRA_HANG
	GROUP BY 
	V_TRA_HANG.NGAY_TRA

	UNION ALL

	SELECT 
	0 AS SO_TIEN_KHACH_TRA, 
	0 AS SO_TIEN_NO_GOI_DAU, 
	0 AS TOTAL,
	0 AS RETURN_TOTAL,
	ISNULL(SUM(EXPENSES.TONG_CHI),0) TONG_CHI, 
	0 AS TONG_NHAP,
	0 AS TONG_PHAT_SINH,
	EXPENSES.NGAY_CHI
	FROM
	EXPENSES
	WHERE ACTIVE = 'A'
	GROUP BY EXPENSES.NGAY_CHI

	UNION ALL

	SELECT 
	0 AS SO_TIEN_KHACH_TRA, 
	0 AS SO_TIEN_NO_GOI_DAU, 
	0 AS TOTAL,
	0 RETURN_TOTAL,
	0 AS TONG_CHI,
	ISNULL(SUM(ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG,0)* ISNULL(CHI_TIET_NHAP_KHO.GIA_VON,0)),0) TONG_NHAP, 
	0 AS TONG_PHAT_SINH,
	NHAP_KHO.NGAY_NHAP
	FROM
	NHAP_KHO, 
	CHI_TIET_NHAP_KHO
	WHERE
	NHAP_KHO.ACTIVE = 'A'
	AND CHI_TIET_NHAP_KHO.ACTIVE = 'A'
	AND NHAP_KHO.LY_DO_NHAP = 0 
	AND NHAP_KHO.MA_NHAP_KHO = CHI_TIET_NHAP_KHO.MA_NHAP_KHO
	AND NHAP_KHO.NGAY_NHAP IS NOT NULL
	GROUP BY NHAP_KHO.NGAY_NHAP
	HAVING ISNULL(SUM(ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG,0)* ISNULL(CHI_TIET_NHAP_KHO.GIA_VON,0)),0) > 0

	UNION ALL

	SELECT 
	0 AS SO_TIEN_KHACH_TRA, 
	0 AS SO_TIEN_NO_GOI_DAU, 
	0 AS TOTAL,
	0 RETURN_TOTAL,
	0 AS TONG_CHI,
	0 AS TONG_NHAP,
	ISNULL(SUM(KHACH_HANG_DEBIT_HIST.PHAT_SINH),0) TONG_PHAT_SINH,
	KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH
	FROM
	KHACH_HANG_DEBIT_HIST
	WHERE
	ACTIVE = 'A'
	AND PHAT_SINH > 0
	GROUP BY KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH
)TEMP
GROUP BY NGAY_BAN
