CREATE PROCEDURE SP_THU_TIEN_XUAT_KHO
@MA_HOA_DON INT, 
@MA_NHAN_VIEN_THUC_HIEN INT, 
@SO_TIEN_KHACH_TRA FLOAT, 
@RETURN_VALUE INT OUTPUT
AS
BEGIN
	DECLARE  @TON_KHO FLOAT;
	DECLARE  @MA_KHO INT;
	DECLARE  @MA_KHO_NEXT INT;
	DECLARE  @MA_KHACH_HANG INT;
	DECLARE  @MA_XUAT_KHO INT;
	DECLARE  @TONG_TIEN FLOAT;
	DECLARE  @SO_TIEN_KHACH_NO FLOAT;
	
	SELECT 
		@MA_KHACH_HANG = MA_KHACH_HANG
	FROM HOA_DON
	WHERE  
	HOA_DON.ACTIVE = 'A'
	AND HOA_DON.MA_HOA_DON = @MA_HOA_DON;

	
	DECLARE CHI_TIEC_HOA_DON_CURSOR CURSOR FOR
	SELECT 
	MA_SAN_PHAM, 
	SO_LUONG, 
	DON_GIA - DON_GIA.PHAN_TRAM_CHIEC_KHAU/100 DON_GIA, 
	MA_KHO_XUAT 
	FROM
	CHI_TIEC_HOA_DON
	WHERE
	ACTIVE = 'A'
	AND MA_HOA_DON = @MA_HOA_DON
	ORDER BY MA_KHO
	
END