ALTER PROCEDURE [dbo].[SP_EXPORT_REPORT]
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG),0) SO_LUONG, 
		ISNULL(V_XUAT_KHO.GIA_XUAT, 0) GIA_XUAT,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT,0) VALUE 
	FROM
	V_XUAT_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_XUAT_KHO.GIA_XUAT, 
		DON_VI_TINH.TEN_DON_VI
END 

ALTER PROCEDURE [dbo].[SP_EXPORT_REPORT_DETAIL]
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT
		V_XUAT_KHO.NGAY_XUAT, 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI, 
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG),0) SO_LUONG, 
		ISNULL(V_XUAT_KHO.GIA_XUAT,0)  GIA_XUAT,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT,0) VALUE 
	FROM
	V_XUAT_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_XUAT_KHO.GIA_XUAT, 
		V_XUAT_KHO.NGAY_XUAT, 
		DON_VI_TINH.TEN_DON_VI
	ORDER BY V_XUAT_KHO.NGAY_XUAT DESC
END 

ALTER PROCEDURE [dbo].[SP_GET_PHIEU_CHUYEN_KHO] 
@STATUS INT, 
@MA_KHO_CHUYEN INT, 
@MA_KHO_NHAN INT, 
@FROM_DATE DATE, 
@TO_DATE DATE, 
@MA_NHAN_VIEN_CHUYEN INT, 
@TEN_NHAN_VIEN_CHUYEN NVARCHAR(100)
AS
BEGIN
	SELECT
		XUAT_KHO.MA_XUAT_KHO, 
		XUAT_KHO.MA_KHO_XUAT, 
		KHO_XUAT.TEN_KHO TEN_KHO_XUAT,
		XUAT_KHO.MA_KHO_NHAN,
		KHO_NHAN.TEN_KHO TEN_KHO_NHAN,
		XUAT_KHO.GHI_CHU,
		XUAT_KHO.NGAY_XUAT,
		XUAT_KHO.ACTIVE, 
		XUAT_KHO.MA_NHAN_VIEN_XUAT, 
		NGUOI_DUNG.TEN_NGUOI_DUNG TEN_NHAN_VIEN_XUAT,
		CASE XUAT_KHO.ACTIVE 
			WHEN 'W' THEN 1
			WHEN 'A' THEN 
				CASE (SELECT COUNT(MA_PHIEU_XUAT) FROM  NHAP_KHO WHERE NHAP_KHO.ACTIVE = 'A' AND MA_PHIEU_XUAT  = XUAT_KHO.MA_XUAT_KHO)
				WHEN 0
					THEN 2
				ELSE
					 3 
				END
		END AS STATUS
	FROM
		XUAT_KHO, 
		KHO KHO_XUAT, 
		KHO KHO_NHAN, 
		NGUOI_DUNG
	WHERE
		XUAT_KHO.LY_DO_XUAT = 3 -- XUẤT CHUYỂN KHO
		AND (@MA_KHO_CHUYEN = 0 OR XUAT_KHO.MA_KHO_XUAT = @MA_KHO_CHUYEN)
		AND (@MA_KHO_NHAN = 0 OR XUAT_KHO.MA_KHO_NHAN = @MA_KHO_NHAN)
		AND (@FROM_DATE IS NULL OR CAST(NGAY_XUAT AS DATE) >= CAST(@FROM_DATE AS DATE))
		AND (@TO_DATE IS NULL OR CAST(NGAY_XUAT AS DATE) <= CAST(@TO_DATE AS DATE))
		AND (@MA_NHAN_VIEN_CHUYEN = 0 OR XUAT_KHO.MA_NHAN_VIEN_XUAT = @MA_NHAN_VIEN_CHUYEN)
		AND (@TEN_NHAN_VIEN_CHUYEN IS NULL OR @TEN_NHAN_VIEN_CHUYEN = '' OR NGUOI_DUNG.TEN_NGUOI_DUNG LIKE '%' + @TEN_NHAN_VIEN_CHUYEN + '%')
		AND (
				@STATUS = 0 OR
				(
					@STATUS = 1 
					AND XUAT_KHO.ACTIVE = 'W'
				) OR 
				(
					@STATUS = 2 
					AND XUAT_KHO.ACTIVE = 'A' 
					AND XUAT_KHO.MA_XUAT_KHO NOT IN (SELECT ISNULL(MA_PHIEU_XUAT,0) FROM  NHAP_KHO WHERE NHAP_KHO.ACTIVE = 'A')
				)
				OR 
				(
					@STATUS = 3
					AND XUAT_KHO.ACTIVE = 'A' 
					AND XUAT_KHO.MA_XUAT_KHO  IN (SELECT ISNULL(MA_PHIEU_XUAT,0) FROM  NHAP_KHO WHERE NHAP_KHO.ACTIVE = 'A')
				)
			)
		AND XUAT_KHO.MA_KHO_XUAT = KHO_XUAT.MA_KHO
		AND XUAT_KHO.MA_KHO_NHAN = KHO_NHAN.MA_KHO
		AND XUAT_KHO.MA_NHAN_VIEN_XUAT = NGUOI_DUNG.MA_NGUOI_DUNG
	ORDER BY XUAT_KHO.NGAY_XUAT DESC
END



