CREATE PROCEDURE SP_EXPORT_REPORT
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI,
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG),0) SO_LUONG, 
		V_XUAT_KHO.GIA_XUAT, 
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT,0) VALUE 
	FROM
	V_XUAT_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_XUAT_KHO.GIA_XUAT, 
		DON_VI_TINH.TEN_DON_VI
END 


CREATE PROCEDURE SP_EXPORT_REPORT_DETAIL
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT
		V_XUAT_KHO.NGAY_XUAT, 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		DON_VI_TINH.TEN_DON_VI, 
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG),0) SO_LUONG, 
		V_XUAT_KHO.GIA_XUAT, 
		ISNULL(SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT,0) VALUE 
	FROM
	V_XUAT_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE 
		(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
		AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
		AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
		AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
		AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
		AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
		AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
	GROUP BY 
		V_XUAT_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		V_XUAT_KHO.GIA_XUAT, 
		V_XUAT_KHO.NGAY_XUAT, 
		DON_VI_TINH.TEN_DON_VI
	ORDER BY V_XUAT_KHO.NGAY_XUAT
END 

CREATE PROCEDURE SP_EXPORT_REPORT_SUM
@KIND INT, 
@MA_KHO INT,
@MA_SAN_PHAM INT, 
@TEN_SAN_PHAM NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
		SELECT
		ISNULL(SUM(VALUE),0) VALUE
		FROM
		(
			SELECT
				SUM(V_XUAT_KHO.SO_LUONG)*GIA_XUAT VALUE 
			FROM
			V_XUAT_KHO, 
			SAN_PHAM
			WHERE 
				(@KIND IS NULL OR @KIND = -1 OR V_XUAT_KHO.LY_DO_XUAT = @KIND)
				AND (@MA_KHO IS NULL OR @MA_KHO = 0 OR V_XUAT_KHO.MA_KHO_XUAT = @MA_KHO)
				AND (@MA_SAN_PHAM IS NULL OR @MA_SAN_PHAM = 0 OR V_XUAT_KHO.MA_SAN_PHAM = @MA_SAN_PHAM)
				AND (@FROM_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT >= @FROM_DATE)
				AND (@TO_DATE IS NULL OR V_XUAT_KHO.NGAY_XUAT <= @TO_DATE)
				AND (@TEN_SAN_PHAM IS NULL OR @TEN_SAN_PHAM = '' OR SAN_PHAM.TEN_SAN_PHAM LIKE '%' + @TEN_SAN_PHAM + '%')
				AND V_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
			GROUP BY 
				V_XUAT_KHO.MA_SAN_PHAM, 
				SAN_PHAM.TEN_SAN_PHAM, 
				V_XUAT_KHO.GIA_XUAT, 
				V_XUAT_KHO.NGAY_XUAT
		)TEMP
END 
