ALTER PROCEDURE [dbo].[SP_GET_REPORT_DEBT_COLLECTION]
@CUSTOMER_ID INT, 
@CUSTOMER_NAME NVARCHAR(200),
@FROM_DATE DATE, 
@TO_DATE DATE
AS
BEGIN
	SELECT 
	MA_KHACH_HANG, 
	TEN_KHACH_HANG, 
	NGAY_PHAT_SINH,
	SUM(PHAT_SINH) PHAT_SINH,
	SUM(PHAT_SINH_BY_RETURN) PHAT_SINH_BY_RETURN,
	SUM(PHAT_SINH) + SUM(PHAT_SINH_BY_RETURN) TOTAL
	FROM
	(
		SELECT 
		KHACH_HANG.MA_KHACH_HANG, 
		KHACH_HANG.TEN_KHACH_HANG, 
		SUM(ISNULL(KHACH_HANG_DEBIT_HIST.PHAT_SINH,0)) PHAT_SINH,
		KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH,
		0 PHAT_SINH_BY_RETURN
		FROM
		(
			SELECT * FROM KHACH_HANG 
			WHERE ACTIVE = 'A'
			AND (@CUSTOMER_ID = 0 OR KHACH_HANG.MA_KHACH_HANG = @CUSTOMER_ID)
			AND (@CUSTOMER_NAME IS NULL OR @CUSTOMER_NAME = '' OR UPPER(KHACH_HANG.TEN_KHACH_HANG) LIKE '%' + UPPER(@CUSTOMER_NAME) + '%')	
		) KHACH_HANG	
		JOIN(
			SELECT * FROM KHACH_HANG_DEBIT_HIST 
			WHERE 
			MA_PHIEU_TRA IS NULL 
			AND ACTIVE = 'A'
			AND PHAT_SINH >0
			AND (@FROM_DATE IS NULL OR CAST(NGAY_PHAT_SINH AS DATE) >= CAST(@FROM_DATE AS DATE))
			AND (@TO_DATE IS NULL OR CAST(NGAY_PHAT_SINH AS DATE) <= CAST(@TO_DATE AS DATE))
		) KHACH_HANG_DEBIT_HIST ON KHACH_HANG_DEBIT_HIST.MA_KHACH_HANG = KHACH_HANG.MA_KHACH_HANG
		GROUP BY  
		KHACH_HANG.MA_KHACH_HANG, 
		KHACH_HANG.TEN_KHACH_HANG, 
		KHACH_HANG_DEBIT_HIST.NGAY_PHAT_SINH
		UNION ALL		
		SELECT 
		KHACH_HANG_RETURN.MA_KHACH_HANG, 
		KHACH_HANG_RETURN.TEN_KHACH_HANG, 
		0 PHAT_SINH,
		KHACH_HANG_DEBIT_HIST_RETURN.NGAY_PHAT_SINH,
		SUM(ISNULL(KHACH_HANG_DEBIT_HIST_RETURN.PHAT_SINH,0)) PHAT_SINH_BY_RETURN
		FROM
		(
			SELECT * FROM KHACH_HANG 
			WHERE ACTIVE = 'A'
			AND (@CUSTOMER_ID = 0 OR KHACH_HANG.MA_KHACH_HANG = @CUSTOMER_ID)
			AND (@CUSTOMER_NAME IS NULL OR @CUSTOMER_NAME = '' OR UPPER(KHACH_HANG.TEN_KHACH_HANG) LIKE '%' + UPPER(@CUSTOMER_NAME) + '%')	
		) KHACH_HANG_RETURN	
		JOIN(
			SELECT * FROM KHACH_HANG_DEBIT_HIST 
			WHERE 
			MA_PHIEU_TRA IS NOT NULL 
			AND ACTIVE = 'A'
			AND PHAT_SINH >0
			AND (@FROM_DATE IS NULL OR CAST(NGAY_PHAT_SINH AS DATE) >= CAST(@FROM_DATE AS DATE))
			AND (@TO_DATE IS NULL OR CAST(NGAY_PHAT_SINH AS DATE) <= CAST(@TO_DATE AS DATE))
		) KHACH_HANG_DEBIT_HIST_RETURN ON KHACH_HANG_DEBIT_HIST_RETURN.MA_KHACH_HANG = KHACH_HANG_RETURN.MA_KHACH_HANG
		GROUP BY 
		KHACH_HANG_RETURN.MA_KHACH_HANG, 
		KHACH_HANG_RETURN.TEN_KHACH_HANG, 
		KHACH_HANG_DEBIT_HIST_RETURN.NGAY_PHAT_SINH
	)TEMP
	GROUP BY MA_KHACH_HANG, 
	TEN_KHACH_HANG, 
	NGAY_PHAT_SINH
END