ALTER VIEW [dbo].[V_XUAT_KHO] 
AS
SELECT 
	XUAT_KHO.MA_XUAT_KHO,
	XUAT_KHO.NGAY_XUAT, 
	XUAT_KHO.MA_KHO_XUAT, 
	XUAT_KHO.LY_DO_XUAT, 
	CHI_TIET_XUAT_KHO.MA_SAN_PHAM, 
	CHI_TIET_XUAT_KHO.SO_LUONG, 
	CHI_TIET_XUAT_KHO.GIA_XUAT
FROM 
	XUAT_KHO, 
	CHI_TIET_XUAT_KHO
WHERE
			XUAT_KHO.ACTIVE = 'A'
	AND 	CHI_TIET_XUAT_KHO.ACTIVE = 'A'
	AND 	CAST(XUAT_KHO.NGAY_XUAT AS DATE) >= CAST(DBO.STMA_GET_MAX_DATE_KIEM_KHO(XUAT_KHO.MA_KHO_XUAT) AS DATE)
	AND 	XUAT_KHO.MA_XUAT_KHO = CHI_TIET_XUAT_KHO.MA_XUAT_KHO
GO

CREATE PROCEDURE SP_HET_IM_BY_ID
@ID INT
AS
BEGIN
	SELECT 
		NHAP_KHO.MA_NHAP_KHO, 
		NHAP_KHO.SO_HOA_DON,
		NHAP_KHO.NGAY_NHAP,
		NHAP_KHO.NHAN_VIEN_NHAP,
		NHAP_KHO.MA_NHA_CUNG_CAP,
		NHAP_KHO.MA_KHO,
		NHAP_KHO.LY_DO_NHAP,
		NHAP_KHO.GHI_CHU,
		KHO.TEN_KHO, 
		NGUOI_DUNG.TEN_NGUOI_DUNG
	FROM
	NHAP_KHO
	LEFT JOIN NHA_CUNG_CAP ON NHAP_KHO.MA_NHA_CUNG_CAP = NHA_CUNG_CAP.MA_NHA_CUNG_CAP
	LEFT JOIN KHO ON NHAP_KHO.MA_KHO = KHO.MA_KHO
	LEFT JOIN NGUOI_DUNG ON NHAP_KHO.NHAN_VIEN_NHAP = NGUOI_DUNG.MA_NGUOI_DUNG
	WHERE
	NHAP_KHO.ACTIVE = 'A'
	AND NHAP_KHO.MA_NHAP_KHO = @ID
END

CREATE PROCEDURE SP_GET_IM_DETAIL_BY_ID
@ID INT
AS
BEGIN
	SELECT 
		CHI_TIET_NHAP_KHO.MA_SAN_PHAM, 
		SAN_PHAM.TEN_SAN_PHAM, 
		CASE ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG_TEMP,0)
		WHEN 0 THEN 
			ISNULL(CHI_TIET_NHAP_KHO.SO_LUONG,0)
		ELSE 
			CHI_TIET_NHAP_KHO.SO_LUONG_TEMP
		END AS SO_LUONG, 
		CASE ISNULL(CHI_TIET_NHAP_KHO.MA_DON_VI,0)
		WHEN 0 THEN 
			SAN_PHAM.MA_DON_VI
		ELSE 
			CHI_TIET_NHAP_KHO.MA_DON_VI
		END AS MA_DON_VI, 	
		CASE ISNULL(CHI_TIET_NHAP_KHO.DON_GIA_TEMP, 0) 
		WHEN 0 THEN
			ISNULL(CHI_TIET_NHAP_KHO.GIA_VON,0)
		ELSE
			CHI_TIET_NHAP_KHO.DON_GIA_TEMP
		END AS DON_GIA, 
		DON_VI.TEN_DON_VI, 
		SAN_PHAM.TEN_SAN_PHAM
	FROM 
		CHI_TIET_NHAP_KHO, 
		SAN_PHAM, 
		DON_VI
	WHERE 
		CHI_TIET_NHAP_KHO.ACTIVE = 'A'
		AND CHI_TIET_NHAP_KHO.MA_NHAP_KHO = @ID
		AND CHI_TIET_NHAP_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
		AND 
		(
			CHI_TIET_NHAP_KHO.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_NHAP_KHO.MA_DON_VI IS NOT NULL AND CHI_TIET_NHAP_KHO.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		)		
END

CREATE PROCEDURE SP_GET_EX_BY_ID
@ID INT
AS
BEGIN
	SELECT 
		XUAT_KHO.MA_XUAT_KHO,
		XUAT_KHO.MA_HOA_DON,
		XUAT_KHO.LY_DO_XUAT,
		XUAT_KHO.MA_KHO_XUAT,
		XUAT_KHO.MA_KHO_NHAN,
		XUAT_KHO.NGAY_XUAT,
		XUAT_KHO.MA_NHAN_VIEN_XUAT, 
		XUAT_KHO.TEN_NGUOI_NHAN_HANG, 
		XUAT_KHO.GHI_CHU, 
		KHO.TEN_KHO TEN_KHO_XUAT, 
		KHO_NHAN.TEN_KHO TEN_KHO_NHAN
	FROM
		XUAT_KHO
	LEFT JOIN KHO ON XUAT_KHO.MA_KHO_XUAT = KHO.MA_KHO
	LEFT JOIN KHO KHO_NHAN ON XUAT_KHO.MA_KHO_NHAN = KHO_NHAN.MA_KHO
	LEFT JOIN NGUOI_DUNG ON XUAT_KHO.MA_NHAN_VIEN_XUAT = NGUOI_DUNG.MA_NGUOI_DUNG
	WHERE
	XUAT_KHO.ACTIVE = 'A' AND XUAT_KHO.MA_XUAT_KHO = @ID
END

CREATE PROCEDURE SP_GET_EX_DETAIL_BY_ID
@ID INT
AS
BEGIN
	SELECT 
		CHI_TIET_XUAT_KHO.MA_XUAT_KHO, 
		CHI_TIET_XUAT_KHO.MA_SAN_PHAM, 
		CASE ISNULL(CHI_TIET_XUAT_KHO.SO_LUONG_TEMP,0)			
		WHEN 0 THEN 
			ISNULL(CHI_TIET_XUAT_KHO.SO_LUONG,0)
		ELSE CHI_TIET_XUAT_KHO.SO_LUONG_TEMP
		END AS SO_LUONG,		 
		CASE ISNULL(CHI_TIET_XUAT_KHO.DON_GIA_TEMP,0) 
		WHEN 0 THEN
			ISNULL(CHI_TIET_XUAT_KHO.GIA_XUAT, 0)
		ELSE
			CHI_TIET_XUAT_KHO.DON_GIA_TEMP
		END AS DON_GIA,		
		CASE ISNULL(CHI_TIET_XUAT_KHO.MA_DON_VI,0) 
		WHEN 0 THEN
			SAN_PHAM.MA_DON_VI
		ELSE CHI_TIET_XUAT_KHO.MA_DON_VI
		END AS MA_DON_VI,
		DON_VI_TINH.TEN_DON_VI, 
		SAN_PHAM.TEN_SAN_PHAM
	FROM
	CHI_TIET_XUAT_KHO, 
	SAN_PHAM, 
	DON_VI_TINH
	WHERE
	CHI_TIET_XUAT_KHO.ACTIVE = 'A'
	AND MA_XUAT_KHO = @ID
	AND CHI_TIET_XUAT_KHO.MA_SAN_PHAM = SAN_PHAM.MA_SAN_PHAM
	AND 
		(
			CHI_TIET_XUAT_KHO.MA_DON_VI IS NULL AND SAN_PHAM.MA_DON_VI = DON_VI_TINH.MA_DON_VI
			OR 
			CHI_TIET_XUAT_KHO.MA_DON_VI IS NOT NULL AND CHI_TIET_XUAT_KHO.MA_DON_VI = DON_VI_TINH.MA_DON_VI
		)
END

ALTER TABLE
TRA_HANG_NCC_CHI_TIET
ADD MA_KHO_XUAT INT

ALTER TABLE
TRA_HANG_NCC_CHI_TIET
ADD SO_LUONG_TEMP FLOAT

ALTER TABLE
TRA_HANG_NCC_CHI_TIET
ADD MA_DON_VI INT
