//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYEN_DOI_DON_VI_TINH
    {
        public int MA_CHUYEN_DOI { get; set; }
        public Nullable<int> MA_SAN_PHAN { get; set; }
        public Nullable<int> MA_DON_VI_VAO { get; set; }
        public Nullable<double> HE_SO { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual DON_VI_TINH DON_VI_TINH { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
    }
}
