//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using PagedList;

    public class ExpenesModel
    {
        public int Kind { get; set; }
        public int Count { get; set; }
        public IPagedList<SP_GET_EXPENSES_Result> ResultList { get; set; } 
    }

    public partial class EXPENS
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Mục đích chi")]
        public Nullable<short> LOAI_CHI { get; set; }

        [Display(Name = "Người chi tiền")]
        public Nullable<int> NGUOI_CHI { get; set; }


        [Required]
        [Display(Name = "Tên người nhận tiền")]
        public string TEN_NGUOI_NHAN { get; set; }

        [Required]
        [Display(Name = "Ngày chi tiền")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NGAY_CHI { get; set; }

        [Required]
        [Display(Name = "Tổng số tiền chi")]
        public Nullable<double> TONG_CHI { get; set; }

        [Display(Name = "Ghi chú")]
        public string GHI_CHU { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG2 { get; set; }
    }
}
