//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public class KhachHangModel
    {
        public KHACH_HANG KhachHang { get; set; }
        public KHU_VUC KhuVuc { get; set; }
        public NGUOI_DUNG NguoiTao { get; set; }
        public NGUOI_DUNG NguoiCapNhat { get; set; }
    }


    public partial class KHACH_HANG
    {
        public KHACH_HANG()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int MA_KHACH_HANG { get; set; }

        [Required]
        [Display(Name = "Mã thẻ khách hàng")]
        [StringLength(20)]
        public string MA_THE_KHACH_HANG { get; set; }

        [Required]
        [Display(Name = "Tên khách hàng")]
        [StringLength(50)]
        public string TEN_KHACH_HANG { get; set; }

        [Required]
        [Display(Name = "Địa chỉ")]
        [StringLength(200)]
        public string DIA_CHI { get; set; }

        [Display(Name = "Số điện thoại")]
        [StringLength(50)]
        public string SO_DIEN_THOAI { get; set; }

        [Display(Name = "Tên khách hàng")]
        [StringLength(50)]
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }

        [Display(Name = "Khu vực")]
        public Nullable<int> MA_KHU_VUC { get; set; }

        [Display(Name = "Doanh số")]
        public Nullable<decimal> DOANH_SO { get; set; }

        [Display(Name = "Nợ gối đầu")]
        public Nullable<decimal> NO_GOI_DAU { get; set; }
        public byte[] HINH_ANH { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }

        [Display(Name = "Ngày phát sinh nợ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NGAY_PHAT_SINH_NO { get; set; }
    
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual KHU_VUC KHU_VUC { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
    }
}
