//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_NGUOI_DUNG
    {
        public NHOM_NGUOI_DUNG()
        {
            this.NGUOI_DUNG = new HashSet<NGUOI_DUNG>();
            this.PHAN_QUYEN = new HashSet<PHAN_QUYEN>();
            this.PHAN_QUYEN1 = new HashSet<PHAN_QUYEN>();
        }
    
        public int MA_NHOM { get; set; }
        public string TEN_NHOM { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
    
        public virtual ICollection<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG1 { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG2 { get; set; }
        public virtual ICollection<PHAN_QUYEN> PHAN_QUYEN { get; set; }
        public virtual ICollection<PHAN_QUYEN> PHAN_QUYEN1 { get; set; }
    }
}
