//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_QUESTIONS
    {
        public int ID { get; set; }
        public Nullable<int> USR_ID { get; set; }
        public Nullable<int> QUESTION_ID { get; set; }
        public string ANSWER { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual SECURITY_QUESTIONS SECURITY_QUESTIONS { get; set; }
    }
}
