//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SmsContext : DbContext
    {
        public SmsContext()
            : base("name=SmsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual DbSet<CHI_TIET_NHAP_KHO> CHI_TIET_NHAP_KHO { get; set; }
        public virtual DbSet<CHI_TIET_TRA_HANG> CHI_TIET_TRA_HANG { get; set; }
        public virtual DbSet<CHI_TIET_XUAT_KHO> CHI_TIET_XUAT_KHO { get; set; }
        public virtual DbSet<CHUYEN_DOI_DON_VI_TINH> CHUYEN_DOI_DON_VI_TINH { get; set; }
        public virtual DbSet<CONTROLLER_PERMISSION> CONTROLLER_PERMISSION { get; set; }
        public virtual DbSet<DON_VI_TINH> DON_VI_TINH { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<KHACH_HANG_DEBIT_HIST> KHACH_HANG_DEBIT_HIST { get; set; }
        public virtual DbSet<KHO> KHOes { get; set; }
        public virtual DbSet<KHU_VUC> KHU_VUC { get; set; }
        public virtual DbSet<KIEM_KHO_HISTORY> KIEM_KHO_HISTORY { get; set; }
        public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public virtual DbSet<NHA_SAN_XUAT> NHA_SAN_XUAT { get; set; }
        public virtual DbSet<NHAP_KHO> NHAP_KHO { get; set; }
        public virtual DbSet<NHOM_NGUOI_DUNG> NHOM_NGUOI_DUNG { get; set; }
        public virtual DbSet<PHAN_QUYEN> PHAN_QUYEN { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<SMS_MASTER> SMS_MASTER { get; set; }
        public virtual DbSet<SMS_MESSAGES> SMS_MESSAGES { get; set; }
        public virtual DbSet<TRA_HANG> TRA_HANG { get; set; }
        public virtual DbSet<TRA_HANG_NCC> TRA_HANG_NCC { get; set; }
        public virtual DbSet<TRA_HANG_NCC_CHI_TIET> TRA_HANG_NCC_CHI_TIET { get; set; }
        public virtual DbSet<XUAT_KHO> XUAT_KHO { get; set; }
        public virtual DbSet<V_HOA_DON> V_HOA_DON { get; set; }
        public virtual DbSet<V_HOA_DON_DISTICNT> V_HOA_DON_DISTICNT { get; set; }
        public virtual DbSet<V_IMPORT_DETAIL> V_IMPORT_DETAIL { get; set; }
        public virtual DbSet<V_MA_TRA_HANG> V_MA_TRA_HANG { get; set; }
        public virtual DbSet<V_NHAP_KHO> V_NHAP_KHO { get; set; }
        public virtual DbSet<V_NHAP_XUAT_DETAIL> V_NHAP_XUAT_DETAIL { get; set; }
        public virtual DbSet<V_NHAP_XUAT_KHO> V_NHAP_XUAT_KHO { get; set; }
        public virtual DbSet<V_TRA_NHAP_TRA_NCC> V_TRA_NHAP_TRA_NCC { get; set; }
        public virtual DbSet<V_XUAT_KHO> V_XUAT_KHO { get; set; }
    
        public virtual ObjectResult<GET_HOA_DON_Result> GET_HOA_DON(Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_KHACH_HANG)
        {
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_HOA_DON_Result>("GET_HOA_DON", fROM_DATEParameter, tO_DATEParameter, mA_KHACH_HANGParameter);
        }
    
        public virtual int GET_KHACH_HANG_ALERT(string nAME)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_KHACH_HANG_ALERT", nAMEParameter);
        }
    
        public virtual ObjectResult<GET_SUM_HOA_DON_BY_CUS_ID_Result> GET_SUM_HOA_DON_BY_CUS_ID(Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_KHACH_HANG)
        {
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SUM_HOA_DON_BY_CUS_ID_Result>("GET_SUM_HOA_DON_BY_CUS_ID", fROM_DATEParameter, tO_DATEParameter, mA_KHACH_HANGParameter);
        }
    
        public virtual int SP_DELETE_EXPORT_4_SALE(Nullable<int> mA_XUAT_KHO, Nullable<int> mA_NHAN_VIEN_TH, ObjectParameter rETURN_VALUE)
        {
            var mA_XUAT_KHOParameter = mA_XUAT_KHO.HasValue ?
                new ObjectParameter("MA_XUAT_KHO", mA_XUAT_KHO) :
                new ObjectParameter("MA_XUAT_KHO", typeof(int));
    
            var mA_NHAN_VIEN_THParameter = mA_NHAN_VIEN_TH.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_TH", mA_NHAN_VIEN_TH) :
                new ObjectParameter("MA_NHAN_VIEN_TH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_EXPORT_4_SALE", mA_XUAT_KHOParameter, mA_NHAN_VIEN_THParameter, rETURN_VALUE);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_EXPORT_REPORT_Result> SP_EXPORT_REPORT(Nullable<int> kIND, Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var kINDParameter = kIND.HasValue ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EXPORT_REPORT_Result>("SP_EXPORT_REPORT", kINDParameter, mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_EXPORT_REPORT_DETAIL_Result> SP_EXPORT_REPORT_DETAIL(Nullable<int> kIND, Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var kINDParameter = kIND.HasValue ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EXPORT_REPORT_DETAIL_Result>("SP_EXPORT_REPORT_DETAIL", kINDParameter, mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> SP_EXPORT_REPORT_SUM(Nullable<int> kIND, Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var kINDParameter = kIND.HasValue ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SP_EXPORT_REPORT_SUM", kINDParameter, mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALL_ROLE_Result> SP_GET_ALL_ROLE(Nullable<int> uSER_ID, string uSER_FULL_NAME)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var uSER_FULL_NAMEParameter = uSER_FULL_NAME != null ?
                new ObjectParameter("USER_FULL_NAME", uSER_FULL_NAME) :
                new ObjectParameter("USER_FULL_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALL_ROLE_Result>("SP_GET_ALL_ROLE", uSER_IDParameter, uSER_FULL_NAMEParameter);
        }
    
        public virtual ObjectResult<SP_GET_CHI_TIET_PHIEU_XUAT_CHUYEN_Result> SP_GET_CHI_TIET_PHIEU_XUAT_CHUYEN(Nullable<int> mA_XUAT_KHO)
        {
            var mA_XUAT_KHOParameter = mA_XUAT_KHO.HasValue ?
                new ObjectParameter("MA_XUAT_KHO", mA_XUAT_KHO) :
                new ObjectParameter("MA_XUAT_KHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_CHI_TIET_PHIEU_XUAT_CHUYEN_Result>("SP_GET_CHI_TIET_PHIEU_XUAT_CHUYEN", mA_XUAT_KHOParameter);
        }
    
        public virtual ObjectResult<SP_GET_DON_VI_TINH_Result> SP_GET_DON_VI_TINH(Nullable<int> mA_SAN_PHAM)
        {
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_DON_VI_TINH_Result>("SP_GET_DON_VI_TINH", mA_SAN_PHAMParameter);
        }
    
        public virtual ObjectResult<SP_GET_EX_BY_ID_Result> SP_GET_EX_BY_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_EX_BY_ID_Result>("SP_GET_EX_BY_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_GET_EX_DETAIL_BY_ID_Result> SP_GET_EX_DETAIL_BY_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_EX_DETAIL_BY_ID_Result>("SP_GET_EX_DETAIL_BY_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_GET_EXPORT_4_CANCEL_Result> SP_GET_EXPORT_4_CANCEL(Nullable<int> mA_KHO, string tEN_KHO, Nullable<int> mA_NHAN_VIEN, string tEN_NHAN_VIEN, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var tEN_KHOParameter = tEN_KHO != null ?
                new ObjectParameter("TEN_KHO", tEN_KHO) :
                new ObjectParameter("TEN_KHO", typeof(string));
    
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(int));
    
            var tEN_NHAN_VIENParameter = tEN_NHAN_VIEN != null ?
                new ObjectParameter("TEN_NHAN_VIEN", tEN_NHAN_VIEN) :
                new ObjectParameter("TEN_NHAN_VIEN", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_EXPORT_4_CANCEL_Result>("SP_GET_EXPORT_4_CANCEL", mA_KHOParameter, tEN_KHOParameter, mA_NHAN_VIENParameter, tEN_NHAN_VIENParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GET_HD_DETAIL_FOR_EXPORT_Result> SP_GET_HD_DETAIL_FOR_EXPORT(Nullable<int> mA_KHO, Nullable<int> mA_HOA_DON)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_HOA_DONParameter = mA_HOA_DON.HasValue ?
                new ObjectParameter("MA_HOA_DON", mA_HOA_DON) :
                new ObjectParameter("MA_HOA_DON", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HD_DETAIL_FOR_EXPORT_Result>("SP_GET_HD_DETAIL_FOR_EXPORT", mA_KHOParameter, mA_HOA_DONParameter);
        }
    
        public virtual ObjectResult<SP_GET_HOA_DON_Result> SP_GET_HOA_DON(Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_NHAN_VIEN_BAN_HANG, Nullable<int> mA_NV_THU_TIEN)
        {
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_NHAN_VIEN_BAN_HANGParameter = mA_NHAN_VIEN_BAN_HANG.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_BAN_HANG", mA_NHAN_VIEN_BAN_HANG) :
                new ObjectParameter("MA_NHAN_VIEN_BAN_HANG", typeof(int));
    
            var mA_NV_THU_TIENParameter = mA_NV_THU_TIEN.HasValue ?
                new ObjectParameter("MA_NV_THU_TIEN", mA_NV_THU_TIEN) :
                new ObjectParameter("MA_NV_THU_TIEN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HOA_DON_Result>("SP_GET_HOA_DON", fROM_DATEParameter, tO_DATEParameter, mA_NHAN_VIEN_BAN_HANGParameter, mA_NV_THU_TIENParameter);
        }
    
        public virtual ObjectResult<SP_GET_HOA_DON_BH_Result> SP_GET_HOA_DON_BH(Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_KHACH_HANG, string tEN_KHACH_HANG, Nullable<int> mA_NHAN_VIEN_BAN, string tEN_NV_BAN, Nullable<int> mA_NHAN_VIEN_TT, string tEN_NV_TT, Nullable<int> sTATUS, Nullable<int> mA_KHU_VUC, string tEN_KHU_VUC)
        {
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var mA_NHAN_VIEN_BANParameter = mA_NHAN_VIEN_BAN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_BAN", mA_NHAN_VIEN_BAN) :
                new ObjectParameter("MA_NHAN_VIEN_BAN", typeof(int));
    
            var tEN_NV_BANParameter = tEN_NV_BAN != null ?
                new ObjectParameter("TEN_NV_BAN", tEN_NV_BAN) :
                new ObjectParameter("TEN_NV_BAN", typeof(string));
    
            var mA_NHAN_VIEN_TTParameter = mA_NHAN_VIEN_TT.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_TT", mA_NHAN_VIEN_TT) :
                new ObjectParameter("MA_NHAN_VIEN_TT", typeof(int));
    
            var tEN_NV_TTParameter = tEN_NV_TT != null ?
                new ObjectParameter("TEN_NV_TT", tEN_NV_TT) :
                new ObjectParameter("TEN_NV_TT", typeof(string));
    
            var sTATUSParameter = sTATUS.HasValue ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(int));
    
            var mA_KHU_VUCParameter = mA_KHU_VUC.HasValue ?
                new ObjectParameter("MA_KHU_VUC", mA_KHU_VUC) :
                new ObjectParameter("MA_KHU_VUC", typeof(int));
    
            var tEN_KHU_VUCParameter = tEN_KHU_VUC != null ?
                new ObjectParameter("TEN_KHU_VUC", tEN_KHU_VUC) :
                new ObjectParameter("TEN_KHU_VUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HOA_DON_BH_Result>("SP_GET_HOA_DON_BH", fROM_DATEParameter, tO_DATEParameter, mA_KHACH_HANGParameter, tEN_KHACH_HANGParameter, mA_NHAN_VIEN_BANParameter, tEN_NV_BANParameter, mA_NHAN_VIEN_TTParameter, tEN_NV_TTParameter, sTATUSParameter, mA_KHU_VUCParameter, tEN_KHU_VUCParameter);
        }
    
        public virtual ObjectResult<SP_GET_HOA_DON_CAN_XUAT_KHO_Result> SP_GET_HOA_DON_CAN_XUAT_KHO(Nullable<int> mA_KHACH_HANG, string tEN_KHACH_HANG, Nullable<int> mA_KHO, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HOA_DON_CAN_XUAT_KHO_Result>("SP_GET_HOA_DON_CAN_XUAT_KHO", mA_KHACH_HANGParameter, tEN_KHACH_HANGParameter, mA_KHOParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GET_HOA_DON_CHUA_TT_Result> SP_GET_HOA_DON_CHUA_TT(Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_KHACH_HANG, string tEN_KHACH_HANG, Nullable<int> mA_NHAN_VIEN_BAN, string tEN_NV_BAN, Nullable<int> mA_NHAN_VIEN_TT, string tEN_NV_TT)
        {
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var mA_NHAN_VIEN_BANParameter = mA_NHAN_VIEN_BAN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_BAN", mA_NHAN_VIEN_BAN) :
                new ObjectParameter("MA_NHAN_VIEN_BAN", typeof(int));
    
            var tEN_NV_BANParameter = tEN_NV_BAN != null ?
                new ObjectParameter("TEN_NV_BAN", tEN_NV_BAN) :
                new ObjectParameter("TEN_NV_BAN", typeof(string));
    
            var mA_NHAN_VIEN_TTParameter = mA_NHAN_VIEN_TT.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_TT", mA_NHAN_VIEN_TT) :
                new ObjectParameter("MA_NHAN_VIEN_TT", typeof(int));
    
            var tEN_NV_TTParameter = tEN_NV_TT != null ?
                new ObjectParameter("TEN_NV_TT", tEN_NV_TT) :
                new ObjectParameter("TEN_NV_TT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HOA_DON_CHUA_TT_Result>("SP_GET_HOA_DON_CHUA_TT", fROM_DATEParameter, tO_DATEParameter, mA_KHACH_HANGParameter, tEN_KHACH_HANGParameter, mA_NHAN_VIEN_BANParameter, tEN_NV_BANParameter, mA_NHAN_VIEN_TTParameter, tEN_NV_TTParameter);
        }
    
        public virtual ObjectResult<SP_GET_HOA_DON_DETAIL_FOR_RETURN_Result> SP_GET_HOA_DON_DETAIL_FOR_RETURN(Nullable<int> mA_HOA_DON)
        {
            var mA_HOA_DONParameter = mA_HOA_DON.HasValue ?
                new ObjectParameter("MA_HOA_DON", mA_HOA_DON) :
                new ObjectParameter("MA_HOA_DON", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HOA_DON_DETAIL_FOR_RETURN_Result>("SP_GET_HOA_DON_DETAIL_FOR_RETURN", mA_HOA_DONParameter);
        }
    
        public virtual ObjectResult<SP_GET_HOA_DON_EXPORTED_Result> SP_GET_HOA_DON_EXPORTED(Nullable<int> mA_HOA_DON, string sO_HOA_DON, Nullable<int> mA_KHACH_HANG, string tEN_KHACH_HANG, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var mA_HOA_DONParameter = mA_HOA_DON.HasValue ?
                new ObjectParameter("MA_HOA_DON", mA_HOA_DON) :
                new ObjectParameter("MA_HOA_DON", typeof(int));
    
            var sO_HOA_DONParameter = sO_HOA_DON != null ?
                new ObjectParameter("SO_HOA_DON", sO_HOA_DON) :
                new ObjectParameter("SO_HOA_DON", typeof(string));
    
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HOA_DON_EXPORTED_Result>("SP_GET_HOA_DON_EXPORTED", mA_HOA_DONParameter, sO_HOA_DONParameter, mA_KHACH_HANGParameter, tEN_KHACH_HANGParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GET_HOA_DON_INFO_Result> SP_GET_HOA_DON_INFO(Nullable<int> mA_HOA_DON)
        {
            var mA_HOA_DONParameter = mA_HOA_DON.HasValue ?
                new ObjectParameter("MA_HOA_DON", mA_HOA_DON) :
                new ObjectParameter("MA_HOA_DON", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_HOA_DON_INFO_Result>("SP_GET_HOA_DON_INFO", mA_HOA_DONParameter);
        }
    
        public virtual int SP_GET_IM_DETAIL_BY_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_IM_DETAIL_BY_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_GET_IMPORT_Result> SP_GET_IMPORT(Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_NHAN_VIEN_NHAP, string tEN_NHAN_VIEN_NHAP, Nullable<int> lY_DO_NHAP, Nullable<int> mA_KHO, string tEN_KHO, Nullable<int> mA_NHA_CC, string tEN_NHA_CUNG_CAP)
        {
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_NHAN_VIEN_NHAPParameter = mA_NHAN_VIEN_NHAP.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_NHAP", mA_NHAN_VIEN_NHAP) :
                new ObjectParameter("MA_NHAN_VIEN_NHAP", typeof(int));
    
            var tEN_NHAN_VIEN_NHAPParameter = tEN_NHAN_VIEN_NHAP != null ?
                new ObjectParameter("TEN_NHAN_VIEN_NHAP", tEN_NHAN_VIEN_NHAP) :
                new ObjectParameter("TEN_NHAN_VIEN_NHAP", typeof(string));
    
            var lY_DO_NHAPParameter = lY_DO_NHAP.HasValue ?
                new ObjectParameter("LY_DO_NHAP", lY_DO_NHAP) :
                new ObjectParameter("LY_DO_NHAP", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var tEN_KHOParameter = tEN_KHO != null ?
                new ObjectParameter("TEN_KHO", tEN_KHO) :
                new ObjectParameter("TEN_KHO", typeof(string));
    
            var mA_NHA_CCParameter = mA_NHA_CC.HasValue ?
                new ObjectParameter("MA_NHA_CC", mA_NHA_CC) :
                new ObjectParameter("MA_NHA_CC", typeof(int));
    
            var tEN_NHA_CUNG_CAPParameter = tEN_NHA_CUNG_CAP != null ?
                new ObjectParameter("TEN_NHA_CUNG_CAP", tEN_NHA_CUNG_CAP) :
                new ObjectParameter("TEN_NHA_CUNG_CAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_IMPORT_Result>("SP_GET_IMPORT", fROM_DATEParameter, tO_DATEParameter, mA_NHAN_VIEN_NHAPParameter, tEN_NHAN_VIEN_NHAPParameter, lY_DO_NHAPParameter, mA_KHOParameter, tEN_KHOParameter, mA_NHA_CCParameter, tEN_NHA_CUNG_CAPParameter);
        }
    
        public virtual ObjectResult<SP_GET_IMPORT_DETAIL_BY_ID_Result> SP_GET_IMPORT_DETAIL_BY_ID(Nullable<int> iMPORT_ID)
        {
            var iMPORT_IDParameter = iMPORT_ID.HasValue ?
                new ObjectParameter("IMPORT_ID", iMPORT_ID) :
                new ObjectParameter("IMPORT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_IMPORT_DETAIL_BY_ID_Result>("SP_GET_IMPORT_DETAIL_BY_ID", iMPORT_IDParameter);
        }
    
        public virtual ObjectResult<SP_GET_IMPORT_DETAIL_BY_ID_4_EDIT_Result> SP_GET_IMPORT_DETAIL_BY_ID_4_EDIT(Nullable<int> mA_NHAP_KHO)
        {
            var mA_NHAP_KHOParameter = mA_NHAP_KHO.HasValue ?
                new ObjectParameter("MA_NHAP_KHO", mA_NHAP_KHO) :
                new ObjectParameter("MA_NHAP_KHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_IMPORT_DETAIL_BY_ID_4_EDIT_Result>("SP_GET_IMPORT_DETAIL_BY_ID_4_EDIT", mA_NHAP_KHOParameter);
        }
    
        public virtual ObjectResult<SP_GET_IMPORT_INFOR_BY_ID_Result> SP_GET_IMPORT_INFOR_BY_ID(Nullable<int> mA_NHAP_KHO)
        {
            var mA_NHAP_KHOParameter = mA_NHAP_KHO.HasValue ?
                new ObjectParameter("MA_NHAP_KHO", mA_NHAP_KHO) :
                new ObjectParameter("MA_NHAP_KHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_IMPORT_INFOR_BY_ID_Result>("SP_GET_IMPORT_INFOR_BY_ID", mA_NHAP_KHOParameter);
        }
    
        public virtual ObjectResult<SP_GET_INVENTORY_Result> SP_GET_INVENTORY(Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_INVENTORY_Result>("SP_GET_INVENTORY", mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> SP_GET_INVENTORY_BY_PRO_STO_ID(Nullable<int> pRODUCT_ID, Nullable<int> sTORE_ID)
        {
            var pRODUCT_IDParameter = pRODUCT_ID.HasValue ?
                new ObjectParameter("PRODUCT_ID", pRODUCT_ID) :
                new ObjectParameter("PRODUCT_ID", typeof(int));
    
            var sTORE_IDParameter = sTORE_ID.HasValue ?
                new ObjectParameter("STORE_ID", sTORE_ID) :
                new ObjectParameter("STORE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SP_GET_INVENTORY_BY_PRO_STO_ID", pRODUCT_IDParameter, sTORE_IDParameter);
        }
    
        public virtual ObjectResult<SP_GET_INVENTORY_BY_STORE_ID_Result> SP_GET_INVENTORY_BY_STORE_ID(Nullable<int> mA_KHO)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_INVENTORY_BY_STORE_ID_Result>("SP_GET_INVENTORY_BY_STORE_ID", mA_KHOParameter);
        }
    
        public virtual ObjectResult<SP_GET_LIST_RETURN_TO_PROVIDERS_Result> SP_GET_LIST_RETURN_TO_PROVIDERS(Nullable<int> pROVIDER_ID, string pROVIDER_NAME, Nullable<int> fLAG, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> uSER_ID, string uSER_FULL_NAME)
        {
            var pROVIDER_IDParameter = pROVIDER_ID.HasValue ?
                new ObjectParameter("PROVIDER_ID", pROVIDER_ID) :
                new ObjectParameter("PROVIDER_ID", typeof(int));
    
            var pROVIDER_NAMEParameter = pROVIDER_NAME != null ?
                new ObjectParameter("PROVIDER_NAME", pROVIDER_NAME) :
                new ObjectParameter("PROVIDER_NAME", typeof(string));
    
            var fLAGParameter = fLAG.HasValue ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(int));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var uSER_FULL_NAMEParameter = uSER_FULL_NAME != null ?
                new ObjectParameter("USER_FULL_NAME", uSER_FULL_NAME) :
                new ObjectParameter("USER_FULL_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_LIST_RETURN_TO_PROVIDERS_Result>("SP_GET_LIST_RETURN_TO_PROVIDERS", pROVIDER_IDParameter, pROVIDER_NAMEParameter, fLAGParameter, fROM_DATEParameter, tO_DATEParameter, uSER_IDParameter, uSER_FULL_NAMEParameter);
        }
    
        public virtual ObjectResult<SP_GET_NHAP_XUAT_Result> SP_GET_NHAP_XUAT(Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_NHAP_XUAT_Result>("SP_GET_NHAP_XUAT", mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GET_PHIEU_CHUYEN_KHO_Result> SP_GET_PHIEU_CHUYEN_KHO(Nullable<int> sTATUS, Nullable<int> mA_KHO_CHUYEN, Nullable<int> mA_KHO_NHAN, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_NHAN_VIEN_CHUYEN, string tEN_NHAN_VIEN_CHUYEN)
        {
            var sTATUSParameter = sTATUS.HasValue ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(int));
    
            var mA_KHO_CHUYENParameter = mA_KHO_CHUYEN.HasValue ?
                new ObjectParameter("MA_KHO_CHUYEN", mA_KHO_CHUYEN) :
                new ObjectParameter("MA_KHO_CHUYEN", typeof(int));
    
            var mA_KHO_NHANParameter = mA_KHO_NHAN.HasValue ?
                new ObjectParameter("MA_KHO_NHAN", mA_KHO_NHAN) :
                new ObjectParameter("MA_KHO_NHAN", typeof(int));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_NHAN_VIEN_CHUYENParameter = mA_NHAN_VIEN_CHUYEN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_CHUYEN", mA_NHAN_VIEN_CHUYEN) :
                new ObjectParameter("MA_NHAN_VIEN_CHUYEN", typeof(int));
    
            var tEN_NHAN_VIEN_CHUYENParameter = tEN_NHAN_VIEN_CHUYEN != null ?
                new ObjectParameter("TEN_NHAN_VIEN_CHUYEN", tEN_NHAN_VIEN_CHUYEN) :
                new ObjectParameter("TEN_NHAN_VIEN_CHUYEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PHIEU_CHUYEN_KHO_Result>("SP_GET_PHIEU_CHUYEN_KHO", sTATUSParameter, mA_KHO_CHUYENParameter, mA_KHO_NHANParameter, fROM_DATEParameter, tO_DATEParameter, mA_NHAN_VIEN_CHUYENParameter, tEN_NHAN_VIEN_CHUYENParameter);
        }
    
        public virtual ObjectResult<SP_GET_PHIEU_CHUYEN_KHO_INFO_BY_ID_Result> SP_GET_PHIEU_CHUYEN_KHO_INFO_BY_ID(Nullable<int> mA_XUAT_KHO)
        {
            var mA_XUAT_KHOParameter = mA_XUAT_KHO.HasValue ?
                new ObjectParameter("MA_XUAT_KHO", mA_XUAT_KHO) :
                new ObjectParameter("MA_XUAT_KHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PHIEU_CHUYEN_KHO_INFO_BY_ID_Result>("SP_GET_PHIEU_CHUYEN_KHO_INFO_BY_ID", mA_XUAT_KHOParameter);
        }
    
        public virtual ObjectResult<SP_GET_PHIEU_XUAT_KHO_BAN_LE_Result> SP_GET_PHIEU_XUAT_KHO_BAN_LE(Nullable<int> mA_KHO, Nullable<int> mA_NHAN_VIEN_XUAT, string tEN_NHAN_VIEN_XUAT, Nullable<int> mA_KHACH_HANG, string tEN_KHACH_HANG, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_NHAN_VIEN_XUATParameter = mA_NHAN_VIEN_XUAT.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_XUAT", mA_NHAN_VIEN_XUAT) :
                new ObjectParameter("MA_NHAN_VIEN_XUAT", typeof(int));
    
            var tEN_NHAN_VIEN_XUATParameter = tEN_NHAN_VIEN_XUAT != null ?
                new ObjectParameter("TEN_NHAN_VIEN_XUAT", tEN_NHAN_VIEN_XUAT) :
                new ObjectParameter("TEN_NHAN_VIEN_XUAT", typeof(string));
    
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PHIEU_XUAT_KHO_BAN_LE_Result>("SP_GET_PHIEU_XUAT_KHO_BAN_LE", mA_KHOParameter, mA_NHAN_VIEN_XUATParameter, tEN_NHAN_VIEN_XUATParameter, mA_KHACH_HANGParameter, tEN_KHACH_HANGParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GET_PRICE_BY_UNIT_Result> SP_GET_PRICE_BY_UNIT(Nullable<int> mA_SAN_PHAM, Nullable<int> mA_DON_VI)
        {
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var mA_DON_VIParameter = mA_DON_VI.HasValue ?
                new ObjectParameter("MA_DON_VI", mA_DON_VI) :
                new ObjectParameter("MA_DON_VI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PRICE_BY_UNIT_Result>("SP_GET_PRICE_BY_UNIT", mA_SAN_PHAMParameter, mA_DON_VIParameter);
        }
    
        public virtual ObjectResult<SP_GET_PRODUC_4_RETURN_Result> SP_GET_PRODUC_4_RETURN(string tEN_SAN_PHAM)
        {
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PRODUC_4_RETURN_Result>("SP_GET_PRODUC_4_RETURN", tEN_SAN_PHAMParameter);
        }
    
        public virtual ObjectResult<SP_GET_RE_DETAIL_BY_ID_Result> SP_GET_RE_DETAIL_BY_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_RE_DETAIL_BY_ID_Result>("SP_GET_RE_DETAIL_BY_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_GET_REFUND_DETAIL_Result> SP_GET_REFUND_DETAIL(Nullable<int> mA_TRA_HANG)
        {
            var mA_TRA_HANGParameter = mA_TRA_HANG.HasValue ?
                new ObjectParameter("MA_TRA_HANG", mA_TRA_HANG) :
                new ObjectParameter("MA_TRA_HANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_REFUND_DETAIL_Result>("SP_GET_REFUND_DETAIL", mA_TRA_HANGParameter);
        }
    
        public virtual ObjectResult<SP_GET_RETURN_DETAIL_BY_ID_Result> SP_GET_RETURN_DETAIL_BY_ID(Nullable<int> mA_TRA_HANG)
        {
            var mA_TRA_HANGParameter = mA_TRA_HANG.HasValue ?
                new ObjectParameter("MA_TRA_HANG", mA_TRA_HANG) :
                new ObjectParameter("MA_TRA_HANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_RETURN_DETAIL_BY_ID_Result>("SP_GET_RETURN_DETAIL_BY_ID", mA_TRA_HANGParameter);
        }
    
        public virtual ObjectResult<SP_GET_RETURN_INFO_BY_ID_Result> SP_GET_RETURN_INFO_BY_ID(Nullable<int> mA_TRA_HANG)
        {
            var mA_TRA_HANGParameter = mA_TRA_HANG.HasValue ?
                new ObjectParameter("MA_TRA_HANG", mA_TRA_HANG) :
                new ObjectParameter("MA_TRA_HANG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_RETURN_INFO_BY_ID_Result>("SP_GET_RETURN_INFO_BY_ID", mA_TRA_HANGParameter);
        }
    
        public virtual ObjectResult<SP_GET_RETURN_LIST_Result> SP_GET_RETURN_LIST(string tEN_KHACH_HANG, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_NHAN_VIEN_NHAN, string tEN_NHAN_VIEN)
        {
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_NHAN_VIEN_NHANParameter = mA_NHAN_VIEN_NHAN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_NHAN", mA_NHAN_VIEN_NHAN) :
                new ObjectParameter("MA_NHAN_VIEN_NHAN", typeof(int));
    
            var tEN_NHAN_VIENParameter = tEN_NHAN_VIEN != null ?
                new ObjectParameter("TEN_NHAN_VIEN", tEN_NHAN_VIEN) :
                new ObjectParameter("TEN_NHAN_VIEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_RETURN_LIST_Result>("SP_GET_RETURN_LIST", tEN_KHACH_HANGParameter, fROM_DATEParameter, tO_DATEParameter, mA_NHAN_VIEN_NHANParameter, tEN_NHAN_VIENParameter);
        }
    
        public virtual ObjectResult<SP_GET_ROLE_OF_USER_Result> SP_GET_ROLE_OF_USER(Nullable<int> uSER_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ROLE_OF_USER_Result>("SP_GET_ROLE_OF_USER", uSER_IDParameter);
        }
    
        public virtual ObjectResult<SP_GET_SMS_MESSAGES_Result> SP_GET_SMS_MESSAGES(Nullable<int> mA_NHOM_NGUOI_DUNG, string tEN_NHOM_NGUOI_DUNG, string nOI_DUNG, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var mA_NHOM_NGUOI_DUNGParameter = mA_NHOM_NGUOI_DUNG.HasValue ?
                new ObjectParameter("MA_NHOM_NGUOI_DUNG", mA_NHOM_NGUOI_DUNG) :
                new ObjectParameter("MA_NHOM_NGUOI_DUNG", typeof(int));
    
            var tEN_NHOM_NGUOI_DUNGParameter = tEN_NHOM_NGUOI_DUNG != null ?
                new ObjectParameter("TEN_NHOM_NGUOI_DUNG", tEN_NHOM_NGUOI_DUNG) :
                new ObjectParameter("TEN_NHOM_NGUOI_DUNG", typeof(string));
    
            var nOI_DUNGParameter = nOI_DUNG != null ?
                new ObjectParameter("NOI_DUNG", nOI_DUNG) :
                new ObjectParameter("NOI_DUNG", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_SMS_MESSAGES_Result>("SP_GET_SMS_MESSAGES", mA_NHOM_NGUOI_DUNGParameter, tEN_NHOM_NGUOI_DUNGParameter, nOI_DUNGParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual int SP_GET_TON_KHO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_TON_KHO");
        }
    
        public virtual int SP_GET_TON_KHO_ALERT(string nAME)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_TON_KHO_ALERT", nAMEParameter);
        }
    
        public virtual int SP_GET_TON_KHO_ALL(string nAME)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_TON_KHO_ALL", nAMEParameter);
        }
    
        public virtual int SP_GET_TON_KHO_BY_ID(Nullable<int> iNPUT_ID)
        {
            var iNPUT_IDParameter = iNPUT_ID.HasValue ?
                new ObjectParameter("INPUT_ID", iNPUT_ID) :
                new ObjectParameter("INPUT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_TON_KHO_BY_ID", iNPUT_IDParameter);
        }
    
        public virtual int SP_GET_TON_KHO_BY_STORE_ID_AND_PRODUCT_ID(Nullable<int> sTORE_ID, Nullable<int> pRODUC_ID, ObjectParameter rETURN_VAL)
        {
            var sTORE_IDParameter = sTORE_ID.HasValue ?
                new ObjectParameter("STORE_ID", sTORE_ID) :
                new ObjectParameter("STORE_ID", typeof(int));
    
            var pRODUC_IDParameter = pRODUC_ID.HasValue ?
                new ObjectParameter("PRODUC_ID", pRODUC_ID) :
                new ObjectParameter("PRODUC_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_TON_KHO_BY_STORE_ID_AND_PRODUCT_ID", sTORE_IDParameter, pRODUC_IDParameter, rETURN_VAL);
        }
    
        public virtual ObjectResult<SP_GET_VALUE_ALL_HOA_DON_Result> SP_GET_VALUE_ALL_HOA_DON(Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> mA_KHACH_HANG, string tEN_KHACH_HANG, Nullable<int> mA_NHAN_VIEN_BAN, string tEN_NV_BAN, Nullable<int> mA_NHAN_VIEN_TT, string tEN_NV_TT, Nullable<int> sTATUS, Nullable<int> mA_KHU_VUC, string tEN_KHU_VUC)
        {
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var mA_KHACH_HANGParameter = mA_KHACH_HANG.HasValue ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(int));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var mA_NHAN_VIEN_BANParameter = mA_NHAN_VIEN_BAN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_BAN", mA_NHAN_VIEN_BAN) :
                new ObjectParameter("MA_NHAN_VIEN_BAN", typeof(int));
    
            var tEN_NV_BANParameter = tEN_NV_BAN != null ?
                new ObjectParameter("TEN_NV_BAN", tEN_NV_BAN) :
                new ObjectParameter("TEN_NV_BAN", typeof(string));
    
            var mA_NHAN_VIEN_TTParameter = mA_NHAN_VIEN_TT.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_TT", mA_NHAN_VIEN_TT) :
                new ObjectParameter("MA_NHAN_VIEN_TT", typeof(int));
    
            var tEN_NV_TTParameter = tEN_NV_TT != null ?
                new ObjectParameter("TEN_NV_TT", tEN_NV_TT) :
                new ObjectParameter("TEN_NV_TT", typeof(string));
    
            var sTATUSParameter = sTATUS.HasValue ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(int));
    
            var mA_KHU_VUCParameter = mA_KHU_VUC.HasValue ?
                new ObjectParameter("MA_KHU_VUC", mA_KHU_VUC) :
                new ObjectParameter("MA_KHU_VUC", typeof(int));
    
            var tEN_KHU_VUCParameter = tEN_KHU_VUC != null ?
                new ObjectParameter("TEN_KHU_VUC", tEN_KHU_VUC) :
                new ObjectParameter("TEN_KHU_VUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_VALUE_ALL_HOA_DON_Result>("SP_GET_VALUE_ALL_HOA_DON", fROM_DATEParameter, tO_DATEParameter, mA_KHACH_HANGParameter, tEN_KHACH_HANGParameter, mA_NHAN_VIEN_BANParameter, tEN_NV_BANParameter, mA_NHAN_VIEN_TTParameter, tEN_NV_TTParameter, sTATUSParameter, mA_KHU_VUCParameter, tEN_KHU_VUCParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> SP_GET_VALUE_OF_INVENTORY(Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SP_GET_VALUE_OF_INVENTORY", mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter);
        }
    
        public virtual ObjectResult<SP_HET_IM_BY_ID_Result> SP_HET_IM_BY_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HET_IM_BY_ID_Result>("SP_HET_IM_BY_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_IMPORT_REPORTER_Result> SP_IMPORT_REPORTER(Nullable<int> kIND, Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var kINDParameter = kIND.HasValue ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_IMPORT_REPORTER_Result>("SP_IMPORT_REPORTER", kINDParameter, mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<SP_IMPORT_REPORTER_DETAIL_Result> SP_IMPORT_REPORTER_DETAIL(Nullable<int> kIND, Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var kINDParameter = kIND.HasValue ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_IMPORT_REPORTER_DETAIL_Result>("SP_IMPORT_REPORTER_DETAIL", kINDParameter, mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> SP_IMPORT_REPORTER_SUM(Nullable<int> kIND, Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, string tEN_SAN_PHAM, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE)
        {
            var kINDParameter = kIND.HasValue ?
                new ObjectParameter("KIND", kIND) :
                new ObjectParameter("KIND", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SP_IMPORT_REPORTER_SUM", kINDParameter, mA_KHOParameter, mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, fROM_DATEParameter, tO_DATEParameter);
        }
    
        public virtual int SP_IMPORT_TRANSFER(Nullable<int> mA_PHIEU_CHUYEN, Nullable<System.DateTime> nGAY_NHAP, Nullable<int> mA_NHAN_VIEN, Nullable<int> mA_KHO, string gHI_CHU, ObjectParameter rETURN_VALUE)
        {
            var mA_PHIEU_CHUYENParameter = mA_PHIEU_CHUYEN.HasValue ?
                new ObjectParameter("MA_PHIEU_CHUYEN", mA_PHIEU_CHUYEN) :
                new ObjectParameter("MA_PHIEU_CHUYEN", typeof(int));
    
            var nGAY_NHAPParameter = nGAY_NHAP.HasValue ?
                new ObjectParameter("NGAY_NHAP", nGAY_NHAP) :
                new ObjectParameter("NGAY_NHAP", typeof(System.DateTime));
    
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(int));
    
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var gHI_CHUParameter = gHI_CHU != null ?
                new ObjectParameter("GHI_CHU", gHI_CHU) :
                new ObjectParameter("GHI_CHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IMPORT_TRANSFER", mA_PHIEU_CHUYENParameter, nGAY_NHAPParameter, mA_NHAN_VIENParameter, mA_KHOParameter, gHI_CHUParameter, rETURN_VALUE);
        }
    
        public virtual int SP_SALE_EXPORT(Nullable<int> mA_KHO, Nullable<int> mA_HOA_DON, Nullable<int> mA_NHAN_VIEN_THUC_HIEN, string tEN_KHACH_HANG, ObjectParameter rETURN_VALUE)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_HOA_DONParameter = mA_HOA_DON.HasValue ?
                new ObjectParameter("MA_HOA_DON", mA_HOA_DON) :
                new ObjectParameter("MA_HOA_DON", typeof(int));
    
            var mA_NHAN_VIEN_THUC_HIENParameter = mA_NHAN_VIEN_THUC_HIEN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_THUC_HIEN", mA_NHAN_VIEN_THUC_HIEN) :
                new ObjectParameter("MA_NHAN_VIEN_THUC_HIEN", typeof(int));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SALE_EXPORT", mA_KHOParameter, mA_HOA_DONParameter, mA_NHAN_VIEN_THUC_HIENParameter, tEN_KHACH_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int SP_THU_TIEN_XUAT_KHO(Nullable<int> mA_HOA_DON, Nullable<int> mA_NHAN_VIEN_THUC_HIEN, Nullable<double> sO_TIEN_KHACH_TRA, ObjectParameter rETURN_VALUE)
        {
            var mA_HOA_DONParameter = mA_HOA_DON.HasValue ?
                new ObjectParameter("MA_HOA_DON", mA_HOA_DON) :
                new ObjectParameter("MA_HOA_DON", typeof(int));
    
            var mA_NHAN_VIEN_THUC_HIENParameter = mA_NHAN_VIEN_THUC_HIEN.HasValue ?
                new ObjectParameter("MA_NHAN_VIEN_THUC_HIEN", mA_NHAN_VIEN_THUC_HIEN) :
                new ObjectParameter("MA_NHAN_VIEN_THUC_HIEN", typeof(int));
    
            var sO_TIEN_KHACH_TRAParameter = sO_TIEN_KHACH_TRA.HasValue ?
                new ObjectParameter("SO_TIEN_KHACH_TRA", sO_TIEN_KHACH_TRA) :
                new ObjectParameter("SO_TIEN_KHACH_TRA", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THU_TIEN_XUAT_KHO", mA_HOA_DONParameter, mA_NHAN_VIEN_THUC_HIENParameter, sO_TIEN_KHACH_TRAParameter, rETURN_VALUE);
        }
    
        public virtual int STMA_GET_GIA_TRI_HANG_BAN_TON(Nullable<int> mA_KHO, Nullable<int> mA_SAN_PHAM, ObjectParameter gIA_VON_HANG_BAN_TOTAL, ObjectParameter gIA_TRI_HANG_TON_TOTAL)
        {
            var mA_KHOParameter = mA_KHO.HasValue ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(int));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM.HasValue ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STMA_GET_GIA_TRI_HANG_BAN_TON", mA_KHOParameter, mA_SAN_PHAMParameter, gIA_VON_HANG_BAN_TOTAL, gIA_TRI_HANG_TON_TOTAL);
        }
    
        public virtual int SP_EXPORT_4_RETURN_2_PROVIDER(Nullable<int> iD, Nullable<int> sTORE_ID, Nullable<int> uSER_ID, ObjectParameter rETURN_VALUE)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var sTORE_IDParameter = sTORE_ID.HasValue ?
                new ObjectParameter("STORE_ID", sTORE_ID) :
                new ObjectParameter("STORE_ID", typeof(int));
    
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EXPORT_4_RETURN_2_PROVIDER", iDParameter, sTORE_IDParameter, uSER_IDParameter, rETURN_VALUE);
        }
    
        public virtual ObjectResult<SP_GET_WAITING_EX_2_PROVIDER_Result> SP_GET_WAITING_EX_2_PROVIDER(Nullable<int> sTORE_ID, string sTORE_NAME, Nullable<System.DateTime> fROM_DATE, Nullable<System.DateTime> tO_DATE, Nullable<int> sTATAUS)
        {
            var sTORE_IDParameter = sTORE_ID.HasValue ?
                new ObjectParameter("STORE_ID", sTORE_ID) :
                new ObjectParameter("STORE_ID", typeof(int));
    
            var sTORE_NAMEParameter = sTORE_NAME != null ?
                new ObjectParameter("STORE_NAME", sTORE_NAME) :
                new ObjectParameter("STORE_NAME", typeof(string));
    
            var fROM_DATEParameter = fROM_DATE.HasValue ?
                new ObjectParameter("FROM_DATE", fROM_DATE) :
                new ObjectParameter("FROM_DATE", typeof(System.DateTime));
    
            var tO_DATEParameter = tO_DATE.HasValue ?
                new ObjectParameter("TO_DATE", tO_DATE) :
                new ObjectParameter("TO_DATE", typeof(System.DateTime));
    
            var sTATAUSParameter = sTATAUS.HasValue ?
                new ObjectParameter("STATAUS", sTATAUS) :
                new ObjectParameter("STATAUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_WAITING_EX_2_PROVIDER_Result>("SP_GET_WAITING_EX_2_PROVIDER", sTORE_IDParameter, sTORE_NAMEParameter, fROM_DATEParameter, tO_DATEParameter, sTATAUSParameter);
        }
    
        public virtual ObjectResult<SP_GET_DE_OF_RE_2_PR_BY_ST_AND_INV_ID_Result> SP_GET_DE_OF_RE_2_PR_BY_ST_AND_INV_ID(Nullable<int> sTORE_ID, Nullable<int> iNVOICE_ID)
        {
            var sTORE_IDParameter = sTORE_ID.HasValue ?
                new ObjectParameter("STORE_ID", sTORE_ID) :
                new ObjectParameter("STORE_ID", typeof(int));
    
            var iNVOICE_IDParameter = iNVOICE_ID.HasValue ?
                new ObjectParameter("INVOICE_ID", iNVOICE_ID) :
                new ObjectParameter("INVOICE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_DE_OF_RE_2_PR_BY_ST_AND_INV_ID_Result>("SP_GET_DE_OF_RE_2_PR_BY_ST_AND_INV_ID", sTORE_IDParameter, iNVOICE_IDParameter);
        }
    }
}
