//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HOA_DON
    {
        public int MA_HOA_DON { get; set; }
        public string SO_HOA_DON { get; set; }
        public Nullable<int> MA_KHACH_HANG { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public Nullable<int> MA_NHAN_VIEN_BAN { get; set; }
        public string TEN_NHAN_VIEN_BAN { get; set; }
        public Nullable<System.DateTime> NGAY_BAN { get; set; }
        public Nullable<System.DateTime> NGAY_GIAO { get; set; }
        public string DIA_CHI_GIAO_HANG { get; set; }
        public Nullable<int> MA_NHAN_VIEN_THU_TIEN { get; set; }
        public string TEN_NV_THU_TIEN { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<double> SO_TIEN_KHACH_TRA { get; set; }
        public Nullable<double> SO_TIEN_NO_GOI_DAU { get; set; }
        public Nullable<int> MA_SAN_PHAM { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> DON_GIA { get; set; }
        public Nullable<double> PHAN_TRAM_CHIEC_KHAU { get; set; }
        public Nullable<int> MA_KHO_XUAT { get; set; }
    }
}
