//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NHAP_KHO
    {
        public int MA_NHAP_KHO { get; set; }
        public Nullable<System.DateTime> NGAY_NHAP { get; set; }
        public Nullable<int> MA_KHO { get; set; }
        public Nullable<short> LY_DO_NHAP { get; set; }
        public Nullable<int> MA_SAN_PHAM { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> GIA_VON { get; set; }
    }
}
